### ISSUE TITLE
你好，你的控件非常好用，只是我发现了一点美中不足

### ISSUE THREAD

**Issue by happying** [wangmchn/WMPageController#1]
今天偶然间发现了你的控件，特地下下来玩了一下，发现了一点小问题，就是当用手势滑动的时候，调用了slideMenuAtProgress:方法更新UI，但是并没有在其中设置item的selected，虽然不影响大局，但是这个selected属性在拓展的时候经常会用到，可能修复一下会比较好。

**Comment by wangmchn** [comment]
哈哈，感谢你的关注，是我疏忽了，感谢你的指出，我这就看下~ ：）
> 在 2015年6月18日，17:27，happying <notifications@github.com> 写道：
> 
> 会
