### ISSUE TITLE
大哥你好, 我是小白,问个关于使用WMPageController传值的问题

### ISSUE THREAD

**Issue by WQNMLGM** [wangmchn/WMPageController#10]
正在使用你的 WMPageController, 但是我发现它的init方法用的是添加class的方法, 现在我想实现从当前控制器向WMPageController管理的其中一个控制器传值, 想了好久都没有解决方法, 故此请教,望回复

**Comment by wangmchn** [comment]
请问下当前控制器是指创建`WMPageController`的控制器吗？还有传值的目的是什么呢？

**Comment by WQNMLGM** [comment]
就像WMPageController Demo 中的在前一个tableview中创建了WMPageController管理3个视图控制器, 向其中的一个控制器传一个ID, 做网络请求

**Comment by WQNMLGM** [comment]
但是因为WMPageController的 initWithViewControllerClasses 方法用的是Class, 不能用属性传值, 我是一个小白,不知怎么解决了

**Comment by wangmchn** [comment]
是每个控制器对应一个ID吗？然后这些是在之前的控制器通过网络获取的？
好像没有什么好的方法，用单例或者做一下本地缓存吧= =

**Comment by WQNMLGM** [comment]
是的, 想了很长时间好像除了单例也没别的方法了,  其实如果能在创建控制器的时候实例化控制器, 而不是直接接受控制器的Class,可能会更好用,比如在页面之间传用属性传数据等, 但我是小白,不知怎么修改

**Comment by WQNMLGM** [comment]
是的, 想了很长时间好像除了单例也没别的方法了,  其实如果能在创建控制器的时候实例化控制器, 而不是直接接受控制器的Class,可能会更好用,比如在页面之间传用属性传数据等, 但我是小白,不知怎么修改

**Comment by WQNMLGM** [comment]
是的, 想了很长时间好像除了单例也没别的方法了,  其实如果能在创建控制器的时候实例化控制器, 而不是直接接受控制器的Class,可能会更好用,比如在页面之间传用属性传数据等, 但我是小白,不知怎么修改

**Comment by WQNMLGM** [comment]
是的, 想了很长时间好像除了单例也没别的方法了,  其实如果能在创建控制器的时候实例化控制器, 而不是直接接受控制器的Class,可能会更好用,比如在页面之间传用属性传数据等, 但我是小白,不知怎么修改

**Comment by WQNMLGM** [comment]
是的, 想了很长时间好像除了单例也没别的方法了,  其实如果能在创建控制器的时候实例化控制器, 而不是直接接受控制器的Class,可能会更好用,比如在页面之间传用属性传数据等, 但我是小白,不知怎么修改

**Comment by wangmchn** [comment]
不太好改 因为整个都是通过class来的，要改的话会牵扯到挺多代码。。之所以用class是为了考虑多控制器的内存情况，合理的释放和创建

**Comment by WQNMLGM** [comment]
(⊙o⊙) 不明觉厉, 其实也不必要改, 自己尝试用单例解决把,感谢大神的分享

**Comment by wangmchn** [comment]
有问题继续交流 ：）
