### ISSUE TITLE
如何在导航栏的item上加红点?

### ISSUE THREAD

**Issue by LuisPorsche** [wangmchn/WMPageController#103]
试了很多方法都不管用

**Comment by wangmchn** [comment]
暂时还不支持这个功能。。。
看看下周有空的话再加这个功能吧

**Comment by LuisPorsche** [comment]
嗯,好,持续关注

**Comment by LuisPorsche** [comment]
希望能尽快添加上红点功能😭


发自网易邮箱大师
在2016年05月28日 17:22，Wang Ming 写道:

暂时还不支持这个功能。。。
看看下周有空的话再加这个功能吧

**Comment by wangmchn** [comment]
添加了该功能，具体例子在Pass Value文件夹内
只是自测了一下，可能会有bug，欢迎测试及反馈问题 😄

**Comment by LuisPorsche** [comment]
好的，加紧测试


发自网易邮箱大师
在2016年05月30日 17:09，Wang Ming 写道:

添加了该功能，具体例子在Pass Value文件夹内
只是自测了一下，可能会有bug，欢迎测试及反馈问题 😄

**Comment by LuisPorsche** [comment]
现在只是一个点,我把UIView改成Label试试
