### ISSUE TITLE
点击menu, 下面的scrollView动画效果

### ISSUE THREAD

**Issue by mxyolande** [wangmchn/WMPageController#109]
点击menu, 下面的scrollView动画效果, 能添加动画效果么? 
比方说我有 7 个控制器 0 ~ 6 
从 我在 0  点击menu到 6
能不能看起来像 5 -> 6一样的动画效果, 就向滑动 5 -> 6 一样

感觉好像有点复杂 qvq

**Comment by wangmchn** [comment]
这个库现在不支持这种动画效果，你可以使用UIPageViewController来实现这种的动画

**Comment by laoyur** [comment]
@wangmchn 就是因为UIPageViewController有各种奇奇怪怪的bug才找到你这里的  :)
这个feature还是挺重要的，比如从0->6，可能中间的1~5都需要做网络操作，如果能像UIPageViewController一样，直接用0跟6的VC做动画切换，无论显示效果上，还是性能上，都会比较好。

是否可以这样做，把6对应的vc拿到，然后临时将它的位置挪动到1所处的位置（即屏幕右侧），然后滚动过去，滚完后再将offset设对。缺点是滚动到1的过程中，如果用户再次执行滑动，会比较难处理，可以考虑这个过程中禁止二次滑动。

以上只是一个设想，并不是request  :)  再次感谢作者！
