### ISSUE TITLE
请问如何在实例化的时候给controller传值

### ISSUE THREAD

**Issue by zhangjinling** [wangmchn/WMPageController#11]
请问如何在实例化的时候给controller传值
因为tab页 ， 结构都一样只是 参数不一样  ，我想在实例化的时候传入参数！！
望解答，谢谢，辛苦了。。。

**Comment by wangmchn** [comment]
请问这个参数是通过网络请求获取的吗？没有想到特别好的解决方案，现在的想法是通过一个全局对象`(单例)`来保存数据，然后在各个子控制器中自取。

**Comment by zhangjinling** [comment]
首先谢谢您的开源代码，帮助了我。
您是这样实例化的 ：vcClass = [控制器名称 class];
我想在这个时候传入一个变量  ，我用alloc init不行  。直接点语法也不行，我ios不是特别厉害。
其实我就想在初始化的时候穿进去一个变量。

**Comment by wangmchn** [comment]
tab的标题是指哪个？底下的tabBar还是顶部滚动导航的菜单栏的标题？如果是顶部滚动导航的菜单栏的标题可以通过如下方法：
`#import "WMPageConst.h"`
`pageVC.postNotification = YES;`
在对应`childController` 通过 `NSNotificationCenter` 获取：
```
[[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(yourMethod:) name:WMControllerDidFullyDisplayedNotification object:nil]; //  或者 WMControllerDidAddToSuperViewNotification
- (void)yourMethod:(NSNotification *)note {
    NSLog(@"%@", [note userInfo]);
}
```

**Comment by zhangjinling** [comment]
请问在控制器实例化
    WMPageController *pageVC = [[WMPageController alloc] initWithViewControllerClasses:viewControllers andTheirTitles:titles];
的时候不能设置childController 的 属性吗？

**Comment by wangmchn** [comment]
你可以尝试为`WMPageController `添加两个属性，比如`@property (nonatomic, copy) NSArray *values;`
`values`是一个你希望为各个控制器赋值的值的集合，
然后第二个属性 `@property (nonatomic, copy) NSArray *keys;`
`keys`是属性名，`childController.h`里面定义的属性的名字，为`NSString`；
然后找到WMPageController.m：
```
// 添加子控制器
// 添加子控制器
- (void)addViewControllerAtIndex:(int)index {
    Class vcClass = self.viewControllerClasses[index];
    UIViewController *viewController = [[vcClass alloc] init];
    [viewController setValue:self.values[index] forKey:self.keys[index]];
    [self addChildViewController:viewController];
    viewController.view.frame = [self.childViewFrames[index] CGRectValue];
    [viewController didMoveToParentViewController:self];
    [self.scrollView addSubview:viewController.view];
    [self.displayVC setObject:viewController forKey:@(index)];
    
    [self backToPositionIfNeeded:viewController atIndex:index];
}
```
添加` [viewController setValue:self.values[index] forKey:self.keys[index]];`
利用`kvc`来设置属性。
如果不知道怎么做可以`E-mail`我，发你代码

**Comment by wangmchn** [comment]
或者QQ交流

**Comment by zhangjinling** [comment]
非常感谢！已经解决tab页面控制器的重用问题！使用 KVC设置属性的方法就可以解决。再次感谢。。

**Comment by Chren** [comment]
storyboard里的viewcontroller支持么？

**Comment by wangmchn** [comment]
hey,@Chren
暂时还不支持`storyboard`

**Comment by KONGFANJI** [comment]
能刷新本页面吗，我在导航栏上添加了一个菜单，点击菜单需要刷新本页面

**Comment by wangmchn** [comment]
@KONGFANJI 
刷新子页面吗？刷新子控制器(即传入控制器)的话和`WMPageController`无关的，以前怎么做现在一样做就好了

**Comment by KONGFANJI** [comment]
刷新整个页面。点击导航栏上的菜单，刷新整个页面，titles和其他数据都刷新

**Comment by wangmchn** [comment]
暂时还不支持，后续会加上reload功能，最近事情比较多，可能这周末有空会做，也可能会等些时间。
急用的话得找下其他更好的库了 : (

**Comment by KONGFANJI** [comment]
好的，谢谢啦

**Comment by iamjaswanth** [comment]
FizzLoyaltystampTableViewController *vc =  [[FizzLoyaltystampTableViewController alloc]init];
    FizzLoyaltystampTableViewController *vc1 =  [[FizzLoyaltystampTableViewController alloc]init];
    FizzLoyaltystampTableViewController *vc2 =  [[FizzLoyaltystampTableViewController alloc]init];
    
    NSString *strng = @"HI";
    NSString *strng1 = @"HI1";
    NSString *strng2 = @"HI2";
    
    VCArray = @[vc,vc1,vc2];
    titlearray = @[strng,strng1,strng2];
    
    WMPageController *pageview = [[WMPageController alloc]initWithViewControllerClasses:VCArray andTheirTitles:titlearray];

    pageview.pageAnimatable = YES;
   pageview.menuItemWidth = 85;
    pageview.postNotification = YES;
    pageview.bounces = NO;

when I load it I Cant see any thing on my screen?

**Comment by iamjaswanth** [comment]
How Can I access when view is  loaded initially when loading the controller?

**Comment by wangmchn** [comment]
Hey,@iamjaswanth
You need pass viewController's `Class` in the VCArray.
Like:
```Objective-c
Class *vc =  [FizzLoyaltystampTableViewController Class];
Class *vc1 =  [FizzLoyaltystampTableViewController Class];
Class *vc2 =  [FizzLoyaltystampTableViewController Class];
VCArray = @[vc,vc1,vc2];
```

**Comment by iamjaswanth** [comment]
Thanks

**Comment by iamjaswanth** [comment]
- (void)viewDidLoad {
    [super viewDidLoad];
    
    
    Class vc =  [FizzLoyaltystampTableViewController class];
    Class vc1 =  [FizzLoyaltystampTableViewController class];
    Class vc2 =  [FizzLoyaltystampTableViewController class];
    VCArray = @[vc,vc1,vc2];
    
    NSString *strng = @"HI";
    NSString *strng1 = @"HI1";
    NSString *strng2 = @"HI2";
    
    VCArray = @[vc,vc1,vc2];
    titlearray = @[strng,strng1,strng2];
    
    WMPageController *pageview = [[WMPageController alloc]initWithViewControllerClasses:VCArray andTheirTitles:titlearray];

    pageview.pageAnimatable = YES;
   pageview.menuItemWidth = 85;
    pageview.postNotification = YES;
    pageview.bounces = NO;

 
    
}
but still cant able to load it.help me

**Comment by iamjaswanth** [comment]
do I need to set any thing in story board ?

**Comment by wangmchn** [comment]
`WMPageController` is a controller.You need deal with it just like a `UIViewController`
Like this:
```Objective-C
// For example, In AppDelegate.
WMPageController *pageController = [[WMPageController alloc] initWithViewControllerClasses:VCArray andTheirTitles:titleArray];

UINavigationController *nav = [[UINavigationController alloc] initWithRootViewController:pageController];
self.window.rootViewController = nav;
```

**Comment by iamjaswanth** [comment]
can you explain clearly I am newbie to iOS

**Comment by iamjaswanth** [comment]
understood thanks for help

**Comment by wangmchn** [comment]
Well,when we use code to init a view controller with a navigationBar, we always init the view controller and navigation controller in `AppDelegate`'s method: 
`- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions`
Like this:
```Objective-C
UIViewController *vc = [[UIViewController alloc] init];
UINavigationController *nav = [[UINavigationController alloc] initWithRootViewController:vc];
self.window.rootViewController = nav;
```
So if you want a `WMPageController` with a `UINavigationBar`
we do like this:
```Objective-C
WMPageController *pageController = [[WMPageController alloc] initWithViewControllerClasses:VCArray andTheirTitles:titleArray];

UINavigationController *nav = [[UINavigationController alloc] initWithRootViewController:pageController];
self.window.rootViewController = nav;
```
It's the same with `UIViewController`.
also, If you want to push a controller,
```objective-c
WMPageController *pageController = [[WMPageController alloc] initWithViewControllerClasses:VCArray andTheirTitles:titleArray];
[self.navigationController pushViewController:pageController animated:YES];
```
Just regard it as `UIViewController`, when deal with it.

**Comment by wangmchn** [comment]
OK,It's fine.
New issue if has any problem.:smile:

**Comment by KONGFANJI** [comment]
请问能在菜单上添加背景图吗

**Comment by wangmchn** [comment]
需要自己在WMMenuView里面自行添加

**Comment by KONGFANJI** [comment]
好的  谢谢

**Comment by mxpasser** [comment]
很好用的库。想问个问题就是切换上面tab的时候，切换到新的页面怎么能让他们重新请求一次数据？目前好像只在viewDidLoad中请求过一次，切换的时候就没再请求了，盼复！😄

**Comment by wangmchn** [comment]
@mxpasser 
可以在-viewWillAppear:中做数据刷新

**Comment by mxpasser** [comment]
@wangmchn 多谢回复，解决了我的问题！
现在传参使用kvc，然后去源码中做修改,这个库是否可以优化这个地方!

**Comment by mxpasser** [comment]
@wangmchn 多谢回复，解决了我的问题！
现在传参使用kvc，然后去源码中做修改,是否可以优化这个地方!

**Comment by wangmchn** [comment]
@mxpasser 
现在不需要去源码中修改,已经暴露出KVC的数组属性了，设置values和keys就可以传参

**Comment by mxpasser** [comment]
@wangmchn 好的，多谢回复。

**Comment by IceTears1** [comment]
![3ef2fb5b-0cad-4048-995b-72720599c2f8](https://cloud.githubusercontent.com/assets/18476318/14551887/5f87cd14-030b-11e6-9519-2c8ce2da7490.png)
集成之后个别用户 崩溃

**Comment by huanghaiyanghhy** [comment]
没太看懂valus和keys这两个属性，究竟怎么做才能给子控制传值呢

**Comment by wangmchn** [comment]
可以参看最新代码pass value文件夹内demo
如有问题再进行交流

发自我的 iPhone

**Comment by huanghaiyanghhy** [comment]
多谢回复，问题已经解决，上次我用的版本太老了，没有datasource

**Comment by IceTears1** [comment]
最近没怎么上这个，没看到抱歉

**Comment by bigbigxh** [comment]
问一下，栏目过多时(超出屏幕显示范围)，通过滑动屏幕外的栏目进来。点击之后栏目会跳动好几次。请问怎么解决？
