### ISSUE TITLE
请问如何设置第一个menu保持不动呢， 我设置leftview滑动不能滚到我设置的leftview

### ISSUE THREAD

**Issue by YangSugar** [wangmchn/WMPageController#110]
请问如何设置第一个menu保持不动呢， 我设置leftview滑动不能滚到我设置的leftview

我看内部代码，只怪自己不知道咋改， 能给下思路么  谢谢啦

**Comment by wangmchn** [comment]
没看懂你的问题，什么叫“滑动不能滚到我设置的leftview”

发自我的 iPhone

**Comment by YangSugar** [comment]
self.menuView.leftView   我添加的这个 滑动页面怎么也滑动这个view里呢？  可以加QQ吗

**Comment by wangmchn** [comment]
这个不支持 抱歉

发自我的 iPhone
