### ISSUE TITLE
能够支持做一个类似于搜狐新闻中,最右边有一个自定义item的项目吗

### ISSUE THREAD

**Issue by nobeeJonh** [wangmchn/WMPageController#111]

**Comment by nobeeJonh** [comment]
求助啊啊啊

**Comment by wangmchn** [comment]
是指右边有固定的button吗？可以设置menuView的rightView来实现

**Comment by nobeeJonh** [comment]
是的,我试一下,谢谢

**Comment by nobeeJonh** [comment]
兄弟,问题还没解决,希望多多指点,拜托

**Comment by wangmchn** [comment]
1.指的是整个导航
2.rightView 和 navigationBar 的 rightBarButtonItem 相似，其次，需要理解的是，对于一个Controller，它的view需要在viewDidLoad之后才会存在，所以你一个controller继承至WMPageController，并在ViewDidload之后设置rightView

**Comment by wangmchn** [comment]
可以参考一下 Pass Value 文件夹里面的内容，这个demo有设置rightView

**Comment by nobeeJonh** [comment]
还得再麻烦你一下,我自定义一个类继承WMPageController,在viewDidLoad设置一些属性,有的属性并没有起到作用
override func viewDidLoad() {
        super.viewDidLoad()
        self.menuViewStyle = WMMenuViewStyle.Line
        self.titleColorNormal = UIColor.whiteColor()
        self.titleColorSelected = UIColor.whiteColor()
        self.menuItemWidth = 100
        self.titleSizeNormal = 17
        self.titleSizeSelected = 17
        // 设置标题栏的高度
        self.menuHeight = 36
        self.progressColor = UIColor.orangeColor()
        self.menuView.backgroundColor = UIColor.init(red: 10/255.0, green: 110/255.0, blue: 0/255.0, alpha: 1.0)
        
        addViews()
    }
self.titleColorNormal, self.titleColorSelected, self.titleSizeNormal, self.titleSizeSelected, self.progressColor没有起到作用

**Comment by wangmchn** [comment]
这些属性都是在init的时候设置的

**Comment by nobeeJonh** [comment]
我在自定义类中重写了init!(viewControllerClasses classes: [AnyClass]!, andTheirTitles titles: [String]!)方法并设置相关属性,运行错误,编译器告诉我让我实现init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: NSBundle?),我照做了,就运行正常了,我想知道为什么要让我写上init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: NSBundle?)

**Comment by Huang-Libo** [comment]
如果不在导航栏上能实现吗？比如添加类似网易新闻中的“➕”来打开切换栏目页面，位于菜单栏最右侧。

**Comment by wangmchn** [comment]
可以在viewdidiload里面设置menu view的right view

发自我的 iPhone

**Comment by Huang-Libo** [comment]
@wangmchn 谢谢！我还有一个问题，就是控制器能不能直接继承view controller（使用说明中写的需要继承自WMPageController），然后通过遵守WM库中的协议来实现？

**Comment by Huang-Libo** [comment]
@wangmchn 如果可以，除了遵守数据源协议，还有哪些协议要遵守？

**Comment by wangmchn** [comment]
@Huang-Libo 
WMPageController 是一个类似于 UINavigationController 的控制器，它管理了里面很多子控制器，这些控制器可以是任何你自己创建的。
而跟UINavigationController类似的，这个管理用的 WMPageController 需要继承自 WMPageController（就跟你自己的UINavigationController需要继承自系统的UINavigationController一样）
所以我不太清楚你需要自己定义一个WMPageController来做什么？如果说需要添加一些自己的视图的话，可以设置viewFrame属性来控制子控制器的大小。然后再自己在WMPageController的viewDidLoad方法中添加自己的视图即可

**Comment by Huang-Libo** [comment]
恩，明白了。
我目前发现一个小问题，如果数据是从网络加载的，那么在viewDidLoad中是还没有拿到网络数据的，这个时候设置menuView的rightView，是无效的，原因是menuView为nil。这种情境下，在[self reloadData]之后设置menuView有效。
对于这个问题，我有个想法，就是给rightView设置一个回调，当menuView不为nil的时候来执行回调再把rightView设置上去，不知可行否？请指教

**Comment by wangmchn** [comment]
@Huang-Libo 确实现在如果子控制器数是0的话是不添加menuView的，你可以在reload之后再设置rightView
