### ISSUE TITLE
为什么一退到后台控制器就会被销毁。

### ISSUE THREAD

**Issue by zhouwude** [wangmchn/WMPageController#113]

**Comment by wangmchn** [comment]
是有这个问题，由于我是用的 NSCache 做的缓存，而在后台清空数据是 NSCache 的一个默认特性，导致了这个现象。
我做一下修改

**Comment by gongyua** [comment]
一退到后台控制器就会被销毁，这个问题还是存在 @wangmchn 修改好了吗

**Comment by wangmchn** [comment]
@gongyua 
是最新版本还存在吗？提供下版本号？

**Comment by gongyua** [comment]
不好意思，是我自己之前改出的问题 重新你的新版是没问题的
