### ISSUE TITLE
menuView上的label能根据文字的多少自适应大小吗

### ISSUE THREAD

**Issue by Huang-Libo** [wangmchn/WMPageController#115]
我的菜单label中，有的文字只有两个，有点多达7个，按照WMPageController的默认行为，很多label被截断、显示省略号，目前我发现有这两个属性可以控制label的大小：

/**
 *  每个 MenuItem 的宽度
 *  The item width,when all are same,use this property  
 */   
`@property (nonatomic, assign) CGFloat menuItemWidth;`

/**
 *  各个 MenuItem 的宽度，可不等，数组内为 NSNumber.
 *  Each item's width, when they are not all the same, use this property, Put `NSNumber` in this array.  
 */  
`@property (nonatomic, copy) NSArray<NSNumber *> *itemsWidths;`

第一个属性是把所有的label设置为同样大小，第二个属性是手动给每个label设置大小，但是每个label该显示多大不好确定。label有一个sizeToFit功能，可以根据文字内容自适应大小，我尝试在WMMenuItem的init方法中加[self sizeToFit]，发现没有效果，请问有解决方案吗？

**Comment by wangmchn** [comment]
现在没有自适应的功能，可能在后期会加
你可以暂时先通过计算文字长度来设置item的宽度
