### ISSUE TITLE
跳转问题

### ISSUE THREAD

**Issue by LuisPorsche** [wangmchn/WMPageController#117]
有一个问题,现在有一个控制器,继承于WMPageController,里面添加了两个ViewController, 在第二个控制器中有一个按钮,点击按钮如何能回到第一个控制器呢?

**Comment by Huang-Libo** [comment]
@LuisPorsche 使用WMMenuView里面的selectItemAtIndex方法

**Comment by LuisPorsche** [comment]
好使, 感谢~
