### ISSUE TITLE
貌似用不了。。。。

### ISSUE THREAD

**Issue by AllLuckly** [wangmchn/WMPageController#12]
- (void)viewDidLoad {
    [super viewDidLoad];

    WMPageController *pageController = [self getDefaultController];
    pageController.title = @"Line";
}

- (WMPageController *)getDefaultController{
    NSMutableArray *viewControllers = [[NSMutableArray alloc] init];
    NSMutableArray *titles = [[NSMutableArray alloc] init];
    for (int i = 0; i < 4; i++) {
        Class vcClass;
        NSString *title;
        switch (i % 3) {
            case 0:
                vcClass = [YZViewController class];
                
                title = @"Greetings";
                break;
            case 1:
                vcClass = [YZSales_VC class];
                title = @"Hit Me";
                break;
            default:
                vcClass = [YZViewController class];
                title = @"Fluency";
                break;
        }
        [viewControllers addObject:vcClass];
        [titles addObject:title];
       
    }
    WMPageController *pageVC = [[WMPageController alloc] initWithViewControllerClasses:viewControllers andTheirTitles:titles];
    pageVC.pageAnimatable = YES;
    pageVC.menuItemWidth = 85;
    pageVC.postNotification = NO;
    
    return pageVC;
}
设置了没啥反应

**Comment by wangmchn** [comment]
用法错了 `WMPageController` 和 `UINavigationController` 以及 `UITabBarController` 的用法类似，你需要作为 `rootViewController` 或者由上一个控制器` push` `present`出来，
比如在 `tableView` 中，点击某一行：
```
[self.navigationController pushViewController:pageController animation:YES];
```

**Comment by AllLuckly** [comment]
有没有好点的方法   直接 丢一个ViewController里面。。。。

**Comment by wangmchn** [comment]
没懂你什么意思，那你那个 `viewController` 需要怎么显示？还不是需要成为 `rootViewController` 或者通过其他 `Controller` `push` `present`?

**Comment by AllLuckly** [comment]
直接显示成  tabBar  中的  一页

**Comment by wangmchn** [comment]
那你把`pageController`直接作为`tabBar`中的一页就好了

**Comment by AllLuckly** [comment]
OK  谢啦
