### ISSUE TITLE
能实现像网易新闻 tabBarItem为话题时 那样的效果么,我试了下,貌似不行.

### ISSUE THREAD

**Issue by zzdota** [wangmchn/WMPageController#120]
网易应该是外面固定宽度了,  内容里面只有2--3个的选项卡.

**Comment by Huang-Libo** [comment]
https://cloud.githubusercontent.com/assets/12227130/16383309/2a1a072e-3cb7-11e6-9cba-2cdc56a253d2.png

**Comment by wangmchn** [comment]
抽空添加了这个类型，新类型名字为 WMMenuVIewStyleSegmented，欢迎尝试

**Comment by yuhuixia** [comment]
我想问一下, 每次页面出现的时候, item 的个数不是一样的,这样的话怎么创建控制器啊  事先不知道需要创建多少个,根据网络请求进行的

**Comment by Huang-Libo** [comment]
@yuhuixia 拿到数据后在回调里面reload就行了。

**Comment by yuhuixia** [comment]
多谢啦
