### ISSUE TITLE
menu的title能居中显示吗

### ISSUE THREAD

**Issue by Huang-Libo** [wangmchn/WMPageController#121]
# 建议在mode枚举中添加这个样式
<img width="317" alt="2016-06-27 4 58 17" src="https://cloud.githubusercontent.com/assets/12227130/16374298/6af286c4-3c88-11e6-9f8e-95a03853d96e.png">

**Comment by wangmchn** [comment]
好的 会在近期添加布局mode

**Comment by Huang-Libo** [comment]
👍

**Comment by Huang-Libo** [comment]
还有以下这种mode，是网易新闻客户端用的比较多的，我也觉得挺实用。
![2016-06-27 10 33 02](https://cloud.githubusercontent.com/assets/12227130/16383309/2a1a072e-3cb7-11e6-9cba-2cdc56a253d2.png)
![2016-06-27 10 32 46](https://cloud.githubusercontent.com/assets/12227130/16383313/2e5a4146-3cb7-11e6-8dc4-83abed40c189.png)

**Comment by YangSugar** [comment]
请问MeneView的标题 中间的标题能否居中？

**Comment by Huang-Libo** [comment]
@YangSugar 你说的是上面图中的一种吗……

**Comment by wangmchn** [comment]
会在这周末添加~

**Comment by Huang-Libo** [comment]
@wangmchn 坐等😄

**Comment by YangSugar** [comment]
给力！

**Comment by wangmchn** [comment]
先添加了 WMMenuViewLayoutMode 的枚举，现在还存在的问题是，如果设置了showOnNavigationBar，那么当左右两个barButtonItem宽度不一样的时候，会有偏移（在showOnNavigationBar的时候会根据左右两个item压缩MenuView的宽度的，所以如果要居中可以设置两个相同大小的barButtonItem，比如你图片上右边有一个搜索按钮，可以左边添加一个透明的view，当然你也可以设置itemsMargins）

对于网易新闻那种模式，现在卡在了第一步，起名字上面，有什么好的建议吗- -

**Comment by Huang-Libo** [comment]
@wangmchn 网易新闻这种模式，像改造升级的UISegmentedControl控件，不如就叫WMMenuViewSegmentedMode，如何？

**Comment by wangmchn** [comment]
已经添加这种类型了! 🎉🎉
