### ISSUE TITLE
最新版的WMPageController跟MBProgressHUD有冲突

### ISSUE THREAD

**Issue by YangSugar** [wangmchn/WMPageController#123]
我放到一起 添加到一起就会有冲突 不能编译

**Comment by wangmchn** [comment]
能否给下错误的信息？

发自我的 iPhone

**Comment by Huang-Libo** [comment]
@YangSugar 我试了用MBProgressHUD 0.9.2 和 WMPageController 1.6.4，没问题呀。

**Comment by YangSugar** [comment]
今天我用pod集成了下，好了。可能是我这边问题，不是WMPageController的事。
