### ISSUE TITLE
请问 当titles只有一个时可以隐藏掉上部视图吗

### ISSUE THREAD

**Issue by a514754574** [wangmchn/WMPageController#125]
请问 当titles只有一个时可以隐藏掉上部视图吗  谢谢回答

**Comment by wangmchn** [comment]
这个需要自己在合适的时机（viewDidload之后）设置 `self.memuView.hidden = YES；` 了

**Comment by a514754574** [comment]
我在viewDidAppear里面调用self.memuView.hidden = YES； 他还是有白条条哈，白条条不能隐藏是吧

**Comment by Huang-Libo** [comment]
@wangmchn @a514754574 白条应该是hidden操作后menuView的约束或者是frame没有更新引起的？

**Comment by wangmchn** [comment]
是的，可以在更新的同时设置下viewFrame属性

发自我的 iPhone

**Comment by githubzxq** [comment]
这个问题解决了吗？

**Comment by wangmchn** [comment]
我会在近期添加一个属性来开关当只有一个控制器时，menuView的显示情况

**Comment by a514754574** [comment]
开关添加了吗 大哥

**Comment by Huang-Libo** [comment]
@a514754574 其实我没有想通只有一个控制器的时候为什么要用page contrller

**Comment by a514754574** [comment]
动态的嘛

**Comment by Huang-Libo** [comment]
@a514754574 这个还真没见过。。

**Comment by wangmchn** [comment]
@a514754574 抱歉，给忘了。。还没加，这周末加上

**Comment by MrCaiWH** [comment]
这个问题解决了吗 @wangmchn
