### ISSUE TITLE
WMPageController重用机制导致下拉刷新时间(lastUpdatedTime)被覆盖

### ISSUE THREAD

**Issue by Huang-Libo** [wangmchn/WMPageController#126]
我的WMPageController下有多个UITableViewController，每个UITableViewController都应该有lastUpdatedTime，但是在使用WMPageController的时候，只要有一个UITableViewController进行了下拉刷新，其他UITableViewController的lastUpdatedTime都变成了和当前UITableViewController一样的值。这应该是WMPageController的重用机制引起的。请问有办法解决此类问题吗，或者给一个接口来关闭controller重用？
（注：我使用的下拉刷新框架是MJRefresh）

**Comment by wangmchn** [comment]
不是的，理论上WMPageController中的所有控制器都是只缓存，不重用的。也就是每个控制器都是独立的。
看看是否是继承了同一个控制器？并在夫类里面实现了lastUpdateTime的更新？

发自我的 iPhone

**Comment by Huang-Libo** [comment]
是继承的同一个控制器，但每个控制器对象都应该有自己的lastUpdateTime属性吧，为什么会发生覆盖行为呢，也许是MJRfresh自己获取时间的机制导致的？

**Comment by wangmchn** [comment]
现在这样说我也说不出是哪里出的问题，理论上是不应该出现这种情况的。
如果可以的话，提供一个简单的demo可能会比较好找问题

**Comment by Huang-Libo** [comment]
好的，等我忙完这阵写个Demo给你看看，到时候直接发你gmail邮箱。
