### ISSUE TITLE
iOS8下tableview cell左滑删除

### ISSUE THREAD

**Issue by hongchenxi** [wangmchn/WMPageController#128]
iOS8下tableview cell左滑删除手势不响应。

**Comment by Huang-Libo** [comment]
@hongchenxi demo里面就有cell的左滑删除功能，你可以参考Demo里面的代码。

**Comment by wangmchn** [comment]
@hongchenxi 是只有iOS8不响应？

**Comment by wangmchn** [comment]
Close because lack of information.

**Comment by ghysrc** [comment]
@wangmchn 更新了您的最新版本后，子 Controller 里 TableView 的左滑手势失效了，上一个版本还是正常的。
