### ISSUE TITLE
请问为啥numbersOfChildControllersInPageController这个方法会调用多次

### ISSUE THREAD

**Issue by iOSyan** [wangmchn/WMPageController#129]
在storyboard的demo里打印了一下 这个代理方法numbersOfChildControllersInPageController调用了45次
每次滑动又调用很多次，导致滑动的时候有点卡顿~

**Comment by wangmchn** [comment]
是这样的，这个方法会在任何需要判断个数的时候被调用，我在内部没有做临时变量的缓存，主要是为了刷新的时候方便以及数据统一。
所以在这个方法中，最好是简单的返回一个数据，self.xxArray.count 之类的。

**Comment by wangmchn** [comment]
不过调用45次有点多？是用了autolayout？

**Comment by iOSyan** [comment]
我是直接在你的demo里打印的哦，跟storyboard没关，因为Pass Value里面打印次数也是很多

**Comment by wangmchn** [comment]
因为在viewdidlayoutsubviews中做了控制器个数判断，应该是这个问题造成的，我会在下次更新的时候添加一个临时变量来存，而不是每次问datasource要，这样应该可以避免太多次调用的问题

**Comment by iOSyan** [comment]
恩恩 谢谢开源~库很好用

**Comment by wangmchn** [comment]
最新的代码加了一个私有变量存储，应该解决了多次调用的问题~
