### ISSUE TITLE
请问下 怎么获取页面的跳转事件

### ISSUE THREAD

**Issue by a514754574** [wangmchn/WMPageController#130]
我要另外点击某个按钮跳转到某个子页面，怎么获取子页面的跳转事件阿？

**Comment by wangmchn** [comment]
不太明白你的意思，能更详细点吗

发自我的 iPhone

**Comment by a514754574** [comment]
![Uploading 屏幕快照 2016-07-05 下午12.41.34.png…]()

上面是pageCotroller的子页面  我要跳转到他的选择的子页面  怎么跳转

**Comment by Huang-Libo** [comment]
@a514754574 
WMPageController的代理方法
`- (void)pageController:(WMPageController *)pageController willEnterViewController:(__kindof UIViewController *)viewController withInfo:(NSDictionary *)info;
`
`- (void)pageController:(WMPageController *)pageController didEnterViewController:(__kindof UIViewController *)viewController withInfo:(NSDictionary *)info;
`

**Comment by wangmchn** [comment]
@a514754574 图挂了。
你可以直接在子页面拿到WMPageController
```
#import <WMPageController> 
// ...
// ...
WMPageController *pageController = (WMPageController *)self.parentViewController;
pageControler.selectIndex = n;
```
