### ISSUE TITLE
貌似有内存泄漏

### ISSUE THREAD

**Issue by jianjianhao** [wangmchn/WMPageController#131]
<img width="735" alt="6ec08b8f-71d2-4866-975e-975fed9c3ed5" src="https://cloud.githubusercontent.com/assets/12797357/16612680/ce355658-439a-11e6-8a41-022ea9f8b95d.png">

- (void)slideMenuAtProgress:(CGFloat)progress {
    if (self.progressView) {
        self.progressView.progress = progress;
    }
    NSInteger tag = (NSInteger)progress + WMMenuItemTagOffset;
    CGFloat rate = progress - tag + WMMenuItemTagOffset;
    WMMenuItem *currentItem = (WMMenuItem *)[self viewWithTag:tag];
    WMMenuItem *nextItem = (WMMenuItem *)[self viewWithTag:tag+1];
    if (rate == 0.0) {
        rate = 1.0; //这里用Xcode分析了有警告
        [self.selItem deselectedItemWithoutAnimation];
        self.selItem = currentItem;
        [self.selItem selectedItemWithoutAnimation];
        [self refreshContenOffset];
        return;
    }
    currentItem.rate = 1-rate;
    nextItem.rate = rate;
}

**Comment by wangmchn** [comment]
确实多余了，感谢指出

**Comment by wangmchn** [comment]
已经删去
