### ISSUE TITLE
"updateBadgeViewAtIndex" badge was updated to the wrong title

### ISSUE THREAD

**Issue by ghysrc** [wangmchn/WMPageController#134]
I use WMPageController in a swift project, the objc version.
I have a MessageController, there are two kinds of message. So I have two titles in WMMenuView. Here is the code:
```
    override func menuView(menu: WMMenuView!, badgeViewAtIndex index: Int) -> UIView! {
        if index == 0 {
            return nil
        }
        if MessageUitls.hasUnreadMessage() {
            let badge = UIView(frame: CGRectMake(60, 20, 10, 10))
            badge.setCornerRadius(radius: 5)
            badge.backgroundColor = Theme.Color.Red
            return badge
        } else {
            return nil
        }
    }
    override func viewWillAppear(animated: Bool) {
        super.viewWillAppear(animated)
        self.menuView.updateBadgeViewAtIndex(1)
    }
```
When I have unread messages, I open this controller, the badge is showing on the second title, it works all right. But when I navigated to next controller, came back, the "updateBadgeViewAtIndex" method was called, then I see the badge is showing on the first title, not the second where it should be.
PS: I didn't read the messages in the next controller.

**Comment by wangmchn** [comment]
Hi,@ghysrc 
Thanks for the issue. It's a bug and I have made some fixs.
Tell me whether it works! 😃

**Comment by ghysrc** [comment]
@wangmchn It works all right now. Thanks
