### ISSUE TITLE
第一个和最后一个控制器会变得可以斜滑 ,怎么解决

### ISSUE THREAD

**Issue by kunpengapple** [wangmchn/WMPageController#136]
ll

**Comment by wangmchn** [comment]
关闭otherGestureRecognizerSimultaneously属性，开启的话还没法解决。

**Comment by kunpengapple** [comment]
有什么思路解决呢?

**Comment by wangmchn** [comment]
首先要知道你出于什么目的设置的otherGestureRecognizerSimultaneously = YES;
其次，问题给的信息太少了，我做不出什么的判断。（好在这个问题以前有人提出过，不然我都不知道怎么重现这个问题，所以在提问的时候应该有对问题的详细描述、关键代码、自己的分析等等任何有可能有用的信息。）
这个问题是手势冲突造成的，你可以在WMScrollView里面的手势代理中对自己的冲突手势做一些判断和优先级设置。
对于这个问题，我暂时做不出什么比较好的改进，如果有什么好的解决思路，非常期待。

**Comment by kunpengapple** [comment]
好的,谢谢,

**Comment by kunpengapple** [comment]
我是左边有个侧滑栏,需要用到手势必须设置的otherGestureRecognizerSimultaneously = YES 才生效,同时上倾斜滑动第一个tableview时会出现倾斜

**Comment by wangmchn** [comment]
@kunpengapple 
现在确实是存在这个bug，我暂时还没有解决好，你可以在WMScrollView里面添加对手势的判断~
例如下面是tableViewCell删除手势的冲突的解决方法：
```
- (BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldRequireFailureOfGestureRecognizer:(UIGestureRecognizer *)otherGestureRecognizer {
    //MARK: UITableViewCell 自定义手势可能要在此处自行定义
    if ([otherGestureRecognizer.view isKindOfClass:NSClassFromString(@"UITableViewWrapperView")] && [otherGestureRecognizer isKindOfClass:[UIPanGestureRecognizer class]]) {
        return YES;
    }
    return NO;
}
```
类似的，对于你的冲突手势，可能也要做一些类似的判断，但是我这边现在没有一个好的方法，期待你的建议~
