### ISSUE TITLE
能否实现按需加载ViewController

### ISSUE THREAD

**Issue by liuweiisme** [wangmchn/WMPageController#137]
一个界面中，有5个Menu共用一个ViewController,我在ViewController中的viewDidLoad请求数据，加载完整个Menu后，我从第一个ViewController直接点击到最后一个，会请求4次。请问是否能按需加载，我点击到哪个Menu，在加载相应的ViewController？

**Comment by wangmchn** [comment]
关闭滚动动画可以避免这个情况

**Comment by wangmchn** [comment]
或者在下面这个代理中做数据加载
```
- (void)pageController:(WMPageController *)pageController lazyLoadViewController:(__kindof UIViewController *)viewController withInfo:(NSDictionary *)info;
```

**Comment by wangmchn** [comment]
或者在下面这个代理中做数据加载
- (void)pageController:(WMPageController *)pageController lazyLoadViewController:(__kindof UIViewController *)viewController withInfo:(NSDictionary *)info;

**Comment by liuweiisme** [comment]
我从第一个直接点击到最后一个,在点击到第二个，lazyLoadViewController 方法会不执行。

**Comment by wangmchn** [comment]
是的，没有停顿到的控制器不会执行，只有目标控制器才会执行
