### ISSUE TITLE
初始化设置progressColor之后就不能再改变progress的颜色了吗？

### ISSUE THREAD

**Issue by nobeeJonh** [wangmchn/WMPageController#138]
初始化设置progressColor之后就不能再改变progress的颜色了吗？

**Comment by Huang-Libo** [comment]
@nobeeJonh 应该是可以改的，能拿到这个对象就能改属性刷新UI

**Comment by wangmchn** [comment]
可以的，设置self.menuView.progressView.color就可以，之后记得调用self.menuView.progressView的setNeedsDisplay方法

**Comment by nobeeJonh** [comment]
@wangmchn 谢谢

**Comment by bigNiuSanMao** [comment]
> 可以的，设置self.menuView.progressView.color就可以，之后记得调用self.menuView.progressView的setNeedsDisplay方法

调用 setNeedsDisplay方法后  会崩溃  提示 drawrect中 这个 位置 崩溃 CGContextSetFillColorWithColor(ctx, self.color);
