### ISSUE TITLE
作者大神，有个问题请教

### ISSUE THREAD

**Issue by XHaller** [wangmchn/WMPageController#141]
很喜欢你的项目！我读了读源码。
WMProgressView.m 中的 step 变量是做什么的？
-(void)progressChanged 方法的原理是什么啊？如果有时间请解答下！
万谢！

**Comment by wangmchn** [comment]
你好，
先回答第二个问题，progressChanged 由 CADisplayLink（与NSTimer类似，但其调用频率与屏幕刷新频率相同，大概没1/60秒调用一次） 调用，也就是说，我在每次屏幕刷新的时候计算出当前状态的进度条应该在的位置即长度，并绘制到屏幕上。
在progressChanged方法中，主要就是计算出位置（progress，对于progress，假如有10个item，那么progress就是0~9，例如，当进度条在第2个item和第3个item之间是，progress就等于1.5）。
对于step，首先要知道gap变量，gap记录了progress的当前位置与目标位置的距离，比如，我现在在第一个item下面（progress=0），我点击第二个item，那么调用[x moveToPostion:1];也就是gap等于 （1-0）= 1，而step就是我每次前进的相对位移比例.（step = gap / 15，即我在15次绘制下结束,在这个例子中，我每次前进距离的 1/15）

**Comment by XHaller** [comment]
好的懂了 谢谢
