### ISSUE TITLE
当所有item的宽度加起来小于屏幕宽时，PageController会自动帮助排版，添加每个item之间的间隙以填充整个宽度。 产品需要：不希望这样。一律靠左排。能实现吗？

### ISSUE THREAD

**Issue by githubzxq** [wangmchn/WMPageController#142]
当所有item的宽度加起来小于屏幕宽时，PageController会自动帮助排版，添加每个item之间的间隙以填充整个宽度。
产品需要：不希望这样。一律靠左排。能实现吗？

**Comment by wangmchn** [comment]
现在OC版本有这个排版了，设置MenuViewLayoutMode就可以方便的实现。
如果使用的swift版本的话（swift版本代码有些落后于OC），需要自己设置itemsMargins数组，比较复杂

**Comment by githubzxq** [comment]
最新版本有了，看到了。不错，这个控件强大，非常感谢。棒棒哒。

**Comment by wangmchn** [comment]
感谢支持，欢迎提意见哈~
