### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by ProgramerSunny** [wangmchn/WMPageController#144]
如果有4个或者以上item的情况下，初次进入然后点击第二个item，会进入第二个controller ，但是item的选中状态全部消失，并且progress会跑到第三个item下面。

**Comment by wangmchn** [comment]
你好，请问是使用的最新代码吗？
我在测试过程中没有遇到这样的情况，能否提供下更多信息，例如：关键代码、demo？

**Comment by ProgramerSunny** [comment]
由于担心是旧的代码，我又换成cocoapod导入，但是还是出现了这样的问题。相关代码如下：


`
- (NSArray<NSString *> *)titles {
    return @[ @"未完成", @"已完成", @"已作废", @"退款列表" ];
}

- (instancetype)init {
    if (self = [super init]) {
        self.menuItemWidth = [[UIScreen mainScreen] bounds].size.width / self.titles.count;
        self.menuViewStyle = WMMenuViewStyleLine;
        self.titleSizeSelected = 14.0f;
        self.titleSizeNormal = 14.0f;
        self.menuHeight = 44;
        self.titleColorNormal = [UIColor colorWithHexString:@"999999"];
        self.titleColorSelected = [UIColor colorWithHexString:@"35B6F9"];
    }
    return self;
}

#pragma mark - WMPageController DataSource
- (NSInteger)numbersOfChildControllersInPageController:(WMPageController *)pageController {
    return self.titles.count;
}

- (NSString *)pageController:(WMPageController *)pageController titleAtIndex:(NSInteger)index {

    return self.titles[index];
}

- (__kindof UIViewController *)pageController:(WMPageController *)pageController viewControllerAtIndex:(NSInteger)index {
    if (index == 3) return [[DrawBackListController alloc] init];
    OrderListViewController *listViewController = [[OrderListViewController alloc] init];
    int i;
    if (index == 0)
        i = 6;
    else if (index == 1)
        i = 9;
    else if (index == 2)
        i = 8;
    listViewController.type = [NSString stringWithFormat:@"%@", @(i)];
    return listViewController;
}`

**Comment by wangmchn** [comment]
这个问题很奇怪，我还是复现不到，请问下WMPageController是否还和其他控制器有什么父子关系？
除了这些还有进行什么设置么。

**Comment by ProgramerSunny** [comment]
在这个项目中WMPageController 是并没有跟其他控制器有什么父子关系，然后我怀疑可能是我给UIViewController加了一个类别。于是我重新创建了一个demo，然后把在这个项目中使用到的相关的类都导入进来（包括这个类别），这个问题就消失了，最后我通过添加预加载机制暂时解决了这个问题；加入一下代码：
‘self.preloadPolicy = WMPageControllerPreloadPolicyNeighbour;’
这个bug消失。

**Comment by wangmchn** [comment]
所以重新创建了项目后，依旧导入你的UIViewController的类别，这个bug是不存在的？
但是原先的项目却存在这个问题？
这个我也不清楚怎么回事，好在意你的类别做了什么。
