### ISSUE TITLE
是不是你的框架只能在根控制器

### ISSUE THREAD

**Issue by ChinaArJun** [wangmchn/WMPageController#147]
请问 self.navigationController pushViewController：WMPageController   可以实现这样的操作吗，我在实现的时候报错，是不是你的框架只能在根控制器

**Comment by wangmchn** [comment]
可以这样操作，为何不把报错信息贴一下呢？

**Comment by ChinaArJun** [comment]
[@wangmchn]  错误信息 : libc++abi.dylib: terminate_handler unexpectedly threw an exception   显示直接不能跳转~~   并没有看到你demo有这样的示例，是不是UINavigationBar.的返回手势和你要处理的事件冲突了

**Comment by ChinaArJun** [comment]
我是需要将WMPageController显示在头部上面

**Comment by wangmchn** [comment]
没有更多的信息了吗？将WMPageController显示在头部上面是指菜单栏显示在NavigationBar上么？
你可以看下Demo里面Code文件夹下的例子：[Code](https://github.com/wangmchn/WMPageController/tree/master/WMPageControllerDemo/Code)
这里就是从另外的控制器push到WMPageController的，不知道你问的是不是这个

**Comment by ChinaArJun** [comment]
谢谢哦，就是这个~
