### ISSUE TITLE
ViewFramDemo  列表滑动头部动画显示有问题

### ISSUE THREAD

**Issue by maxiaofei123** [wangmchn/WMPageController#149]
当cell内容很少时 拖动cell 头部视图显示会闪动

**Comment by Huang-Libo** [comment]
@maxiaofei123 给代码和图看看

**Comment by maxiaofei123** [comment]
就是这个github的demo，吧cell内容设置少点就能发现了，不过没关系啦，我自己用其他的写了

**Comment by xyxdasnjss** [comment]
@maxiaofei123  我也遇到这个问题了，请问是怎么解决的？

**Comment by maxiaofei123** [comment]
你加我QQ 1003064169  我传输给你， 其实我之前有提交一份修改的，作者没懂我的意思 哈哈哈 没采用。

**Comment by qingyigeli** [comment]
请问闪动怎么解决的啊？

**Comment by wangmchn** [comment]
Try this: https://github.com/wangmchn/WMPageController/commit/1dd637a794d7155421def2a504c3d8dfa47eb75c

**Comment by wangmchn** [comment]
合并到：https://github.com/wangmchn/WMPageController/issues/204
