### ISSUE TITLE
数据请求问题

### ISSUE THREAD

**Issue by yangbenben** [wangmchn/WMPageController#150]
上面的title栏  我想通过后台返回给我  应该在哪个地方改变数据操作呢？

**Comment by yangbenben** [comment]
还有，YBPageController *pageVC = [[YBPageController alloc] initWithViewControllerClasses:viewControllers andTheirTitles:titles];
我看到viewControllers是定死的数组，如何根据滑动不同的titleID加载对应的ViewController来展示数据？求教

**Comment by Huang-Libo** [comment]
@yangbenben 有一个数据源协议可以很方便地设置title和controller，WMPageControllerDataSource

**Comment by yangbenben** [comment]
Huang-Libo 谢谢。已经解决！
