### ISSUE TITLE
UI界面绘制

### ISSUE THREAD

**Issue by yangbenben** [wangmchn/WMPageController#153]
我想在标题Title栏item中间加入竖向分割线，请问我应该加在什么地方？

**Comment by wangmchn** [comment]
可在- (UIView *)menuView:(WMMenuView *)menu badgeViewAtIndex:(NSInteger)index;代理中返回一个带 frame 的竖线 view

**Comment by yangbenben** [comment]
但是我设置了pageVC.menuView.delegate = self;
    pageVC.menuView.dataSource = self;之后，代理和数据源方法并没有执行

**Comment by wangmchn** [comment]
menuview 的数据源和代理都是 self，不需要自己设置的
你只需要在子类添加这个方法就行了

**Comment by yangbenben** [comment]
明白了  已经解决！谢谢  这个库确实很好用，可操作性很高。👍

**Comment by wangmchn** [comment]
：）
