### ISSUE TITLE
不能二级WMPageController？

### ISSUE THREAD

**Issue by GuessEver** [wangmchn/WMPageController#156]
我想用这个做一个二级tab，但是第二级的menu会重合在一级的下面，也就是二级没有自动向下偏移
请问是本来就不行，还是我忘了什么设置？

**Comment by Huang-Libo** [comment]
@GuessEver 能给个二级tab的示意图吗

**Comment by GuessEver** [comment]
@Huang-Libo 
声明了两个WMPageController，为了便于看重叠部分，我把Main的menuHeight设为40，Sub的设为80
![image](https://cloud.githubusercontent.com/assets/9291770/17588741/7afc4610-6003-11e6-9417-b138d0f48273.png)
![image](https://cloud.githubusercontent.com/assets/9291770/17588745/820163f0-6003-11e6-9f61-c66dafec04da.png)

AppDelegate如下
![image](https://cloud.githubusercontent.com/assets/9291770/17588741/7afc4610-6003-11e6-9417-b138d0f48273.png)

效果如下，可以很明显发现Sub重叠在了Main下面
![image](https://cloud.githubusercontent.com/assets/9291770/17588760/a4e5e490-6003-11e6-90dd-35bfb2570236.png)

**Comment by wangmchn** [comment]
可能需要设置下 `子PageController` 的 `viewFrame` 属性，确实没考虑到这种情况

**Comment by GuessEver** [comment]
@wangmchn 我试过了，似乎没什么用，也试过了masonry约束

还有一个问题，当放在UISplitViewController的第二个页面(detailView)的时候，设备切换到手机（或者iPad的slide over模式），上面的的tabBar重叠在了NavigationBar下面

**Comment by Huang-Libo** [comment]
@GuessEver 这个需求确实有点复杂，其实有两级菜单的时候，也只有一个能响应左右滑动的手势，所以倒不如把第一级（一般是菜单项比较少的）的用segment来实现并放在导航栏上，而二级菜单（菜单项比较多的）用WMPageController来实现。这样设计UI可能都会好看点

**Comment by GuessEver** [comment]
好的，十分感谢～

不过还有个问题，就是前面说的
```
当放在UISplitViewController的第二个页面(detailView)的时候，设备切换到手机（或者iPad的slide over模式），上面的的tabBar重叠在了NavigationBar下面
```

**Comment by Huang-Libo** [comment]
@GuessEver UISplitViewController是iPad专用的控制器，iOS8加入了size classes，并且允许iPhone上使用UISplitViewController，目前WMPageController还不支持使用storyboard，所以size classes是不是也不好使了？@wangmchn 
而slide over的分页模式是不是需要单独适配呢？
最好tabBar重叠在了NavigationBar下面是什么意思？你是指menuView重叠在NavigationBar下面了吗？

**Comment by GuessEver** [comment]
@Huang-Libo  slide over是iPad默认支持的，当宽度到拖到半屏的时候，就和手机一样了，这个时候menuView就重叠在了navigationBar下面了

WMPageController除了直接设置viewFrame之外，能不能用masonry去约束界面大小呢？因为要做适配，直接去设置viewFrame可能不太方便

**Comment by Huang-Libo** [comment]
@GuessEver  slide over的适配还真没做过，这个得问问作者。@wangmchn

**Comment by wangmchn** [comment]
@Huang-Libo @GuessEver 
周末去玩了，回复晚了抱歉。
现在还不支持masonry的，目前得需要手动设置viewFrame，抱歉

**Comment by GuessEver** [comment]
嗯知道啦～谢谢你们！总体还是非常好用的

**Comment by Huang-Libo** [comment]
@wangmchn 不支持masonry是指的哪些UI的设置不支持，能详细说一下吗？因为我项目同时用了WMPageController和masonry，貌似没有什么问题。

**Comment by wangmchn** [comment]
@Huang-Libo 
主要是对于WMPageController.view以及scrollview，以及对于子控制器的视图
而对于WMPageController中自己添加的子视图，以及子控制器中添加的子视图（vc.view.subview）运用理论上都是没有问题的
