### ISSUE TITLE
如何使用Masonry进行约束

### ISSUE THREAD

**Issue by EMNEIL** [wangmchn/WMPageController#157]
分页顶部有一个headerView,如何使用Masonry进行和headerView的约束，
代码如下：
      WMPageController *wmvc = [[WMPageController alloc]initWithViewControllerClasses:vcArray andTheirTitles:insuranceCategory];
    [wmvc.view mas_makeConstraints:^(MASConstraintMaker *make) {
      
        make.top.equalTo(headerView).offset(10);
        make.right.left.mas_equalTo(0);
        make.height.mas_equalTo(HEIGHT);
    }];

像上面那样写  会把headerview覆盖

**Comment by wangmchn** [comment]
headerView是指？
你可以尝试设置下viewFrame属性

**Comment by EMNEIL** [comment]
WMPageController *wmvc = [[WMPageController alloc]initWithViewControllerClasses:vcArray andTheirTitles:insuranceCategory];

能告诉我wmvc.view  和wmvc.scrollView 之间联系吗？

**Comment by wangmchn** [comment]
wmvc.scrollview是wmvc.view的Subview

**Comment by EMNEIL** [comment]
你好,viewframe的属性能不能等同于我上面wmvc.view的frame。我现在是更新到最新的版本，然后发现
[wmvc.view mas_makeConstraints:^(MASConstraintMaker *make) {

    make.top.mas_equalTo(100);
    make.right.left.mas_equalTo(0);
    make.height.mas_equalTo(HEIGHT);
}];
这样写约束不可以了，以前版本是可行的。调试发现如果像上面那样写，wmvc.scrollView会覆盖wmvc.view

**Comment by wangmchn** [comment]
建议还是设置viewFrame，你可以 **尝试** `override viewFrame`，让他永远返回`wmvc.view.bounds`

**Comment by wangmchn** [comment]
这个issue先关闭了，如有疑问再打开讨论
