### ISSUE TITLE
底部会出现44的空白

### ISSUE THREAD

**Issue by mike-shi** [wangmchn/WMPageController#159]
[self addChildViewController:pageVC]
 
    [self.view addSubview:pageVC.view]

通过这种方式，把WMPageController作为子控制器放到ViewController上时，底部会出现44的空白。

**Comment by GuessEver** [comment]
@mike-shi 
试试设置extendedLayoutIncludesOpaqueBars？
```
[self setExtendedLayoutIncludesOpaqueBars:YES];
```

**Comment by mike-shi** [comment]
还是不行。
WMPageController控制的 controller 还是有44的空白

**Comment by mike-shi** [comment]
![2016-08-12 8 41 44](https://cloud.githubusercontent.com/assets/17229214/17613003/fa09b578-608a-11e6-938e-728c2b447b56.png)

运行的效果是这样的

**Comment by mike-shi** [comment]
已解决
