### ISSUE TITLE
能不能给个开关，去掉点击menuViewItem的颜色渐变效果。因为发现，快速重复点击俩个相邻的item，颜色变化出错，有可能颜色变成奇怪的颜色。

### ISSUE THREAD

**Issue by githubzxq** [wangmchn/WMPageController#161]
能不能给个开关，去掉点击menuViewItem的颜色渐变效果。因为发现，快速重复点击俩个相邻的item，颜色变化出错，有可能颜色变成五颜六色的颜色。最新版本很容易产生这个bug，老版本1.6.7左右不会有。

**Comment by wangmchn** [comment]
因为之前有人提，点击的时候没有渐变，加了个CADisplayLink来控制颜色动画，估计是实现上没考虑全面，有bug存在，我再梳理一下

**Comment by wangmchn** [comment]
@githubzxq 做了修复，试试新的代码
