### ISSUE TITLE
ViewFramDemo问题

### ISSUE THREAD

**Issue by JMZone** [wangmchn/WMPageController#162]
ViewFramDemo中,如果我想在头部自定义一个view,请问应该怎么添加进去呢??
[self.view addSubview:myView];这个方法是添加在最上面的.下面tab滚上去的时候就被myView盖住了...大神帮忙解决一下..谢谢

**Comment by wangmchn** [comment]
试试这个：
[self.view insertSubview:myView atIndex:0];

**Comment by JMZone** [comment]
上述问题解决了..谢谢大神..另外还有一个问题, 我想用三个独立的ViewController,怎么添加进去哇??另外我发现..demo里面的三个ViewController是同时滚动而不是独立滚动???麻烦你了

**Comment by wangmchn** [comment]
这个viewFrameDemo比较简略，目的只是为了告诉通过设置viewFrame可以方便的改变视图大小，具体怎么个实现还是需要自身找方法解决的

**Comment by JMZone** [comment]
好的 万分感谢
