### ISSUE TITLE
在viewDidLoad之前设定好selectIndex不能保证滑动到menuView中央

### ISSUE THREAD

**Issue by xilin** [wangmchn/WMPageController#165]
比如demo中把menu数量改成9，在push之前就设定好selectIndex，这时push进来的视图里选中的offset在左边而不是中央。
看了代码，在`viewDidLoad`中直接调用`wm_addMenuView`，而此时还没有执行过`viewDidLayoutSubviews`，还未执行`wm_calculateSize`拿到`_viewWidth`，这样menuView内部的scrollView的宽度在初始时是0，导致offset计算错误。

**Comment by wangmchn** [comment]
好的，我晚点看看这个问题👌

**Comment by xilin** [comment]
赞速度！

**Comment by wangmchn** [comment]
你都帮忙找到bug的原因了哈~
