### ISSUE TITLE
切换页面菜单偏移的问题

### ISSUE THREAD

**Issue by IAMJ** [wangmchn/WMPageController#166]
A 页面继承了 WMPageController， 并且设置` self.showOnNavigationBar = YES;`
A 页面有个按钮，点击去到 B 页面，B 页面有设置 `[self.navigationController setNavigationBarHidden:YES animated:YES];`
当返回 A 时，A 的 WMMenuView 里面的 scrollView 会向左偏移。

重复上面的步骤，本来居中的菜单就越来越往左偏。
![94cb6332-488f-474a-a827-11353af67582](https://cloud.githubusercontent.com/assets/2928760/18085687/c6fd55ba-6ede-11e6-9a93-13f41dd9dc45.png)

我现在是在 A 里通过下面代码修正
```
- (void)viewDidAppear:(BOOL)animated {
    [super viewDidAppear:animated];
    
    CGRect frame = self.menuView.scrollView.frame;
    frame.origin.x = (self.menuView.width - self.menuView.scrollView.width) / 2;
    self.menuView.scrollView.frame = frame;
}
```

**Comment by wangmchn** [comment]
@IAMJ 请问使用的是最新的代码吗？刚试了下没有重现这个问题，我的操作步骤：
```objc
// In controller B
- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view.
    [self.navigationController setNavigationBarHidden:YES animated:YES];
}


- (void)touchesEnded:(NSSet<UITouch *> *)touches withEvent:(UIEvent *)event {
    [super touchesEnded:touches withEvent:event];
    
    [self.navigationController popViewControllerAnimated:YES];
    [self.navigationController setNavigationBarHidden:NO animated:YES];
 
}
```
是否有其他遗漏点？

**Comment by IAMJ** [comment]
刚新建了一个新工程重现了，还有一个条件就是 A 页面设置了 rightBarButtonItem，我试过如果不设置的话就不会发生左偏移

`
- (void)viewDidLoad {
    [super viewDidLoad];

    self.title = @"A";
    
    UIView *rightView = [[UIView alloc] initWithFrame:CGRectMake(0, 0, 44, 44)];
    UIBarButtonItem *item = [[UIBarButtonItem alloc] initWithCustomView:rightView];
    self.navigationItem.rightBarButtonItem = item;
}
`

**Comment by wangmchn** [comment]
@IAMJ 感谢反馈，做了一下修复，看看现在还存在这个问题不？pod上稍晚点更新

**Comment by IAMJ** [comment]
我是通过 pod 管理的，到时验证

**Comment by IAMJ** [comment]
刚更新到 1.9.1 ，验证已解决这个 bug
