### ISSUE TITLE
WMPageController支持动态添加子控制器以及标题吗？

### ISSUE THREAD

**Issue by suming1910** [wangmchn/WMPageController#167]
非常感谢@wangmchn提供的代码，我的项目需求是子控制器数量是根据后台返回的数组元素个数来决定的，标题亦然，当前我的解决办法是执行push进入WMPageController之前在上一个控制器发送网络请求，然后根据返回数据创建，不过还是希望可以实现先push进入   然后根据服务器返回数据来刷新控制器，不知道这个当前的版本是否支持呢？

顺带问一下，如何关闭滑动切换子控制器的手势，设置只能通过点击标题切换~~~

**Comment by suming1910** [comment]
g刚才翻了下前人的问题，大致知道怎么动态设置了，不过遇到一个问题就是，
    self.menuHeight = 40; //导航栏高度
    self.menuItemWidth = VIEW_WIDTH/2; //每个 MenuItem 的宽度
    self.menuBGColor = [UIColor whiteColor];
    self.menuViewStyle = WMMenuViewStyleLine;//这里设置菜单view的样式
    self.progressHeight = 2;//下划线的高度，需要WMMenuViewStyleLine样式
    self.progressColor = Blue_navigationColor;//设置下划线(或者边框)颜色
这类的设置要写在哪里，我写在ViewDidLoad里[super viewDidLoad];后面没奏效

**Comment by wangmchn** [comment]
@suming1910 
这些需要设置在init方法里

**Comment by suming1910** [comment]
@wangmchn 好的，谢谢啦

**Comment by suming1910** [comment]
@wangmchn 顺带问一下，如何关闭滑动切换子控制器的手势，设置只能通过点击标题切换~~~

**Comment by wangmchn** [comment]
关于关闭滑动手势的问题，你可以在viewDidLoad之后调用：
```objc
self.scrollView.scrollEnabled = NO;
```

**Comment by wangmchn** [comment]
先关闭了，若有问题请再打开该 issue
