### ISSUE TITLE
The crash by progressViewWidths property

### ISSUE THREAD

**Issue by swh82504056** [wangmchn/WMPageController#170]
self.pageController.titles = [[NSArray alloc] initWithArray:itemsTitleArray];
self.pageController.viewControllerClasses = [[NSArray alloc] initWithArray:itemsClassArray];
self.pageController.itemsWidths = [[NSArray alloc] initWithArray:itemsWidthArray];
self.pageController.progressViewWidths = [[NSArray alloc] initWithArray:itemsProgressWidthArray];
[self.pageController reloadData];

By above code, the first time, no problem.
the second time, if you change nothing, no problem.
but you change all items, it can be crash.

I have solved it by the following code, but not the basic reason.

self.pageController.titles = [[NSArray alloc] initWithArray:itemsTitleArray];
self.pageController.viewControllerClasses = [[NSArray alloc] initWithArray:itemsClassArray];
self.pageController.itemsWidths = [[NSArray alloc] initWithArray:itemsWidthArray];
self.pageController.progressViewWidths = @[];
[self.pageController reloadData];
self.pageController.progressViewWidths = [[NSArray alloc] initWithArray:itemsProgressWidthArray];

If you have time to solve it, please do it.  
Thank you.

**Comment by wangmchn** [comment]
Hey， @swh82504056 
Sorry for replying late, I have done some fixes. 
Try it and tell me whether it works! 😄
