### ISSUE TITLE
自定义NavigationController 不能实现 

### ISSUE THREAD

**Issue by keepJion** [wangmchn/WMPageController#171]
我自己自定义了一个继承UINavigationController的导航栏控制器,集成后不能显示任何的界面,你能解决一下吗?"

**Comment by Huang-Libo** [comment]
把UINavigationController 放到WMPageController中？

**Comment by wangmchn** [comment]
@keepJion 没太明白你的现实方式，能详细说明一下吗？

**Comment by keepJion** [comment]
@wangmchn  就是我重新创建一个继承UINavigationController的类，不用系统的UINavigatioinController

**Comment by wangmchn** [comment]
然后是怎么设置不现实呢？

**Comment by keepJion** [comment]
@wangmchn  调用init那个方法 只是UINavigationController 是我自己重新写的

**Comment by wangmchn** [comment]
……
根据你的信息我完全不知道怎么排查
希望提供一下信息：
1.怎么自定义的UINavigationController
2.怎么集成的WMPageController
3.怎么个不显示法

**Comment by wangmchn** [comment]
这个issue先关闭了，如有补充再开启
