### ISSUE TITLE
手势冲突问题？

### ISSUE THREAD

**Issue by QuintGao** [wangmchn/WMPageController#172]
我其中一个子控制器加上了左右滑动的手势，但不起作用

**Comment by wangmchn** [comment]
是可能会冲突的，因为本身子控制器view的父视图就有左右的手势，你可能需要通过UIGestureRecognizerDelegate的几个方法来判断手势的识别

**Comment by wangmchn** [comment]
这个问题先关闭了，如有疑问再打开
