### ISSUE TITLE
底部有白条

### ISSUE THREAD

**Issue by Ailix** [wangmchn/WMPageController#173]
带UITabBarController的情况下 滑动隐藏TabBar时底部有白条，，，

**Comment by wangmchn** [comment]
@Ailix 滑动隐藏是指？

**Comment by Ailix** [comment]
上滑TableView 隐藏底部TabBar 类似映客的效果

**Comment by wangmchn** [comment]
这个可能需要在滑动的时候设置下WMPageController的viewFrame属性，这个属性是可动画的，目前不会自动调整。

**Comment by Ailix** [comment]
好 我试试

**Comment by wangmchn** [comment]
该issue没有后续，先关闭了
