### ISSUE TITLE
想要实现点击按钮，滑动切换页面

### ISSUE THREAD

**Issue by AnnaMa1992** [wangmchn/WMPageController#175]
想要实现点击按钮，滑动切换页面，这个怎么做，在哪里可以实现这种效果

**Comment by wangmchn** [comment]
现在的滑动效果没法从0直接到3，在0页面点击3号item，会经历0->1->2->3的动画过程。
如要开启，设置pageAnimatable = yes

**Comment by AnnaMa1992** [comment]
嘿嘿，你写的定义里面都有，没注意到，谢谢你。

**Comment by wangmchn** [comment]
不客气~
