### ISSUE TITLE
奔溃问题

### ISSUE THREAD

**Issue by liuduanwen** [wangmchn/WMPageController#176]
item来回快速点击会奔溃，
WMProgressView.m
if (_link) {
        [_link invalidate];
        [_link removeFromRunLoop:[NSRunLoop mainRunLoop] forMode:NSRunLoopCommonModes];
    }

**Comment by wangmchn** [comment]
试了下没出现这种情况？最新代码？设备信息？

**Comment by wangmchn** [comment]
问题没后续，缺少信息先关闭了
