### ISSUE TITLE
iOS 10 兼容问题

### ISSUE THREAD

**Issue by yezhanxiang** [wangmchn/WMPageController#179]
点击内容页后再点返回，然后滑动分类发现切换不了控制器了

**Comment by yezhanxiang** [comment]
- (void)setEdgesForExtendedLayout:(UIRectEdge)edgesForExtendedLayout {
    [super setEdgesForExtendedLayout:edgesForExtendedLayout];
    if (_hasInited) {
        _hasInited = NO;
        [self viewDidLayoutSubviews];
    }
}


iOS 10 当条状到详情的控制器再返回时候会进入次方法，导致滚动时候不往下执行
- (void)scrollViewDidScroll:(UIScrollView *)scrollView {
    if (_shouldNotScroll || !_hasInited) { return; }
}

我注释了setEdgesForExtendedLayout的方法，就不会出现此问题，但我觉得这样可能会存在问题，希望作者修复下，谢谢

**Comment by wangmchn** [comment]
@yezhanxiang 
感谢反馈，网速较慢，等我更新完了xcode看看

**Comment by wangmchn** [comment]
@yezhanxiang 是否有设置`edgesForExtendedLayout`属性？
试试看这样改是否能够解决问题：
```obj-c
- (void)setEdgesForExtendedLayout:(UIRectEdge)edgesForExtendedLayout {
    if (self.edgesForExtendedLayout == edgesForExtendedLayout) { return; }
    
    [super setEdgesForExtendedLayout:edgesForExtendedLayout];
    
    if (_hasInited) {
        _hasInited = NO;
        [self viewDidLayoutSubviews];
    }
}
```

**Comment by yezhanxiang** [comment]
问题解决了，谢谢
