### ISSUE TITLE
如何禁止滑动

### ISSUE THREAD

**Issue by green-beans** [wangmchn/WMPageController#183]
请问如何禁止页面之间的可滑动，只要menu的点击动作出发切换控制器？

**Comment by wangmchn** [comment]
@green-beans 
可以在viewDidLoad设置scrollView.scrollEnable = NO；
也可以在任何时刻设置WMPageController的scrollEnable = NO。
回复晚了抱歉

**Comment by green-beans** [comment]
谢谢，框架很好用，希望以后可以出可以自定义图片的menu按钮
