### ISSUE TITLE
怎么把menuview 向下偏移20像素。 想把状态栏留出来

### ISSUE THREAD

**Issue by iphone5s** [wangmchn/WMPageController#184]

**Comment by iphone5s** [comment]
self.menuView.frame = CGRectMake(menuX, 20, menuWidth, menuHeight - 20);
我修改了 这个地方 不知道会不会引起其他地方的问题。 希望支持下menuview 向下偏移的问题

**Comment by wangmchn** [comment]
设置viewFrame属性即可

**Comment by iphone5s** [comment]
设置了 viewframe 直接白屏了  显示不正常呀  能给我留个qq 吗，我还有一个问题要反应下

**Comment by wangmchn** [comment]
@iphone5s 623421832

**Comment by wangmchn** [comment]
问题无后续，先关闭了
