### ISSUE TITLE
怎么通过代码设置WMPageController的selectIndex

### ISSUE THREAD

**Issue by jerry-sl** [wangmchn/WMPageController#19]
我现在遇到的问题是：WMPageController现在在某个Index 比如0. 切换到app的其他地方做了一些操作后，需要跳转到WMPageController的页面的0 index. 我通过设置self.pageView.selectIndex = 0;后调到了对应的index  但是页面是空白的页面。  网络请求的数据是正确的。

有没有人遇到类似的情况？

**Comment by wangmchn** [comment]
hey,@jerry-sl
请问`self.pageView.selectIndex = 0`是在哪里实现的？
不太清楚这个流程，没法复现。

**Comment by xinqidian** [comment]
加入页面不是固定的，进入这个页面，怎么传递一个数据过来，用来确定页面类容

**Comment by xinqidian** [comment]
假如页面不是固定的，进入这个页面，怎么传递一个数据过来，用来确定页面类容

**Comment by wangmchn** [comment]
hey,@xinqidian
`WMPageController` 有两个属性，一个叫 `values`，一个叫 `keys`.
可通过设置这两个属性来传递数据，比如，你第一个子控制器有属性 `name`，第二个有属性 `age`，那么你可以通过一下方式传递`name`和`age`的值：
在初始化的时候，设置
`pageController.values = @[@"xinqidian",@22]`
`pageController.keys = @[@"name",@"age"]`
并注意一下几点：
1.`keys`的值必须和控制器属性名字相同
2.`keys`和`values`个数需与控制器个数相同，顺序一一对应，若中间有控制器不需要传值，请设置空的属性来接受

by the way，下次另起一个issue比较好

**Comment by jerry-sl** [comment]
@wangmchn 问题我大概找到了   我在UITabBarController中一个tab上用了WMPageController. 切换到其他tabbar做了一些业务操作后  按照需求需要跳转回WMPageController  这个时候WMPageController的index没有改变。  - (void)menuView:(WMMenuView *)menu didSelesctedIndex:(NSInteger)index currentIndex:(NSInteger)currentIndex {
中的gap为0.  但是后续的判断是gap > 1  然后把原来的controller删除了。数据没有地方显示。

**Comment by wangmchn** [comment]
确实是一个Bug，感谢提出~

**Comment by wangmchn** [comment]
@jerry-sl 
尝试修复了下 不知道这样还有错不？
