### ISSUE TITLE
不回调menuViewController: atIndex:

### ISSUE THREAD

**Issue by githubzxq** [wangmchn/WMPageController#190]
设置viewFrame后，要不要reloadData。

**Comment by githubzxq** [comment]
为什么设置viewFrame的时候会设置_hasInited = NO即wmpageController没有初始化。

**Comment by wangmchn** [comment]
设置viewFrame不需要reloadData的，和  https://github.com/wangmchn/WMPageController/issues/191 重复，问题合并
