### ISSUE TITLE
不回调menuViewController: atIndex:

### ISSUE THREAD

**Issue by githubzxq** [wangmchn/WMPageController#191]
为什么我会遇到self.view.window == nil的情况。
- (void)viewDidLayoutSubviews {
    [super viewDidLayoutSubviews];
    
    if (!self.childControllersCount) return;
    
    CGFloat oldSuperviewHeight = _superviewHeight;
    _superviewHeight = self.view.frame.size.height;

    if ((_hasInited && _superviewHeight == oldSuperviewHeight) || !self.view.window) return;

    // 计算宽高及子控制器的视图frame
    [self calculateSize];
    
    [self adjustScrollViewFrame];
    
    [self adjustMenuViewFrame];
    
    [self adjustDisplayingViewControllersFrame];
    
    [self removeSuperfluousViewControllersIfNeeded];

    _hasInited = YES;
    [self.view layoutIfNeeded];
}

**Comment by githubzxq** [comment]
我在viewWillAppear的时候调的reloadData，所以此时self.view.window为空，那么_hasInited就不执行yes，问题找到了。

**Comment by wangmchn** [comment]
理论上虽然你在viewWillAppear的时候调的reloadData的时候，_hasInited不执行，但是在之后系统会自动调用这个方法的

**Comment by githubzxq** [comment]
我之前用wmpageController用错了，因为项目的需要，我在viewWillAppear的时候，进行了一些reloadData操作，但是看了下你的源码，此时viewDidLayoutSubviews里面明确指出if(!self.view.window) return，所以我的reloadData操作没有使_hasInited = yes不执行。我把代码放在viewDidAppear就好了。在willWillApear的时候self.view.window为空是controller的共性。

**Comment by wangmchn** [comment]
嗯，是的，有问题继续交流~close了哈

**Comment by githubzxq** [comment]
好。
