### ISSUE TITLE
有个疑问，请教下。。

### ISSUE THREAD

**Issue by dadadong** [wangmchn/WMPageController#193]
- (void)viewDidLayoutSubviews ；
  这个方法中 ，下面的判断，为什么要加上  !self.view.window 呢？ 这样造成了我在push出来的一个页面中 - reloadDate 原页面，在这个方法中被return了。
  if ((_hasInited && _superviewHeight == oldSuperviewHeight) || !self.view.window) return;

**Comment by wangmchn** [comment]
@dadadong 主要在计算size的时候涉及到了window尺寸的获取
这个方法应该是会在你pop回来的时候被系统调用的

**Comment by dadadong** [comment]
是这样的，在我们的业务场景中出现了一个bug,  下面我简要叙述下： 我们是实现类似网页的栏位编辑功能，需要在push出来的一个controllerB中编辑, 编辑后pop，需要可以回到 一个指定的 childCtl

1. 我是在WMPageCtl中选中一个栏位  即 currentViewController == ctlA, selectIndex == 1;
2. push到ctlB， 添加一个栏位，同时使用boock回调ctlA的- reloadDate(会因 !self.view.window被return), 但是 _hasInited 会被置为NO.
3. 在ctl选中一个栏位, 同时使用boock回调ctlA的 setSelectIndex：2，但是在 - (void)menuView:(WMMenuView *)menu didSelesctedIndex:(NSInteger)index currentIndex:(NSInteger)currentIndex；中，因为_hasInited == NO ,被return, 导致了currentViewController 未被更新，但是_selectIndex 却被更新成了2， 
4. 接下来pop结束，ctlA的- viewDidAppear被调用， 接下来会调用  
    [self didEnterController:self.currentViewController atIndex:self.selectIndex];
但是，其中的currentViewController 和 selectIndex已经不同步了，因为selectIndex被修改了，而currentViewController未被系修改成功。


所以，我是否可以把第一个问题中的 window判断去掉呢？

**Comment by wangmchn** [comment]
确实是一个bug，你可以先把window的逻辑去掉，如果出现视图大小不对，可能需要设置一下viewFrame属性，比如：下面有TabBar，但是视图部分被TabBar盖住

**Comment by wangmchn** [comment]
可能后续要再找一个更正确的计算相对frame的方法
