### ISSUE TITLE
亲爱的作者，你好，关于角标的问题

### ISSUE THREAD

**Issue by WangYiOS** [wangmchn/WMPageController#198]
你好，大神
WMMenuView里的方法
- (UIView *)menuView:(WMMenuView *)menu badgeViewAtIndex:(NSInteger)index;
是用来创造 角标的。
您的Demo里有这个角标创建的示例吗？
我想学习一下
可以发给我一份让我学习下马？
361002633@qq.ocm，求教育

**Comment by WangYiOS** [comment]
2016年11月02日21:20:48，来看看作者回复我的消息没有

**Comment by wangmchn** [comment]
@WangYiOS 回复晚了抱歉，最近比较忙
可以看下 PassValue 那个 Demo，有个比较简单的例子，有什么疑问继续交流
这个方法老版本可能有bug，建议用最新版本哈

**Comment by WangYiOS** [comment]
好的，万分感谢作者
