### ISSUE TITLE
请问如何在title旁边添加一个UIImageView？

### ISSUE THREAD

**Issue by xiongxiongjiang** [wangmchn/WMPageController#199]
如题，求指导

**Comment by wangmchn** [comment]
可以参照这个issue，用角标来实现：https://github.com/wangmchn/WMPageController/issues/198

**Comment by xiongxiongjiang** [comment]
![wechatimg50](https://cloud.githubusercontent.com/assets/16330990/19959404/7e0bdf8a-a1e1-11e6-9b1a-7b1c516dca8e.jpeg)
完美解决了，谢谢指导

**Comment by xiongxiongjiang** [comment]
不过还有点小问题，对于下划线，只是文字居中了，没有连着图标一起居中啊，请问可以解决吗

**Comment by wangmchn** [comment]
这个不好解决了，可能需要在标题文字前假写空格来模拟居中了

发自我的 iPhone

**Comment by xiongxiongjiang** [comment]
我也觉得，，就是暴力了点哈哈。再次感谢啦

**Comment by 542604974** [comment]
你好，可以看看你代码怎么写的吗，我也要实现这个功能，但是左侧会多了几个图标
//自定义
- (UIView *)menuView:(WMMenuView *)menu badgeViewAtIndex:(NSInteger)index {
    switch (index) {
        case 1: case 2: case 3: case 4: case 5:{
            UIImageView * imageView = [menu addImageViewWithFrame:CGRectZero image:@"SingUp_CountryText_Country"];
            imageView.frame = CGRectMake(5, 17, 15, 15);
            return imageView;
        }
            break;
            
        default:
            return nil;
            break;
    }
}

**Comment by 542604974** [comment]
你好，我实现了，谢谢
