### ISSUE TITLE
提个问题

### ISSUE THREAD

**Issue by bluesea** [wangmchn/WMPageController#2]
每次都会把之前的ViewController给destroy掉，然后再次查看，重新进入viewdidload。都是些本地数据的话，不影响，但如果是通过网络获取数据或者是之前的viewcontroller内有输入框（处于编辑状态），这样的情况，重新加载整个视图，我觉得不是很合理~

**Comment by wangmchn** [comment]
之前的想法是 对于这一系列数据进行本地保存。在viewDidload里面判断是从网络下载还是本地加载。
如果不释放控制器的话，我怕控制器一多引起内存问题。现在还没有良好的解决想法，如果有的话还希望告知改善。

**Comment by bluesea** [comment]
http://tech.glowing.com/cn/practice-in-uiscrollview/看看这个呢，希望能有用~~

**Comment by wangmchn** [comment]
已有缓存了~回复晚了抱歉
