### ISSUE TITLE
去掉self.view.window判断，有问题吗？因为我想在viewWillAppear里做一些事。

### ISSUE THREAD

**Issue by githubzxq** [wangmchn/WMPageController#200]
if (!self.childControllersCount) return;
    
    CGFloat oldSuperviewHeight = _superviewHeight;
    _superviewHeight = self.view.frame.size.height;

    if ((_hasInited && _superviewHeight == oldSuperviewHeight) || !self.view.window) return;

**Comment by wangmchn** [comment]
只要设置了viewFrame属性就不会有问题，这个判断主要是window不在的计算会有误，这块代码我再优化下
