### ISSUE TITLE
selectIndex 方法使用的问题

### ISSUE THREAD

**Issue by qyfeng009** [wangmchn/WMPageController#201]
你好，在使用 selectIndex 这个方法是，调到指定的页面后，不显示当前页面的数据，需要滑动一下，才会出现数据。在这个页面上面好像有一个ScrollerView。这个问题怎处理？

**Comment by wangmchn** [comment]
@qyfeng009 你的数据是怎么加载的呢？

**Comment by wangmchn** [comment]
试试最新版本 2.02

发自我的 iPhone

**Comment by qyfeng009** [comment]
我是在viewWillAppear加载数据的，版本不是最新的而是1.9.4, 更新pod后却搜不到2.0.2版本.
不过我下载了最新的测试了一下，如果selectIndex写在viewDidLoad中就会出现我说的情况，如果写在init里就没有问题，但是我从上个页面传来的值好像在init中获取不到

**Comment by wangmchn** [comment]
@qyfeng009 重现了这个bug，感谢反馈 我看一下

**Comment by wangmchn** [comment]
@qyfeng009 已经修复了，试下 2.1.0 版本

**Comment by wangmchn** [comment]
如果找不到，先运行下 pod setup
