### ISSUE TITLE
在第一个继续左滑或者最后一个继续右滑会出现上下卡顿

### ISSUE THREAD

**Issue by Miyaer** [wangmchn/WMPageController#203]
有时候快速的向左滑动到第一个  可能左滑的次数太多了  就会出现上下卡顿的问题 或者是一直右滑到最后一个也会  这种情况应该怎么解决呢。。？？？

**Comment by wangmchn** [comment]
@Miyaer 
1.如果不是最新版本的，尝试更新到最新版本试试
2.我暂时没有重现出这个问题，有没有更详细的信息提供？或者提供下能够复现的demo？

**Comment by wangmchn** [comment]
@Miyaer 
1.如果不是最新版本的，尝试更新到最新版本试试
2.我暂时没有重现出这个问题，有没有更详细的信息提供？或者提供下能够复现的demo？

**Comment by wangmchn** [comment]
@Miyaer 
1.如果不是最新版本的，尝试更新到最新版本试试
2.我暂时没有重现出这个问题，有没有更详细的信息提供？或者提供下能够复现的demo？

**Comment by Miyaer** [comment]
好的 我更新一下  接手的别人的代码  发现不是pod装的 我删掉下一个最新的试试  最新的没有WMFoodView这个类了吗？

**Comment by wangmchn** [comment]
@Miyaer 是的，收拢在 WMProgressView 里面了
