### ISSUE TITLE
reload之后title的颜色会复位。

### ISSUE THREAD

**Issue by jsaddnf** [wangmchn/WMPageController#205]
在更新完标题之后，reload过后，标题titleColorNormal会变成黑色。

**Comment by jsaddnf** [comment]
包括title的字体大小也会复位

**Comment by jsaddnf** [comment]
滑动切换页面之后恢复正常。这个问题在demo里面同样存在

**Comment by wangmchn** [comment]
@jsaddnf 好的，这个问题我周末看下，感谢反馈

**Comment by wangmchn** [comment]
@jsaddnf 这个bug已修复，pod的上稍后上传
