### ISSUE TITLE
能否增加设置 ProgressView 的指示器为自定义图片的功能？

### ISSUE THREAD

**Issue by IAMJ** [wangmchn/WMPageController#206]
如图的效果
![01](https://cloud.githubusercontent.com/assets/2928760/20556791/a5b3dd2c-b1a3-11e6-80ef-f3e926b1440a.png)

**Comment by wangmchn** [comment]
@IAMJ 我周末看下增加这个功能

**Comment by wangmchn** [comment]
@IAMJ 试下设置能否达到效果？
```
pageController.progressColor = [[UIColor alloc] initWithPatternImage:xxxImage];
```

**Comment by IAMJ** [comment]
@wangmchn UIColor 原来还有这样的方法，问题解决了，谢谢

**Comment by wangmchn** [comment]
@IAMJ 我也是无意间发现的，解决就好 😄

**Comment by 542604974** [comment]
你好，请问pageController.progressColor = [[UIColor alloc] initWithPatternImage:xxxImage];是放在哪个方法，我放在- (UIViewController *)pageController:(WMPageController *)pageController viewControllerAtIndex:(NSInteger)index不行

**Comment by xiaobeifeng** [comment]
一张渐变色的图片该怎么设置呢？

**Comment by FoneG** [comment]
@wangmchn 渐变色的color，在progress滚动的时候颜色会变来变去
