### ISSUE TITLE
请问：怎么把menuview放到下方去？

### ISSUE THREAD

**Issue by Icemelt** [wangmchn/WMPageController#211]
如题，默认的menuview一直固定在上方，紧贴着NavigationBar。
现在有个需求是要把menuview设置到下方，紧贴着TabBar。
请问有方法能改么。

**Comment by wangmchn** [comment]
设置`viewFrame`属性，再在viewDidlayoutSubviews的最后设置menuView.frame.origin到合适的位置

试试这个方案能不能行

**Comment by Icemelt** [comment]
可行，感谢dalao

**Comment by wangmchn** [comment]
ok
