### ISSUE TITLE
新建pagevc之后添加了rightview  怎样去reload？

### ISSUE THREAD

**Issue by getol001** [wangmchn/WMPageController#212]
-(void)reloadData{
    UIButton *btn = [UIButton buttonWithType:UIButtonTypeCustom];
    [btn setImage:[UIImage imageNamed:@"添加"] forState:UIControlStateNormal];
    btn.frame = CGRectMake(0,0, 35, 35);
    
    self.menuView.rightView = btn;
    
    [btn bk_addEventHandler:^(id sender) {
        
        HeadChanelViewController * hcvc = [[HeadChanelViewController alloc]init];
        UINavigationController * nav = [[UINavigationController alloc]initWithRootViewController:hcvc];
        nav.modalTransitionStyle = UIModalTransitionStyleCrossDissolve;
        
        hcvc.chance = [PageVC sharedMySingletonClassb].chanelTitles;
        [self presentViewController:nav animated:YES completion:nil];
        
    } forControlEvents:UIControlEventTouchUpInside];
}
看到说明是rightview只能在reload里添加，那我在其他地方需要刷新界面的时候reload还需要添加哪些内容？

**Comment by wangmchn** [comment]
@getol001 没太明白你的意思，能否详细描述下？
rightView并不是只能在reload里添加的呀？

**Comment by getol001** [comment]
@wangmchn 
-(void)viewWillAppear:(BOOL)animated{
    
    UIButton *btn = [UIButton buttonWithType:UIButtonTypeCustom];
    [btn setImage:[UIImage imageNamed:@"添加"] forState:UIControlStateNormal];
    btn.frame = CGRectMake(0,0, 35, 35);
    
    self.menuView.rightView = btn;
    
    [btn bk_addEventHandler:^(id sender) {
        
        HeadChanelViewController * hcvc = [[HeadChanelViewController alloc]init];
        UINavigationController * nav = [[UINavigationController alloc]initWithRootViewController:hcvc];
        nav.modalTransitionStyle = UIModalTransitionStyleCrossDissolve;
        
        hcvc.chance = [PageVC sharedMySingletonClassb].chanelTitles;
        [self presentViewController:nav animated:YES completion:nil];
    } forControlEvents:UIControlEventTouchUpInside];
    
    [self reloadData];
    
}

这是我在滚动条控制器PageVC里面添加的右侧+号的代码  然后这个+号我会推出一个新的控制器界面，是用来处理增加和删除频道的  然后从这个频道处理界面返回之后我在PageVC的viewWillApper里面调用了reloadData，但是问题出现了，返回到界面之后子控制器全部没了。。。求教大佬该怎么去处理？

**Comment by wangmchn** [comment]
1.viewWillAppear 忘记调用 super 方法了
2.需要到WMPageController的reloadData方法里，定位下是什么问题导致的空白，因为不知道你的具体实现我也不方便定位
```
- (void)reloadData {
    [self wm_clearDatas]; // 这里会清除视图及数据
    
    if (!self.childControllersCount) { return; } // cout 是否为 0?
    
    [self wm_resetScrollView];
    [self.memCache removeAllObjects];
    [self wm_resetMenuView];
    [self viewDidLayoutSubviews]; // 这里面布局是否有问题?
}
```

**Comment by getol001** [comment]
@wangmchn 
首次进入的时候进过reloadData方法  但是所有显示都正常  但是在我用+号Present出频道处理控制器之后，然后再dissmiss回去，所有的子控制器就都没了

**Comment by wangmchn** [comment]
@getol001 版本号是？
能否提供下demo？

**Comment by getol001** [comment]
@wangmchn 
可以  发到哪个邮箱？

**Comment by wangmchn** [comment]
wangmchn@163.com

**Comment by wangmchn** [comment]
@getol001 看了下应该是之前的bug，下载最新版本试试？

**Comment by wangmchn** [comment]
最新版本已修复，先关了哈
