### ISSUE TITLE
怎样动态设置 showOnNavigationBar ？

### ISSUE THREAD

**Issue by IAMJ** [wangmchn/WMPageController#214]
需求是：页面显示之后发起请求，根据请求的结果去设置是否显示在 NavigationBar 上，比如后端返回 0 就设置在页面里，1 就设置在 NavigationBar 上。
现在在 viewDidLoad 里设置 showOnNavigationBar = YES 但无效

**Comment by wangmchn** [comment]
@IAMJ 设置showOnNavigationBar之后再调用 reloadData 试试？

**Comment by IAMJ** [comment]
@wangmchn 
不行，这样的话 
viewDidLoad 里有
```
[self addChildViewController:_pageController];
[_pageControllerContView addSubview:_pageController.view];
```

网络请求回来后设置
```
_pageController.showOnNavigationBar = YES;
[_pageController reloadData];
```

这样 menuView 还是在 _pageControllerContView 里，_pageControllerContView 是 self.view 里一个 view

**Comment by wangmchn** [comment]
```
[_pageController.menuView removeFromSupview];
_pageController.showOnNavigationBar = YES;
[_pageController reloadData];
```
这样试试？

**Comment by IAMJ** [comment]
@wangmchn 
😂 不行，这样 menuView 直接不见了。我换个思路去实现我这个需要吧。。自己定义一个 NavigationBar 
谢谢了，关闭吧。。

**Comment by wangmchn** [comment]
嗯嗯..😂
