### ISSUE TITLE
亲爱的作者，请点进来看下这里，帮帮忙解答我心中的疑惑

### ISSUE THREAD

**Issue by WangYiOS** [wangmchn/WMPageController#219]
社区用的是咱们的WM框架，程序启动，创建五个tarbar控制器（），如下图《代码》和《图》所示，社区是WM框架，但是当我点进《社区》的时候，我的个天，内存直接增加了60M，求解，这个地方难倒不是这么用的吗？《社区》的这个控制器就是继承自WM的。求作者指导

    HomeViewController *dvc = [[HomeViewController alloc] init];
    UINavigationController *nc1 = [[UINavigationController alloc] initWithRootViewController:dvc];
    nc1.navigationBar.hidden = YES;
    
    OrderingMealViewController *gvc = [[OrderingMealViewController alloc] init];
    UINavigationController *nc2 = [[UINavigationController alloc] initWithRootViewController:gvc];
    nc2.navigationBar.hidden = YES;
    
    //社区
    RBCommunityViewController *rbComVc = [self loadController];（loadController方法和Demo中您的实现方式一致）
    rbComVc.menuHeight = 44;
    rbComVc.menuViewStyle = WMMenuViewStyleLine;
    rbComVc.titleSizeSelected = 15;
    rbComVc.titleColorSelected = WYRGBColor(251, 49, 80);
    rbComVc.titleColorNormal = WYRGBColor(50, 51, 52);
    rbComVc.menuBGColor = WYRGBColor(245, 246, 248);
    rbComVc.showOnNavigationBar = YES;
    rbComVc.menuViewLayoutMode = WMMenuViewLayoutModeCenter;
    UINavigationController *rbComNavVC = [[UINavigationController alloc] initWithRootViewController:rbComVc];
    rbComNavVC.navigationBar.hidden = NO;
    
    StoreViewController *pvc = [[StoreViewController alloc] init];
    UINavigationController *nc3 = [[UINavigationController alloc] initWithRootViewController:pvc];
    nc3.navigationBar.hidden = YES;
    
    PersonalCenterViewController *plvc = [[PersonalCenterViewController alloc] init];
    UINavigationController *nc4 = [[UINavigationController alloc] initWithRootViewController:plvc];
    nc4.navigationBar.hidden = YES;
    
    self.viewControllers = @[nc1,nc2,rbComNavVC ,nc3,nc4];
![snip20161230_8](https://cloud.githubusercontent.com/assets/17872114/21560251/fb8c5cbe-ce96-11e6-9e5f-b16b26f14a4f.png)

**Comment by wangmchn** [comment]
是这么用的，没有错，试试社区tab先不用WMPageController，直接放最新这个控制器，看看内存增涨情况？

**Comment by Huang-Libo** [comment]
@wangmchn 
很有道理，可以用排除法试一遍
