### ISSUE TITLE
页面值传递的问题

### ISSUE THREAD

**Issue by xinqidian** [wangmchn/WMPageController#22]
人比较笨，没明白，你说pageController进行传递数据，可是这个没法改变WMViewControlle或者WMTableViewController或者WMCollectionViewController里面的 数据类型 假如这里面的数据是根据外面传入的数据进行改变的，这个应该怎么办？by the way，你的这个写的是我看到的类似控件，用起来最简单的一个控件，非常方便！！！

**Comment by xinqidian** [comment]
[WMViewController class]  就是这个 我想传递一个参数给WMViewController  可是  你用的是 class 获取的 我该怎么在这里传递一个数据给它

**Comment by wangmchn** [comment]
还是刚刚的那个方法，我会在子控制器，例如`WMViewController`或者`WMTableViewController`初始化的时候，把`pageController`里面`values`和`keys`的值通过`KVC`的方式，一一赋值给控制器。
还是刚刚那个例子，`name`是`WMViewController`的属性，`age`是`WMTableViewController`的属性
按照刚刚的做法，在`WMViewController`和`WMTableViewController`分别打印`self.name`和`self.age`就会是`@"xinqidian"` 和 `@22`.
刚刚的做法：#19

**Comment by wangmchn** [comment]
不知道是不是你要的？
还是说你是在pageController创建的时候就已经有了WMViewController和WMViewController对应的Model数据？然后想传值Model？

**Comment by xinqidian** [comment]
好像是对的，想传值Model， vcClass = [WMViewController class];   在这里想传一个值给WMViewController  好让它确定数据  而不是固定的数据

**Comment by xinqidian** [comment]
刚刚看到以前别人问的问题  已经有人问过了 我看看那个解决方法

**Comment by wangmchn** [comment]
那这个Model是怎么得来的呢？因为一般都会选择在各自的子控制器请求数据。
比如利用pageController展示的是每个月份的销量，那么一般都会给一个月份属性month，然后通过keys和values把月份传过去，在子控制器，比如WMViewController中，知道了现在是几月，然后通过这个月份发起网络请求或者从本地加载数据。
或者把`Model`还原成`NSDictionary`，放到values数组里面传递过去，然后到各自控制器那边解析dict。

**Comment by wangmchn** [comment]
之前的问题比较老了 现在版本加了`values`和`keys`主要就是为了解决这个情况

**Comment by xinqidian** [comment]
说到底还是不知道怎么从子控制器里面获得  values和keys    Demo里面貌似没有体现

**Comment by wangmchn** [comment]
看最新的提交，增加了KVC传值的例子，具体是` WMMenuViewFoold` 那个例子

**Comment by xinqidian** [comment]
好吧，你真好，我看看

**Comment by xinqidian** [comment]
瞬间明白了!!!很感谢!!!

**Comment by wangmchn** [comment]
：）
