### ISSUE TITLE
Hello,请问初始化的时候传入控制器数组和Title数组的问题

### ISSUE THREAD

**Issue by ws4715535** [wangmchn/WMPageController#220]
Hello,请问初始化的时候传入控制器数组和Title数组必须和在里面实现的代理方的个数一样吗?
如果我有一个需求是增加和删除某个page下的控制器,该怎么做?

**Comment by wangmchn** [comment]
如果用的代理方法不需要传入，用init方法就行

**Comment by ws4715535** [comment]
明白了,感谢你.
