### ISSUE TITLE
建议添加一种风格，就是矩形标签的

### ISSUE THREAD

**Issue by BelaW613** [wangmchn/WMPageController#222]
建议添加一种风格，就是矩形标签的，或者可以提供自定义的

**Comment by wangmchn** [comment]
可以试下用flood类型，然后设置下progressCornerRadius，来试试矩形

发自我的 iPhone

**Comment by BelaW613** [comment]
progressCornerRadius是哪个类里面的，没看到，能提供具体的吗？谢谢

**Comment by wangmchn** [comment]
progressViewCornerRadius，在WMPageController.h里面

发自我的 iPhone

**Comment by BelaW613** [comment]
好的，看到了，刚刚没有更新你最新的

**Comment by BelaW613** [comment]
现在更新你的最新的，运行直接崩溃到了

**Comment by BelaW613** [comment]
- (UIViewController * _Nonnull)initializeViewControllerAtIndex:(NSInteger)index {
    if ([self.dataSource respondsToSelector:@selector(pageController:viewControllerAtIndex:)]) {
        return [self.dataSource pageController:self viewControllerAtIndex:index];
    }
    return [[self.viewControllerClasses[index] alloc] init];
}里面，是怎么回事，之前都没问题

**Comment by wangmchn** [comment]
是什么崩溃信息？

发自我的 iPhone
