### ISSUE TITLE
ViewFrameDemo 如何在加footView 

### ISSUE THREAD

**Issue by guang-sun** [wangmchn/WMPageController#223]
<img width="399" alt="default" src="https://cloud.githubusercontent.com/assets/16836583/22732205/4899146a-ee28-11e6-88cf-ac3bbbc36e4b.png">
<img width="430" alt="default" src="https://cloud.githubusercontent.com/assets/16836583/22732231/5ca77cc6-ee28-11e6-96f3-7fd1b1200bf7.png">
底部的footview 根据需要是否加上

**Comment by wangmchn** [comment]
没有太明白你的需求？是指如何在简介、笔记这些控制器上添加FooterView吗？

**Comment by guang-sun** [comment]
我的意思是 在简介时  底部没有footview    在笔记时 有footview 固定在底部   我现在是通过实时修改viewFrame 这个属性  但是 这样有些麻烦   是不是可以在加个属性设置  footView 呢

**Comment by wangmchn** [comment]
意思是 footview 想要永驻在页面底部？直接在WMPageController的子类通过 [self.View addSubview:footView] 就可以做到
