### ISSUE TITLE
关于子页面上下滑动会刷新上个页面数据的bug

### ISSUE THREAD

**Issue by Rain-dew** [wangmchn/WMPageController#224]
#bug
在page中添加几个控制器，如果其中一个控制器写了明杰的上拉刷新，并且存在刷新列表的网络请求。这时候点击一个列表弹出详情，我这边是详情中也有个列表，这时候上下滑动的时候奇葩出现了，我打印台在打印刷新上个页面的列表数据。也就是说当加入了上拉刷新下拉刷新后，push的子页面上下滑动会刷新上个页面的数据。期待改进下。虽然这个bug并不影响功能，但是我觉得这个对内存和流量都是一个不小的考验。

**Comment by Huang-Libo** [comment]
你说的列表是 tableview 吗, 我感觉你说的 这个bug 是一个具体业务 bug,  和 WMPageController 关系不大.

**Comment by Rain-dew** [comment]
好的。我去查查
