### ISSUE TITLE
在计算子controller的view frame时出现错误

### ISSUE THREAD

**Issue by Jerry-Zed** [wangmchn/WMPageController#225]
我设置了showOnNavigationBar = YES; menuView显示正常，但是在wm_calculateSize方法中计算子页面的frame时出了问题，其中这样取导航栏高度CGFloat navigationHeight = CGRectGetMaxY(self.navigationController.navigationBar.frame)拿到的是44，并没有计算状态栏的高度（20），所以后面的子页面全部都向上偏了20，被导航栏遮挡了。。

**Comment by Huang-Libo** [comment]
我在侧滑返回时 menuView 直接消失了, 不知道是怎么回事.

**Comment by Huang-Libo** [comment]
我发现了问题所在:

我之前添加 view 的方式是之前通过赋值添加 subview(通过masonry做的约束), 
```
self.view = self.mySubview;
```
这样写会出现"侧滑返回时 menuView 直接消失"的问题, 可能是 WMPageController 在侧滑时无法获取menuView 的大小?

可以正常工作的代码是这样的
```
    [self.view addSubview:self.mySubview];
    [self.mySubview mas_makeConstraints:^(MASConstraintMaker *make) {
        make.edges.equalTo(self.view);
    }];
```

**Comment by wangmchn** [comment]
@Jerry-Zed 感谢反馈，我稍后看下这个问题。
@Huang-Libo 
self.view = self.mySubview;  虽然还不太清楚原因，最好还是不要更改WMPageController.view哈

**Comment by Jerry-Zed** [comment]
@wangmchn 我好像发现问题了，WMPageController所在的nav我是模态出来的，貌似模态出来的navigationbar取值就是44，又发现了一个苹果坑。。将其改为CGFloat navigationHeight = self.presentingViewController ? CGRectGetMaxY(self.navigationController.navigationBar.frame)+20 : CGRectGetMaxY(self.navigationController.navigationBar.frame);这样就正常了。

**Comment by wangmchn** [comment]
哇 好的 非常感谢🙏

发自我的 iPhone

**Comment by Huang-Libo** [comment]
@wangmchn  我改的不是 WMPageController.view , 而是子控制器的 view

**Comment by wangmchn** [comment]
@Huang-Libo 这个就比较诡异了，得查一下才能知道原因。menuview应该和子控制器无关才对..

**Comment by Huang-Libo** [comment]
@wangmchn menuView 是不是会在子控制器少于 2 个的时候自动隐藏?

**Comment by wangmchn** [comment]
@Huang-Libo 不会自动隐藏，暂时不清楚原因

**Comment by wangmchn** [comment]
@Jerry-Zed 很奇怪，刚测试发现并没有present出来还是64？没有这个问题，能否告知下机型及系统？

**Comment by AntHuiZi** [comment]
我是继承于WMPageController，push出的页面，也是出现menuView距离顶部的距离为44，环境为：Version 8.2.1 (8C1002);xcode设置deployment target最低版本为8.0；测试机版本为：10.2.1（14d27）

**Comment by AntHuiZi** [comment]
@wangmchn 我是继承于WMPageController，push出的页面，也是出现menuView距离顶部的距离为44，环境为：Xcode Version 8.2.1 (8C1002);xcode设置deployment target最低版本为8.0；测试机版本为：10.2.1（14d27）

**Comment by AntHuiZi** [comment]
@wangmchn 我是继承于WMPageController，push出的页面，navigationBar的frame是{{0, 0}, {375, 44}}，navigationBar的起始位置变成（0，0）了，也是出现menuView距离顶部的距离为44，环境为：Xcode Version 8.2.1 (8C1002);xcode设置deployment target最低版本为8.0；测试机版本为：10.2.1（14d27）

**Comment by wangmchn** [comment]
```

/**
 Implement this datasource method, in order to customize your own contentView's frame

 @param pageController The container controller
 @param contentView The contentView, each is the superview of the child controllers
 @return The frame of the contentView
 */
- (CGRect)pageController:(WMPageController *)pageController preferredFrameForContentView:(WMScrollView *)contentView;

/**
 Implement this datasource method, in order to customize your own menuView's frame
 
 @param pageController The container controller
 @param menuView The menuView
 @return The frame of the menuView
 */
- (CGRect)pageController:(WMPageController *)pageController preferredFrameForMenuView:(WMMenuView *)menuView;
```
添加了两个自定义frame的dataSource方法，现在可以比较方便的设置menu和content的frame了
