### ISSUE TITLE
给wmpagecontroller设置三个childviewcontroller，滑动的时候输出selectedIndex，前两个一样都是0

### ISSUE THREAD

**Issue by gy37** [wangmchn/WMPageController#227]
给wmpagecontroller设置三个childviewcontroller，滑动的时候输出selectedIndex，前两个一样都是0，不能区分到底选中的是哪个controller

**Comment by gy37** [comment]
输出[pageController.childViewControllers indexOfObject:self] 的时候，后面两个的index一样；

好奇怪啊！！

**Comment by gy37** [comment]
修改preloadPolicy为near或neighbor的时候可以，但是我不想预加载，能不能有其他的方式，准确的获取当前选中的controller的index？

**Comment by gy37** [comment]
通过设置keys和values，可以区分。。

**Comment by Pikdays2018** [comment]
@gy37 怎么设置区分？
