### ISSUE TITLE
关于menuView的alpha问题

### ISSUE THREAD

**Issue by RenSihao** [wangmchn/WMPageController#228]
先设置menuView的alpha为0，然后设置self.navigationItem.titleView为自定义view，再次设置menuView的alpha为1，此时menuView被释放掉了，除非reloadData，否则menuView不会出现了。

**Comment by wangmchn** [comment]
@RenSihao 
这里不是alpha的问题，应该是设置了showOnNavigationBar = YES，这个时候你设置titleView为其他视图时，menuView就会因为没有引用就被释放了(menuView是原本的titleView)
这里建议用如下方式代替：
1.设置menuView.alpha = 0
2.[self.navigationBar addSubview:customView]

**Comment by RenSihao** [comment]
thx 👍
