### ISSUE TITLE
控制器 底部留白的问题

### ISSUE THREAD

**Issue by DeveloperChen** [wangmchn/WMPageController#229]
你好. 我用XIB创建了一个控制器, 控制器背景色为绿色, 然后添加到DataSource里面, 但是显示控制器的没有完全铺满, 底部还有空隙没有铺满, 麻烦请你看一下
![](
![simulator screen shot 2017 3 12 17 14 55](https://cloud.githubusercontent.com/assets/19606566/23830529/d851e5e0-0747-11e7-8f58-693350e817b0.png)
)

**Comment by DeveloperChen** [comment]
而且只有第一次Push进入的时候 有这个问题  再次进入的时候 这个问题就没有了

**Comment by wangmchn** [comment]
@DeveloperChen 试试设置 WMPageController.viewFrame 能不能解决这个问题？
