### ISSUE TITLE
There is an extra line at the bottom of tab on iPhone 6

### ISSUE THREAD

**Issue by ghysrc** [wangmchn/WMPageController#23]
iPhone 5c:
![screen shot 2015-11-06 at 5 25 14](https://cloud.githubusercontent.com/assets/4082752/10993704/b9f8f87e-84ab-11e5-802e-df476aa1668b.png)
iPhone 6:
![screen shot 2015-11-06 at 5 23 42](https://cloud.githubusercontent.com/assets/4082752/10993706/c25f7d4e-84ab-11e5-876e-7381c5489bb2.png)

**Comment by wangmchn** [comment]
It's weird.This problem never showed in my device.
you can set pageController.view's backgroundColor to MenuView's backgroundColor temporarily?
(I don't know if it works.)
Then I will try to find out the reason.

**Comment by ghysrc** [comment]
Well, it works.
When I set different backgroundColors to the PageController, this line on iPhone 6 change its color too.
It there a 1px space between the MenuView and the ChildViewController's view?

**Comment by wangmchn** [comment]
I never mean to have this 1px space,But it just showed unexpectedly. :(
And It's weird that I never see this on my device.
I have set ChildViewController.view just blew the MenuView.
(ChildViewController.view's y) == (menuview'y + menuview's height)
There must be something I missed.
