### ISSUE TITLE
内存释放不了

### ISSUE THREAD

**Issue by yezhanxiang** [wangmchn/WMPageController#230]
WMPageController *pageVC = [[WMPageController alloc] initWithViewControllerClasses:viewControllers andTheirTitles:titles];
我是这样创建，但是发现内存释放不了，所有打开过的子控制器和WMPageController都不能被释放。

**Comment by wangmchn** [comment]
几个控制器？建议看下WMPageController.h里面的cachePolicy，WMPageController有一个缓存策略可以了解下，如果不需要缓存可以关掉

发自我的 iPhone
