### ISSUE TITLE
Style 为 WMMenuViewStyleLine 的时候，选中条切换的速度很慢

### ISSUE THREAD

**Issue by hilen** [wangmchn/WMPageController#232]
```
self.menuViewStyle = WMMenuViewStyleLine;
self.menuView.speedFactor = 0;
```
我在代码里面这么设置的，但是选中条滑动还是很慢是为什么呢？

代码版本号是：2.2.1
模拟器系统：10.2.0
Xcode：8.2.1
CocoaPods：1.2.0

**Comment by wangmchn** [comment]
试试真机看，不需要设置speedFactor，看看问题还存在不
模拟器确实会存在这个问题，原因是 CADisplayLink 在模拟器上回调不准

**Comment by hilen** [comment]
嗯，没有问题了

**Comment by hilen** [comment]
打开缓存后，发现有个流程上是不是可以做一下优化？？

仔细读了源码，发现在 `wm_layoutChildViewControllers` 这个方法中判断 `frame` 是否在 `wm_isInScreen` 屏幕内。但是如果设置 `preloadPolicy = WMPageControllerPreloadPolicyNeighbour` 的时候依然会删除左右相邻的 `ViewController`。当进入新的选中的 `ViewController` 时，`didEnterController` 方法的最后几行又会去从缓存中加载删除了的 `ViewController`。 这个设计是不是有优化空间？？

举个例子：
0,1,2,3,4,5 个 ViewController

默认进入0，滑动到 1 的时候，这会 0 会删除，然后`scrollViewDidEndDecelerating`方法会调用`didEnterController` 方法 ，此时 index =1 。 然后在 didEnterController 里就出现了从缓存中读取 0 加载到`UIScrollView` 上。 这里 0 其实是 1 的邻居，所以是不是不用删除，保留在 `UIScrollView` 上？

**Comment by wangmchn** [comment]
@hilen 这里确实是一个可以优化的点，感谢指出！
