### ISSUE TITLE
作者您好，小白问题：pageController:viewControllerAtIndex下加载一个自定义cell的tableview

### ISSUE THREAD

**Issue by lhconnect5** [wangmchn/WMPageController#238]
uitableview中内嵌prototype cells，用一个uitableviewcell文件作简单的自定义，
uitableview中的cellForRowAtIndexPath:如下：
[self.tableView registerClass:[newTableViewCell class] forCellReuseIdentifier:@"newCell"];
    newTableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:@"newCell" forIndexPath:indexPath];
    cell.cellLabelc = @"123";
当我设定section为1，row为3时，通过立体图层确实可以看到载入了三个row，但传入的@“123”却无法显示。
采用官方默认布局的cell却可以传入数据。
我看到您示例中都没有用到自定义的tableviewcell，都是官方默认的布局，是不支持自定义嘛？

**Comment by wangmchn** [comment]
支持自定义的，一个不清楚你的cell. cellLabelc的实现，第二个，把cell的注册提前[self.tableView registerClass:[newTableViewCell class] forCellReuseIdentifier:@"newCell"];到viewDidLoad试试

**Comment by lhconnect5** [comment]
试了没用。。。
celllabelc用的常规的定义：
newTableViewCell.h
@property (weak, nonatomic) IBOutlet UILabel *cellLabel;

@property (copy, nonatomic) NSString *cellLabelc;

newTableViewCell.m
@synthesize cellLabelc;

- (void)setCellLabelc:(NSString *)str {
    if(![str isEqual:cellLabelc]){
        cellLabelc = [str copy];
        self.cellLabel.text = cellLabelc;
    }
}

**Comment by wangmchn** [comment]
把demo发上来看看？

**Comment by lhconnect5** [comment]
[pcp.zip](https://github.com/wangmchn/WMPageController/files/907235/pcp.zip)

**Comment by wangmchn** [comment]
3个步骤
1.找到storyboard中newTableViewController，填上identitier：newTableViewController
2.
```
- (UIViewController *)pageController:(WMPageController *)pageController viewControllerAtIndex:(NSInteger)index {
    UIStoryboard *sb = [UIStoryboard storyboardWithName:@"Main" bundle:nil];
    return [sb instantiateViewControllerWithIdentifier:@"newTableViewController"];
```
3.删掉所有newTableViewController中的[self.tableView registerClass:[newTableViewCell class] forCellReuseIdentifier:@"newCell"]

**Comment by lhconnect5** [comment]
谢谢。。
好奇。。麻烦问下老方法不行的原因呢？

**Comment by wangmchn** [comment]
你使用的是storyboard，需要用storyboard来返回创建的实例，如果用alloc/init的方式就会被认为是代码实现了（[self.tableView registerClass:[newTableViewCell class] forCellReuseIdentifier:@"newCell"]同样会被认为是代码实现）
而你cell的代码实现中，根本没有创建label所以显示不出来

**Comment by lhconnect5** [comment]
谢谢，周末愉快！
