### ISSUE TITLE
menuView 到下面的scrollView可以加个间隔字段

### ISSUE THREAD

**Issue by codwam** [wangmchn/WMPageController#24]
menuView 到下面的scrollView可以加个间隔字段

**Comment by wangmchn** [comment]
hi，@codwam
好的，会最近加上该字段

**Comment by wangmchn** [comment]
已经加了该字段了 看看是否符合？

**Comment by codwam** [comment]
嗯，谢谢了。
不过最近我用 RESideMenu 和你的混合使用的时候，发觉他的右滑手势没用了。。

**Comment by wangmchn** [comment]
没用过这个。试试禁止bounce后滑到头它的右滑手势还有效不？

**Comment by codwam** [comment]
self.bounces = NO; // 不可以
self.scrollView.hidden = YES; // 可以

**Comment by wangmchn** [comment]
应该是scrollview和它的gesture冲突了
看看这个是否有帮助
`http://blog.csdn.net/hjaycee/article/details/49279951`

**Comment by codwam** [comment]
上面的menuView点击的时候没有切换childViewController，滑动的时候才有

**Comment by wangmchn** [comment]
我这里正常，能给下demo吗

**Comment by codwam** [comment]
- (void)menuView:(WMMenuView *)menu didSelesctedIndex:(NSInteger)index currentIndex:(NSInteger)currentIndex
代理方法实现之后（里面没写任何代码），除了第一个view的viewDidLoad执行之后，其他的都不执行了

**Comment by wangmchn** [comment]
请问是在子类实现了该方法？
该方法我在父类实现了的，重写的话，我父类的就会失效，所以才会不能切换

**Comment by codwam** [comment]
对，我现在就是想在点击和滑动的时候触发事件

**Comment by wangmchn** [comment]
是这样的 我有两个通知，一个是每个子控制器完全展示在用户面前发送的，还有一个是在每个控制器刚刚出现的时候发送，可以通过添加观察者来监视。
除此之外想要做一些操作的话，就要自己改代码了

**Comment by codwam** [comment]
我发觉了把你的Demo改为只有4个控制器或5个，点几次第二个和第四个或者第五个，viewWillAppear这些方法就不会执行了。。

**Comment by wangmchn** [comment]
是BUG。。之前改的时候不小心删了段代码引入的，这就修复一下。

**Comment by codwam** [comment]
最近的项目有个sidemenu，但是scrollview的手势导致他没触发，你上面的也解决了我的问题，给你pull request了，写的不好的话，自己再写吧，Thanks...
