### ISSUE TITLE
有使用WMMenuView类的demo吗？

### ISSUE THREAD

**Issue by EdenChow** [wangmchn/WMPageController#244]
_menuView = [[WMMenuView alloc] initWithFrame:CGRectMake(0, 64, WIDTH, 40)];
    _menuView.delegate = self;
    _menuView.dataSource = self;
    _menuView.style = WMMenuViewStyleLine;
    
    [self.view addSubview:_menuView];

代理方法
- (NSInteger)numbersOfTitlesInMenuView:(WMMenuView *)menu {

    return 3;
}
- (NSString *)menuView:(WMMenuView *)menu titleAtIndex:(NSInteger)index {

    return @"123";
}

- (CGFloat)menuView:(WMMenuView *)menu widthForItemAtIndex:(NSInteger)index {

    return 50;
}

但是无法显示出来。为什么呢？

**Comment by EdenChow** [comment]
问题解决了，因为作者的 WMMenuView 类是使用scrollView 作为容器，系统会为第一scrollview 里面的子控件往下偏移64，所以看不到WMMenuItem，需要在控制器加上： self.automaticallyAdjustsScrollViewInsets = NO;

**Comment by wangmchn** [comment]
👍
