### ISSUE TITLE
菜单栏目不固定的情况下这么初始化？

### ISSUE THREAD

**Issue by SuXW** [wangmchn/WMPageController#25]
我的工程的首页就是这种控制器，  但是菜单的栏目是从网络获取的，  而我的APP一启动就直接显示首页，  请问我要怎么处理？

**Comment by wangmchn** [comment]
@SuXW 现版本支持的不是很好，后续会加上reload功能
时间上没准信，可能得先去找找其他更好的库了。

**Comment by wangmchn** [comment]
@SuXW 建议这样试试，先到一个普通空白的viewController加载loading动画，结束后切换window的rootViewController到带有PageController的首页。
不知是否符合要求，我看很多多是这么做的

**Comment by SuXW** [comment]
谢谢，  我现在想了一个办法，暂时解决了。   
  还有一个问题就是我在使用这个框架时，  当WMPageController当成tabbar的一页加载在界面上时，  如果我左右滑动来切换标签，则标签与内容中间会出现一个奇怪的缝隙（tabbar是rootVC）。   如果设置成navtionBar  则不会有上述问题。
直接点击标签也不会有这个奇怪的缝隙

**Comment by SuXW** [comment]
![untitled](https://cloud.githubusercontent.com/assets/12590725/11137892/09b1abf4-89f7-11e5-9eb4-c9bc9307fbf3.gif)
大概是这样。

**Comment by wangmchn** [comment]
应该是我contentSize计算有误差 这个BUG之前改过一次 
看来还是没改好，我再上传一次 然后你拉一下代码再试试

**Comment by SuXW** [comment]
好的  谢谢了

**Comment by SuXW** [comment]
还是不能， 我不知道问题出在什么地方

**Comment by wangmchn** [comment]
623421832
