### ISSUE TITLE
内容增加

### ISSUE THREAD

**Issue by LMfiles** [wangmchn/WMPageController#251]
progressView可否开放可以设置背景颜色的属性。因为项目需求，需要把现有的白色改为灰色。多谢！

**Comment by wangmchn** [comment]
可以重写ViewDidLoad和ReloadData方法，在方案最后设置progressView的背景色

**Comment by LMfiles** [comment]
好的，多谢！ 
------------------ Original ------------------

**Comment by LMfiles** [comment]
还有个问题，老铁。就是reloadData时原来的控制器会被释放掉，那我在刷新之前录入的内容就会被干掉。这个有什么解决的办法，我没找到！ 
------------------ Original ------------------

**Comment by wangmchn** [comment]
是会被干掉，录入的内容指什么？重新录入一遍或者自己做缓存
