### ISSUE TITLE
关于视图代理的问题

### ISSUE THREAD

**Issue by Rain-dew** [wangmchn/WMPageController#253]
在使用您的Page控制器的时候。我希望有一个didSelected的代理方法来判断我点击了哪个。但是PageControllerDelegate中没有这样的代理，那么当我在index = 0的控制器中的时候，我希望这时候再点击第一个item。做一个事情。然而我无法得到这个再次点击的时刻？其他代理皆不能收到这个时机。那么，我从而想到memuView也有个代理，并且是有didSelected代理。因此我去设置pageVc.menuView.delegate = self;结果让我惊讶的是，这样设置，代理方法根本不走，也就是说是无效的？

**Comment by wangmchn** [comment]
@Rain-dew 不要修改menuView的代理，这里比较好的方案是子类WMPageController，在WMPageController的子类重写menuView的didSelect代理（别忘了调用super），你也可以让子类把这个事件转发出来

**Comment by Rain-dew** [comment]
好的，我写个继承，谢了！
