### ISSUE TITLE
添加小红点

### ISSUE THREAD

**Issue by linwenquan** [wangmchn/WMPageController#254]
请问能给你的框架中添加小红点的功能吗？类似微信的收到消息后在menu的item上显示小红点

**Comment by linwenquan** [comment]
请问怎么添加小红点？

**Comment by wangmchn** [comment]
```
/**
 *  角标 (例如消息提醒的小红点) 的数据源方法，在 WMPageController 中实现这个方法来为 menuView 提供一个 badgeView
    需要在返回的时候同时设置角标的 frame 属性，该 frame 为相对于 menuItem 的位置
 *
 *  @param index 角标的序号
 *
 *  @return 返回一个设置好 frame 的角标视图
 */
- (UIView *)menuView:(WMMenuView *)menu badgeViewAtIndex:(NSInteger)index;
```

**Comment by linwenquan** [comment]
我已经在WMPageController 里面实现了这个方法，如下：
UIView *view = nil;
    if(self.selectIndex == index)
    {
        view = [[UIView alloc] initWithFrame:CGRectMake(self.menuItemWidth-20, 10, 10, 10)];
        view.layer.cornerRadius = 5;
        view.layer.masksToBounds = YES;
        view.backgroundColor = [UIColor redColor];
    }
    return view;
但是当我收到通知的时候需要去掉这个小红点，在你的框架中有提到需要在下面的方法里面返回nil：
/**
 *  更新角标视图，如要移除，在 -menuView:badgeViewAtIndex: 中返回 nil 即可
 */
- (UIView *)badgeViewAtIndex:(NSInteger)index {
    if (![self.dataSource respondsToSelector:@selector(menuView:badgeViewAtIndex:)]) {
        return nil;
    }
    UIView *badgeView = [self.dataSource menuView:self badgeViewAtIndex:index];
    if (!badgeView) {
        return nil;
    }
    badgeView.tag = index + WMBadgeViewTagOffset;
    
    return badgeView;
}

这个方法如果直接返回nil的话，那么前面设置小红点的方法就会无效，那该怎么处理？

**Comment by wangmchn** [comment]
在这个方法-menuView:badgeViewAtIndex:返回nil
不是-badgeViewAtIndex:(NSInteger)index

**Comment by linwenquan** [comment]
框架里面没有很好的处理小红点的需求，不过还是修改了逻辑完成了需求，希望能通过属性的设置开达到这样的需求，毕竟这样的需求现在已经是很常见的了。

**Comment by linwenquan** [comment]
能否通过属性来达到添加以及删除小红点的功能呢？或者是调用wmpagecontroller的方法来实现呢，这样才能达到真正的框架效果。
