### ISSUE TITLE
在屏幕以外创建会无效果

### ISSUE THREAD

**Issue by Steven-Yung** [wangmchn/WMPageController#258]
我想做一个类似京东商品页上拉出现详情页的效果，一个大容器(UIScrollerView或者UITableView)中在顶部用一个全屏幕大小的VC，底部用WMPageController实现分页，可是因为WMPageController是在屏幕以外创建的，上拉的时候MWPageController除了Menu以外一片空白(其实一个item对应一个TableView的)，这是怎么回事？实验证明，在屏幕以外创建都会这样，联系我356586162@qq.com，我发demo给你看，谢谢了！
![11221](https://cloud.githubusercontent.com/assets/8358206/26366467/d0b1ae38-401d-11e7-981d-48e3e9270d97.png)

**Comment by wangmchn** [comment]
@Steven-Yung 麻烦发下demo到这个邮箱：wangmchn@163.com，thanks~

**Comment by wangmchn** [comment]
@Steven-Yung WMPageController 对于屏幕外创建的视图计算确实存在BUG, 建议这里设置下 viewFrame 属性，后续我抽时间修复这个问题

**Comment by wangmchn** [comment]
```

/**
 Implement this datasource method, in order to customize your own contentView's frame

 @param pageController The container controller
 @param contentView The contentView, each is the superview of the child controllers
 @return The frame of the contentView
 */
- (CGRect)pageController:(WMPageController *)pageController preferredFrameForContentView:(WMScrollView *)contentView;

/**
 Implement this datasource method, in order to customize your own menuView's frame
 
 @param pageController The container controller
 @param menuView The menuView
 @return The frame of the menuView
 */
- (CGRect)pageController:(WMPageController *)pageController preferredFrameForMenuView:(WMMenuView *)menuView;
```
添加了控制frame的两个dataSource方法
