### ISSUE TITLE
NavigationBar 颜色被改变

### ISSUE THREAD

**Issue by tianwen-li** [wangmchn/WMPageController#26]
我的项目里，当显示WMPageController时，Navigation Bar 的颜色会变成亮灰色，而我的项目所有其他部分都是白色。我尝试在WMPageController初始化时设置view的背景颜色为白色也是无效。
Navigation Bar的颜色是在切换动画完成后改变的，也就是动画之中颜色还是正常，一旦动画结束颜色就变成亮灰了。

这个问题在你的demo里也能看到，只是变化是反的，切换过程中是亮灰，切换完毕变成白色。

**Comment by wangmchn** [comment]
是这样的 WMPageController 的 view 不会出现在navigationBar的底部，因为设置了 edgesForExtendedLayout为none，如果想要延生到navigationBar底部可以注释掉该代码 然后手动设置viewFrame属性

**Comment by tianwen-li** [comment]
非常感谢！我搞定了
