### ISSUE TITLE
menuTItle多的时候,点击最后一个界面滚动会卡

### ISSUE THREAD

**Issue by cleven1** [wangmchn/WMPageController#260]
您好  当我menuTItle有10个的时候,我的VC在第一个,也就是0的位置,然后滑动menuView到最后,点击第10个Title,VC在滚动的时候会卡,很明显的卡顿,请问 该怎么解决呢 ,谢谢

**Comment by wangmchn** [comment]
开启了滚动动画吗？建议关掉哦

**Comment by wangmchn** [comment]
或者加载数据放到
- (void)pageController:(WMPageController *)pageController didEnterViewController:(__kindof UIViewController *)viewController withInfo:(NSDictionary *)info;
执行
