### ISSUE TITLE
non-public api

### ISSUE THREAD

**Issue by xingyong723** [wangmchn/WMPageController#263]
NSClassFromString(@"_UINavigationBarBackground") 
NSClassFromString(@"UITableViewWrapperView")
因为这个两个方法，审核的时候被拒，说使用了私有api

**Comment by wangmchn** [comment]
好的 我看看优化下

**Comment by hydyy** [comment]
确定是因为这两个方法被拒的吗？ 如果是的话我就不敢用了啊

**Comment by wangmchn** [comment]
虽然不确定是不是这两个方法的问题，现在WMPageController把这些有被拒风险的私有API调用删掉了，有问题再反馈哈

**Comment by wangmchn** [comment]
代码中确实一直在用这个
[xxView isKindOfClass:NSClassFromString(@"UITableViewWrapperView")]
的判断，没有遇到被拒的情况，这里跟TableViewCell的删除手势的冲突不太好处理
我换种方式，试试还有没这个问题？
[NSStringFromClass(otherGestureRecognizer.view.class) isEqualToString:@"UITableViewWrapperView"]
