### ISSUE TITLE
didSelesctedIndex:方法导致返回为nil

### ISSUE THREAD

**Issue by LGLee** [wangmchn/WMPageController#266]
//- (void)menuView:(WMMenuView *)menu didSelesctedIndex:(NSInteger)index currentIndex:(NSInteger)currentIndex{
//    self.navigationItem.rightBarButtonItem.customView.hidden = (currentIndex==0)?YES:NO;
//}
我想在选择不同的item的时候让navrightitem隐藏.但是这样会导致
- (UIViewController *)pageController:(WMPageController *)pageController viewControllerAtIndex:(NSInteger)index ;方法的index为nil

**Comment by wangmchn** [comment]
调用super的方法了吗？

**Comment by wangmchn** [comment]
暂无后续恢复，先关闭了
