### ISSUE TITLE
请问一下，能自定义MenuView吗？

### ISSUE THREAD

**Issue by jjzjx118** [wangmchn/WMPageController#269]
我的需求是menuView最右边是一个排序按钮，点击的时候把当前显示的VC（tableView）重新排序。
目前我还没有找到每个title点击的执行方法，还请告知下。谢谢啦。另外好像也没有currentVC这样的属性。不置可否添加一下呢？

我目前的打算是覆盖一个透明View到MenuView上，然后添加透明的button，当点击的时候去执行原来menuView的点击操作。

**Comment by wangmchn** [comment]
menuView有个rightView的属性，可以在viewDidLoad之后设置
任何一个title的点击都会执行：
```
- (void)menuView:(WMMenuView *)menu didSelesctedIndex:(NSInteger)index currentIndex:(NSInteger)currentIndex;
```

**Comment by jjzjx118** [comment]
@wangmchn  非常感谢：）

**Comment by jjzjx118** [comment]
@wangmchn 抱歉，还想请问一下，RightView 可否设置右边间隔？希望能和menuItem一样 均分整个menuView。

**Comment by wangmchn** [comment]
可以设置rightView的frame的宽度大一些？

发自我的 iPhone
