### ISSUE TITLE
我想在顶部菜单栏底部加一条分割线，目前加不上去

### ISSUE THREAD

**Issue by tianwen-li** [wangmchn/WMPageController#27]
我想在顶部菜单栏底部加一条分割线，目前加不上去。我是尝试在WMPageController初始化的时候加一个view到menuView,可是此时menuView为空。我尝试在viewDidiLoad中加但也是空的。

**Comment by wangmchn** [comment]
menuView是viewDidAppear的时候才会有，可以考虑在WMMenuView的内部做修改

**Comment by tianwen-li** [comment]
非常感谢！
