### ISSUE TITLE
选中之后的背景色的圆角 可以调整吗 ?  急急急

### ISSUE THREAD

**Issue by Ws1797822324** [wangmchn/WMPageController#273]

**Comment by Ws1797822324** [comment]
self.pageAnimatable = YES;
    
    self.menuHeight=40;
    
    
    
    self.menuBGColor=[UIColor whiteColor];
    
    self.titleColorSelected = [UIColor whiteColor];
    
    self.titleColorNormal = [UIColor blackColor];
    
    self.progressColor = [UIColor redColor];
    

    self.menuViewLayoutMode = WMMenuViewLayoutModeScatter;
    
    self.menuViewStyle = WMMenuViewStyleFlood;
    

    
    self.progressViewBottomSpace = 1;

**Comment by wangmchn** [comment]
设置这个属性即可 progressViewCornerRadius

**Comment by Ws1797822324** [comment]
后来仔细看了  发现了  😓😓  QAQ
