### ISSUE TITLE
关于参数传递的问题

### ISSUE THREAD

**Issue by MoonLht** [wangmchn/WMPageController#278]
目前是keys和values一一对应来传递，请问一下如果一个controller有多个参数的时候应该如何传递？

**Comment by wangmchn** [comment]
建议通过：
```
- (__kindof UIViewController *)pageController:(WMPageController *)pageController viewControllerAtIndex:(NSInteger)index {
    // Initialize view controller..
    // ...
    vc.foo = foo;
    vc.bar = bar;
    return vc;
}

```

**Comment by MoonLht** [comment]
恩，当时没注意，我目前是在子控制器里通过通过代理返回参数的

**Comment by MoonLht** [comment]
另外还有一个问题，就是系统左滑的时候会出现scrollview和controller同时接收滑动事件的情况，如何在这个时候禁止scrollView的滑动呢？self.scrollView.otherGestureRecognizerSimultaneously = YES;这个属性貌似不好用
