### ISSUE TITLE
Can we set `self.scrollView.scrollsToTop = NO;` as default in `WMMenuView`?

### ISSUE THREAD

**Issue by xilin** [wangmchn/WMPageController#28]
Without this setting, I cannot support scroll to top gesture. And the scrollView property of `WMMenuView` is private which cannot be modified.

Thanks.

**Comment by wangmchn** [comment]
Yeah, it's my fault.
I will add it in next commit.
Thanks a lot.

**Comment by xilin** [comment]
@wangmchn Thanks for that. Look forward for the next release.
