### ISSUE TITLE
2.4版本无法设置menuView的背景颜色

### ISSUE THREAD

**Issue by jhchenchong** [wangmchn/WMPageController#281]
pageController?.menuView?.backgroundColor = UIColor.red  在初始化的时候设置背景颜色无效  在返回menuView frame的方法中设置就可以

**Comment by wangmchn** [comment]
是的 因为初始化的时候视图还没有创建，这里在frame方法设置是ok的

**Comment by Huang-Libo** [comment]
2.4 版本的 `menuBGColor` , `menuHeight` , `viewFrame ` 属性都没法用了, 请问替代方式是什么? 如果有一个 API 变动的说明文档或迁移文档就好了

**Comment by wangmchn** [comment]
我周末有空整个文档～
现在提供了两个新的数据源接口
一个是定制contentView的frame
另一个是定制menuView的frame
然后关于menuView的背景色，可以在viewdidload之后直接设置

发自我的 iPhone

**Comment by Huang-Libo** [comment]
关于[这个](https://github.com/wangmchn/WMPageController/issues/264)(做成 ContainerViewController) issue, 如果要改变实现方式, 是不是需要较大规模的 API 改动?

**Comment by Huang-Libo** [comment]
如果 API 的变化能加个 Changelog 就更好了

**Comment by wangmchn** [comment]
@Huang-Libo 很不错的提议👍 确实有一些之前写的不太满意的地方，一直都想做修改

**Comment by wangmchn** [comment]
@Huang-Libo ChangeLog我会在近期尽快加上，然后会抽空整理个文档输出出来
