### ISSUE TITLE
关于Storyboard屏幕旋转遮盖titles的问题

### ISSUE THREAD

**Issue by DabbyCHEN** [wangmchn/WMPageController#286]
1. Xcode / iOS / WMPageController 的版本信息
Xcode8.3.3   /    iPhone7Plus模拟器    /     iOS10.3.1    /    WMPageController0.36.4?

2. 编译错误或者运行时错误时，编译器提供的所有信息
每次旋转都会打印以下日志信息：（但程序依然能正常运行）
Storyboard[1610:373798] [App] if we're in the real pre-commit handler we can't actually add any new fences due to CA restriction

3. 关键的代码片段
用的大神自带Demo -- StoryboardExample，直接运行后来回旋转屏幕，即发现导航栏遮挡titles的问题
![1](https://user-images.githubusercontent.com/18324410/28048971-d9725228-6626-11e7-8883-b024782d29f9.png)
![2](https://user-images.githubusercontent.com/18324410/28048970-d971f864-6626-11e7-87b5-d9a24e59c947.png)
![3](https://user-images.githubusercontent.com/18324410/28048972-d976b39a-6626-11e7-8818-0ded623fca73.png)

**Comment by wangmchn** [comment]
@DabbyCHEN 我有空修复下这个问题，由于240版本不再内部适配contentFrame，这里需要实现下下面的两个方法：
https://github.com/wangmchn/WMPageController#customize-contents-frame

**Comment by DabbyCHEN** [comment]
大神，我将WMPageController应用至我的app，然后真机测试，包括5s和ipad air2，发现旋转不会遮盖titles。可能是模拟器的问题？但每次旋转依然会打印上述日志信息。
另外，我想请问一下，在WMMenuView中有设置角标的方法：(UIView *)menuView:(WMMenuView *)menu badgeViewAtIndex:(NSInteger)index;。我在WMPageController中实现后，发现一个问题，参数menu.frame.size.width等于0，这样我将无法获得menuview的大小，那我怎么确定角标的位置呢，因为不同设备不一样啊。

**Comment by DabbyCHEN** [comment]
还有一个问题再麻烦大神解答一下，我的需求是：当收到ios推送后，给NSNotificationCenter发一个消息，然后在具体VC中添加了一个监视器，当收到推送后，给指定的MenuView加角标。这个方法怎么实现呢？
或者还有一个方案是，我用了一个三方小红点控件：WZLBadge。它可以给任意UIView加小红点，我如何能获取到指定index的MenuView呢？

**Comment by wangmchn** [comment]
@DabbyCHEN 
整体只有一个MenuView，你可以在WMPageController内实现（监听）
-(UIView *)menuView:(WMMenuView *)menu badgeViewAtIndex:(NSInteger)index
这个方法，返回对应位置的badge，至于menuView的大小，是你自己通过
- (CGRect)pageController:(WMPageController *)pageController preferredFrameForMenuView:(WMMenuView *)menuView;
这个方法实现设置的，你自己也可以通过这个方法来获取menuView的frame的
