### ISSUE TITLE
Is there a way to update tab item title?

### ISSUE THREAD

**Issue by xilin** [wangmchn/WMPageController#29]
In my case, I need to show a number in the item title, and update them at some times.

It seems that currently there is no method to update the title easily?

For fixed width items it should be easily to be updated since no frame recalculation is needed?

**Comment by wangmchn** [comment]
Yes,no good method,only one but support badly.
You can reset `titles` property and then call `-reloadData`.
This method will remove all views, clear datas and add again.
(make sure that all array's count are correct :[ )
I will change some menuview's properties to `datasource`, so can help reload designated items.
It's in construction, coming soon.

**Comment by xilin** [comment]
@wangmchn That's too heavy for me. I'll create a fork to do some brute force way for myself only for now.
Thanks!

**Comment by wangmchn** [comment]
add a update method now......

**Comment by wangmchn** [comment]
but found a bug with porgressView if use `- (void)updateTitle:(NSString *)title andWidth:(CGFloat)width atIndex:(NSInteger)index;`
I will fix soon....

**Comment by xilin** [comment]
Thanks you very much for the quick response!

**Comment by wangmchn** [comment]
Mayby fixed now...

**Comment by xilin** [comment]
It works. Thanks.
