### ISSUE TITLE
menuView selected bug?

### ISSUE THREAD

**Issue by litt1e-p** [wangmchn/WMPageController#31]
it calls the method:addMenuView when I scroll , and go to below lines:
- if (self.selectIndex != 0) {
- [self.menuView selectItemAtIndex:self.selectIndex];
- }

then in the WMMenuView.m:
-(void)selectItemAtIndex:(NSInteger)index {
- NSInteger tag = index + kTagGap;
- NSInteger currentIndex = self.selItem.tag - kTagGap;
- WMMenuItem *item = (WMMenuItem *)[self viewWithTag:tag];
- [self.selItem deselectedItemWithoutAnimation];
- self.selItem = item;
- [self.selItem selectedItemWithoutAnimation];
- [self.progressView setProgressWithOutAnimate:index];
- if ([self.delegate respondsToSelector:@selector(menuView:didSelesctedIndex:currentIndex:)]) {
        [self.delegate menuView:self didSelesctedIndex:index currentIndex:currentIndex];
- }
-  [self refreshContenOffset];
}

there is a delegate method @selector(menuView:didSelesctedIndex:currentIndex:), it will send to its delegate and responds to it. _animate will become NO, the bug comes:when I scroll again, the menuView couldn't add its view, cause in the method below:
- -(void)scrollViewDidScroll:(UIScrollView *)scrollView, menuView can not call slideMenuAtProgress:.

it works well when I delete some delegate codes in  the WMMenuView.m: - (void)selectItemAtIndex:(NSInteger)index:

//    if ([self.delegate respondsToSelector:@selector(menuView:didSelesctedIndex:currentIndex:)]) {
//        [self.delegate menuView:self didSelesctedIndex:index currentIndex:currentIndex];
//    }

is it?

**Comment by wangmchn** [comment]
busy this time,I will check it later.
Thx a lot!
=0=

**Comment by wangmchn** [comment]
Hey, @litt1e-p 
Never found this, the `-slideMenuAtProgress:` is call correctly.
the variable `_animate` will become `YES` when scrollView start drag.
In this Method, I have set it.
```objective-c
- (void)scrollViewWillBeginDragging:(UIScrollView *)scrollView {
    _animate = YES;
}
```
So, If still have problem,could you give me more Info or just send your demo to me?
Thx a lot.

**Comment by litt1e-p** [comment]
ok, will email to your wangmchn@163.com

**Comment by wangmchn** [comment]
Hey, @litt1e-p 
Found the bug, it seems the bug was casued because of `Autolayout`.
I will try to fix it soon.
Sorry about that.

**Comment by wangmchn** [comment]
Maybe fixed...need test

**Comment by wangmchn** [comment]
Maybe fixed now.

**Comment by litt1e-p** [comment]
sorry, I forgot to send the demo. I will test your new fix. thanks a lot

**Comment by litt1e-p** [comment]
well done! you fixed this bug, it works fine in my project.thanks !
