### ISSUE TITLE
关于导航栏消失的问题

### ISSUE THREAD

**Issue by fantastichong** [wangmchn/WMPageController#310]
在我把ScrollView滑动屏蔽之后 使用左滑手势 导航栏消失了。。实在是找不出消失的原因 我是直接在Tabbar页面下使用的。

**Comment by hsy1885597** [comment]
只有第一次产生  感觉有视图响应了左滑这个手势  导致导航栏消失了 代码控制导航栏出现的话  第二次左滑就会直接响应到当前控制器的地图手势

**Comment by wangmchn** [comment]
导航栏是指menuView还是指navigationBar？

**Comment by hsy1885597** [comment]
navigationBar消失

**Comment by hsy1885597** [comment]
第一张http://wx4.sinaimg.cn/mw690/c53792f7gy1fiaurm5830j20ku1120wj.jpg
在这个界面左滑  只有左滑会产生http://wx4.sinaimg.cn/mw690/c53792f7gy1fiaurmgekaj20ku1120xu.jpg
结果http://wx2.sinaimg.cn/mw690/c53792f7gy1fiaurlqaysj20ku112n24.jpg
在不切换界面的情况下navgationBar仍然显示  但是其实已经无法点击了  视图层次也没有显示了

**Comment by wangmchn** [comment]
这里看看是被隐藏了还是直接被remove了，然后看看是什么方法导致导致的隐藏或是remove?
