### ISSUE TITLE
menuViewStyle为WMMenuViewStyleSegmented时，怎么能取消那个menuitem点击时的滑动效果？？求大佬指教！

### ISSUE THREAD

**Issue by Zhang1Peng** [wangmchn/WMPageController#322]
menuViewStyle为WMMenuViewStyleSegmented时，怎么能取消那个点击时的滑动效果？？求大佬指教！

**Comment by Zhang1Peng** [comment]
我指的是哪个item上的滑动效果，不是底下控制器的滑动效果。。

**Comment by Zhang1Peng** [comment]
我这边目前实现的方式是吧menuview的高度弄成0，然后放一个UISegmentedControl在navigationItem.titleView上，然后通过点击事件操作控制。
但是我只找到了一个setSelectIndex的方法，通过这个方法修改选中控制器，还需要reloaddata，那之前设置的titleview就变空白了，请问有没有一个修改选中控制器，但不用刷新的方法？

**Comment by Zhang1Peng** [comment]
![image](https://user-images.githubusercontent.com/14211337/29709076-96c9fc18-89bd-11e7-9f3c-f85d304b3a89.png)
因为是这种两层嵌套的，如果reload一下的话，第二层的已选中的控制器就变了，，大佬有没有好的解决方案？

**Comment by Zhang1Peng** [comment]
大神 求帮助啊～

**Comment by wangmchn** [comment]
@zhang1Peng 这个滑动效果目前取消不了
不过你可以尝试下设置一个大于0但是小的速度因子看看
/** 进度条的速度因数，默认为 15，越小越快， 大于 0 */
@property (nonatomic, assign) CGFloat speedFactor;

**Comment by Zhang1Peng** [comment]
哦哦，谢谢大佬，我目前的做法是减少一层wmpagecontroller。通过addChildViewController向一个控制器添加两个wmpagecontroller，不知道有没有问题。

**Comment by wangmchn** [comment]
@Zhang1Peng 没问题的
