### ISSUE TITLE
demo 写的垃圾的不能再垃圾！

### ISSUE THREAD

**Issue by boai** [wangmchn/WMPageController#328]
demo 写的垃圾的不能再垃圾！

**Comment by Huang-Libo** [comment]
好好说话, 请注意你的素质.
block&report

**Comment by shengxianghong** [comment]
自己垃圾还说别人，你是看不懂吧，请尊重作者的开源精神。

**Comment by longdw** [comment]
@boai  说别人之前先掂量下自己

**Comment by boai** [comment]
三楼的git 很牛逼嘛，尊重开源精神可以，但是代码问题我真心不想说！改版连注释都不写，好意思说，重大改版，改了啥东西都不写明，重申一点，不是我用的这代码，是我底下的人用的，更新pod 报错才来看的！再重申一点，自己垃圾就不要说别人，说别人之前好好掂量下自己！

**Comment by boai** [comment]
四楼，改版连注释都不写，好意思说，重大改版，改了啥东西都不写明，重申一点，不是我用的这代码，是我底下的人用的，更新pod 报错才来看的！再重申一点，自己垃圾就不要说别人，说别人之前好好掂量下自己！对于这种开源，我不会fork，也不会给你贡献！

**Comment by pengwj** [comment]
demo确实写得不用心呀，大兄弟

**Comment by boai** [comment]
都不知道二三四楼 喷的是啥，我说的是demo写的垃圾，又没说代码！

**Comment by wangmchn** [comment]
这一休假回来咋就骂起来了...
@boai 觉得那里不好可以提出来，大家都是来学习的，也没必要上来怼天怼地的
我资历不深也能力有限，时间也有限，天天加班都快没时间维护了，至于你说的改动 CHANGELOG 里面也简单提了，可以翻阅下：
https://github.com/wangmchn/WMPageController/blob/master/CHANGELOG.md

@Huang-Libo @shengxianghong @longdw 
也感谢上面各位大佬支持~加班不易，且行且珍惜
