### ISSUE TITLE
多次调用 viewDidLayoutSubviews

### ISSUE THREAD

**Issue by xoxhk** [wangmchn/WMPageController#33]
为什么我在我的项目中使用这些代码，在每次切换菜单的时候都会调用viewDidLayoutSubviews，导致menu每次都从0重新滚动一遍。而你的demo却没有，我自己做个实验，新建一个空白 的项目只放一个uiscrollview 每次向这个scrollview添加view的时候都会调用 viewDidLayoutSubviews。
真心很奇怪

**Comment by wangmchn** [comment]
hi, @xoxhk 
是否在视图内部使用了`Autolayout`呢？
最近刚修复了这个引起的bug。
可以使用下最新的，看下bug是否还存在？

**Comment by xoxhk** [comment]
嗯，我的每个的controller是从storybord加载的，内部有用autolayout,
我看到你修复的代码了，现在可以了，如果你有空能解释一下为什么就好了，

 CGFloat oldSuperviewHeight = _superviewHeight;
    _superviewHeight = self.view.frame.size.height;
    if (_hasInited && _superviewHeight == oldSuperviewHeight) return;

**Comment by wangmchn** [comment]
这段代码主要是判断了 如果 `self.view` 的高度不变，就禁止下面的代码执行。
(下面代码有对scrollView的contentOffset进行改变)
由于autolayout的存在，在scrollView滚动时会调用 -viewDidLayoutSubviews（具体系统是如何调用的还有待研究，如果知道还望告知），此时会引起重设contentOffset的情况，导致无法滚动或是滚动异常。
