### ISSUE TITLE
StickyExample 中 tableview 的 delegate 的方法不执行.

### ISSUE THREAD

**Issue by Huang-Libo** [wangmchn/WMPageController#330]
StickyExample 中 tableview 的 delegate 由 streachScrollView 方法设置为了 WMStickyPageViewController, 导致 tabelView 相关的代理不执行了... 请问这种情况该如何解决?@wanhmr

**Comment by wanhmr** [comment]
你需要执行 [suepr scrollViewDelegateMethod];

**Comment by wanhmr** [comment]
@Huang-Libo 可以具体点吗？我项目中使用没有这个问题。

**Comment by wanhmr** [comment]
@Huang-Libo 目前只有 `WMStickyPageViewController` 中实现了的方法，才能够在 tableView 中执行。这里确实没有考虑完善。

**Comment by wanhmr** [comment]
一种笨的方案是你参照 `WMStickyPageViewController` 的方式，在 `WMStickyPageViewController` 中实现所有的 `tableView` 的代理，然后调用 `super`。

**Comment by wanhmr** [comment]
并且旧代码有由于进行了除0操作所造成的闪退问题，目前已修复 #331 。

**Comment by wanhmr** [comment]
@Huang-Libo 
把 `tableView` 的 delegate  设置为了 `WMStickyPageViewController` 是没有问题的，因为这里会把消息转发给原始 `tableView` 的 delegate 以及 `WMStickyPageViewController`。

**Comment by Huang-Libo** [comment]
@wanhmr
太强了, TPDelegateMatrioska 确实把消息转发过来了, 而且即使有控制器嵌套, 只要它们都遵守 WMStickyPageViewControllerDelegate, 就能转发到 tableview 中.

**Comment by SunShineLOL** [comment]
需要在 将WMStickyPageViewControllerDelegate的代理对象 设置为与 tableview的代理对象一致,并实现相关的代理方法.
