### ISSUE TITLE
再次选中当前 WMMenuItem  刷新界面

### ISSUE THREAD

**Issue by yinqiangw** [wangmchn/WMPageController#336]
再次选中当前 WMMenuItem  刷新界面  
 没有找到类似方法

**Comment by wangmchn** [comment]
- (void)pageController:(WMPageController *)pageController willEnterViewController:(__kindof UIViewController *)viewController withInfo:(NSDictionary *)info;
每次进入一个控制器都会调用这个方法

**Comment by yinqiangw** [comment]
谢谢回复, 这个方法好像不能解决我的问题 .
点击 的menuItem 如果是当前正在显示界面,  获取事件刷新界面
点击 menuItem 如果不是当前显示界面, 比如下一个 切换界面  
类似 今日头条 titleItem 

看代码WMMenuView里面  如果menuItem重复选中, 直接 return 未处理
 我觉得这个功能还是很多人需要的

**Comment by wangmchn** [comment]
@yinqiangw 在子控制器复写试试？可以这样
```
- (void)menuView:(WMMenuView *)menu didSelesctedIndex:(NSInteger)index currentIndex:(NSInteger)currentIndex {
    [super menuView:menu didSelesctedIndex:index currentIndex:currentIndex];
}
```

**Comment by cocoaroger** [comment]
@yinqiangw 
我也刚好有这个需求，目前只是自己 fork 了一个版本，在方法：`- (void)didPressedMenuItem:(WMMenuItem *)menuItem` 里面加了个代理方法
https://github.com/cocoaroger/WMPageController/blob/master/WMPageController/WMMenuView/WMMenuView.m

**Comment by yinqiangw** [comment]
@cocoaroger 谢谢回复, 最新版本已经解决了这个问题
