### ISSUE TITLE
请问  ios 11 下 设置 self.showOnNavigationBar = YES  和 self.navigationItem.leftBarButtonItem  会导致 如下图问题 

### ISSUE THREAD

**Issue by guang-sun** [wangmchn/WMPageController#339]
![image](https://user-images.githubusercontent.com/16836583/30797121-6d13cd2e-a207-11e7-9313-ce2594d037c0.png)
![image](https://user-images.githubusercontent.com/16836583/30797201-a941718e-a207-11e7-90ba-1997faea419c.png)

**Comment by guang-sun** [comment]
![image](https://user-images.githubusercontent.com/16836583/30798208-4964cbf4-a20b-11e7-8e64-14e41f42ad1c.png)

滑到右侧时 也不能全部滑完

**Comment by guang-sun** [comment]
找到了怎么设置了...  - (CGRect)pageController:(WMPageController *)pageController preferredFrameForMenuView:(WMMenuView *)menuView

**Comment by meshangqingchen** [comment]
这个问题主要是 ios 11 UINavgationbar 结构发生改变的 原因..  我说一下ios 11我解决UINavgationbar 布局的思路 如果你用Reveal 看过UINavgationbar 的结构 就好有思路了 首先你可以 用重写 吧customView加到一个自定义的 view 上把这个自定义的 view 当成customView  然后在自定义的 view 的layoutSubviews 方法中 找到 subView 删除约束 加上自己的约束 (等于重新布局了系统的 UINavgationbar 里面影响布局的视图,自己看Reveal 那些影响了布局 ) 然后 titleView 用 left 或者 rightbuttonitem 代替 就可以了

**Comment by Hanchunlin** [comment]
遇到同样问题不知道咋个解决   我去
