### ISSUE TITLE
关于滑动问题

### ISSUE THREAD

**Issue by Eliothu** [wangmchn/WMPageController#35]
关于你的PageController 我想禁止手势滑动
我在你的WMPageController 的 addScrollView 方法中加入 scrollView.scrollEnabled = NO; 可以实现效果 
但是如果外部调用pageController.scrollview.scollEnable =NO;却无法实现,想请教一下

**Comment by wangmchn** [comment]
外部调用无法实现是因为 scrollView是在viewDidLoad的时候被加载的，然后你设置的时机是紧接在init之后，此时pageController的scrollView还是nil

**Comment by Eliothu** [comment]
谢谢
