### ISSUE TITLE
子控制器 init

### ISSUE THREAD

**Issue by codwam** [wangmchn/WMPageController#36]
// 添加子控制器
- (void)addViewControllerAtIndex:(int)index {
    Class vcClass = self.viewControllerClasses[index];
    UIViewController *viewController = [[vcClass alloc] init];

我想问下每次都自动init，那我如果想在ib或者sb里面加载怎么办。。

**Comment by wangmchn** [comment]
重写-init方法
```
- (instancetype)init {
    return [self initWithNibName:@"xxxViewController" bundle:nil];
}
```

**Comment by codwam** [comment]
好吧。
storyboard也是在这里加载，如果想修改collectionViewLayout，只能在viewDidLoad里面改了。。
- (instancetype)init {
    UIStoryboard *sb = [UIStoryboard storyboardWithName:@"Main" bundle:nil];
    self = [sb instantiateViewControllerWithIdentifier:@"HomeCVC"];
    
    return self;
}
