### ISSUE TITLE
最新版本中  menuItemHight 怎么没了。如何设置  菜单itemHight的高度啊

### ISSUE THREAD

**Issue by GuYueZhaoJinRen** [wangmchn/WMPageController#387]

**Comment by wangmchn** [comment]
- (CGRect)pageController:(WMPageController *)pageController preferredFrameForMenuView:(WMMenuView *)menuView;
现在需要通过这个代理解决

**Comment by GuYueZhaoJinRen** [comment]
太感谢了，帮到我了
