### ISSUE TITLE
如何修改menuView的高度

### ISSUE THREAD

**Issue by cnzlh** [wangmchn/WMPageController#39]
我现在这边的结构是这样的。
![image](https://cloud.githubusercontent.com/assets/5771860/11612686/1e8651e2-9c3f-11e5-84ab-38862a31f396.png)
然后在互联网设置(wanSettingsVC)中又加了几个navitationController(而不是viewController)作为childViewControllers.用于切换不同的上网方式。这时上面的menuView 的高度就变成下面这样了。请教下在哪里可以修改。THX
我设置了menuHeight为44，但是不管用。
![image](https://cloud.githubusercontent.com/assets/5771860/11612718/24ec43f6-9c40-11e5-8421-c84ebb253ad1.png)

![image](https://cloud.githubusercontent.com/assets/5771860/11612683/ea21f208-9c3e-11e5-95f1-8accb3bd7983.png)

**Comment by wangmchn** [comment]
是指修改origin.y？
在WMPageController的viewDidLayoutSubViews里面，我在这里对子控制视图的frame和menuView的frame做了计算和设置，可以在此修改。
话说为什么要加navigationController作为子控制器呢？是有特殊的需求？

**Comment by cnzlh** [comment]
恩，主要是想显示navigationController的Toolbar.
你有QQ吗？或者你加我QQ：20825520 。这样交流方便些，谢谢

**Comment by cnzlh** [comment]
感觉wangmchn.问题解决了
