### ISSUE TITLE
我可以单独的给选中的progress设置图片颜色吗？

### ISSUE THREAD

**Issue by 542604974** [wangmchn/WMPageController#395]
self.progressColor = [[UIColor alloc] initWithPatternImage:[UIImage imageNamed:@"MainController_pageVC_bottomline"]];

我发现这样设是设置了整条

**Comment by wangmchn** [comment]
你是指其中一个item的progressColor? 这个不行诶

**Comment by wangmchn** [comment]
或者试试在didEnter 或者 willEnter的时候设置
self.menuview.progressview.color = [[UIColor alloc] initWithPatternImage:[UIImage imageNamed:@"MainController_pageVC_bottomline"]].cgcolor;
[self.menuview.progressview setNeedsLayout]
看看这样能不能解决?

**Comment by 542604974** [comment]
我发现用那个方法会崩溃，UI又改了，可能不用改成图片颜色了
