### ISSUE TITLE
网易新闻样式

### ISSUE THREAD

**Issue by gongyua** [wangmchn/WMPageController#41]
新闻样式

**Comment by wangmchn** [comment]
@gongyua 
什么意思?

**Comment by XiMuYouZi** [comment]
正在使用这个导航栏，很好用。但是有个问题，我想每次滑动的时候可以更新下我的childViewController的内容，比如重新请求URL。我看到有个reload功能，是实现这种情况的吗？能给个范例吗？谢谢~~

**Comment by XiMuYouZi** [comment]
可能说的太复杂了，就是我想实现左右滑动的时候更新WMPageController这个类给添加进来的childViewController重新传值。可以实现么，谨请赐教

**Comment by XiMuYouZi** [comment]
正在使用这个导航栏，很好用，谢谢作者~
但是我遇到个问题：我从WMPageController这个类给childViewController传值，使用的是KVC，但是我想在左右滑动的时候更新这个传值。可以实现么，谨请赐教

**Comment by wangmchn** [comment]
可以的，在调用reload之前，对values和keys做更新，之后调用reload方法，就能更新传值。

**Comment by XiMuYouZi** [comment]
谢谢~
刚发现一个的问题，我的tableview第一行的cell和第二行以及第二行以下的cell的identifier是不同的，导致的问题就是第二行的cell的上面被覆盖了，被覆盖的高度刚好就是导航栏的高度。如果我所有的cell使用相同的identifier就不会出现这个问题。请问这是什么问题呢？

**Comment by wangmchn** [comment]
能给下截图或是demo吗？

**Comment by XiMuYouZi** [comment]
![1](https://cloud.githubusercontent.com/assets/12894809/11710955/182d6c46-9f5e-11e5-9ac5-fcd05579ead7.jpg)
红框部分~

**Comment by XiMuYouZi** [comment]
#import "ArticleSummarySliderNavigation.h"
#import "FetchArticleSummary.h"

@interface ArticleSummarySliderNavigation ()

@end

@implementation ArticleSummarySliderNavigation

- (instancetype)initWithCoder:(NSCoder *)aDecoder {
    self = [super initWithCoder:aDecoder];
    if (self) {
        NSArray *viewControllerClasses = @[[FetchArticleSummary class], [FetchArticleSummary class], [FetchArticleSummary class]];
        NSArray *titles = @[@"社会新闻", @"科技新闻", @"体育新闻"];
        self.viewControllerClasses = viewControllerClasses;
        self.titles = titles;
        self.titleColorSelected=[UIColor colorWithRed:240/255 green:248/255 blue:255/255 alpha:1.0];
        
        self.menuItemWidth = 60;
        self.menuViewStyle = WMMenuViewStyleLine;
        self.titleSizeSelected = 15.0;
        self.keys=@[@"theMagazineURL",@"theMagazineURL",@"theMagazineURL",];
        self.values= @[
                       [NSString stringWithFormat:@"http://apis.baidu.com/txapi/social/social?num=20&page=%d",arc4random()%10],
                       [NSString stringWithFormat:@"http://apis.baidu.com/txapi/keji/keji?num=20&page=%d",arc4random()%10],
                       [NSString stringWithFormat:@"http://apis.baidu.com/txapi/tiyu/tiyu?num=20&page=%d",arc4random()%10]];
        

    }
    return self;
}


@end
这是我设置KVC的地方，请问reload如何写呢？

**Comment by wangmchn** [comment]
晚点给你看，方便的话最好把demo发我email一下

**Comment by XiMuYouZi** [comment]
好的 ，你email多少

**Comment by wangmchn** [comment]
wangmchn@163.com

**Comment by XiMuYouZi** [comment]
好的，我整理下发给你，我这个是一个比较大的demo，我把这个页面分离出来发给你

**Comment by XiMuYouZi** [comment]
发送到你的邮箱了~

**Comment by wangmchn** [comment]
@XiMuYouZi 回你邮件了，是你上面的图片尺寸不对覆盖了下面的cell

**Comment by XiMuYouZi** [comment]
可是我所有的cell的identifier设置成一样的时候就不会出现这种问题啊

**Comment by wangmchn** [comment]
这个不太清楚，尝试在一个tableViewController中做你的逻辑（不用WMPageController）看看是否会被覆盖。

**Comment by XiMuYouZi** [comment]
好的 ，我尝试下，谢谢你~

**Comment by duanyicanyuan** [comment]
我是刚学iOS不到一年，用了你的WMPageController。我遇到一个问题，如何在WMPageController类中设定childViewController的属性的值呢？

**Comment by XiMuYouZi** [comment]
上面这位童靴看我贴的例子
关键是下面两句，使用KVC就可以了
我有三个相同的tableview作为childViewcontroller，他们都有有一个属性是theMagazineURL，我需要向这三个相同的页面的这个属性，传递三个不同的值，使用下面这个方法就可以了。
self.keys=@[@"theMagazineURL",@"theMagazineURL",@"theMagazineURL",];
self.values= @[
               [NSString stringWithFormat:@"http://apis.baidu.com/txapi/social/social?num=20&page=%d",arc4random()%10],
               [NSString stringWithFormat:@"http://apis.baidu.com/txapi/keji/keji?num=20&page=%d",arc4random()%10],
               [NSString stringWithFormat:@"http://apis.baidu.com/txapi/tiyu/tiyu?num=20&page=%d",arc4random()%10]];

**Comment by duanyicanyuan** [comment]
谢谢楼上这位善良的好心人

**Comment by XiMuYouZi** [comment]
不客气，我也是新手 ~~
