### ISSUE TITLE
如何实现向子控制器传值

### ISSUE THREAD

**Issue by duanyicanyuan** [wangmchn/WMPageController#43]
通过设置values和keys向子控制器传值。(内部利用KVC实现)

**Comment by wangmchn** [comment]
@duanyicanyuan 
具体可以参看`WMMainTableViewController`，第68、69行。
keys是子控制器属性的名字，比如`@property (nonatomic, copy) NSString *name;`
key 就是 `@"name"`
关于KVC具体可以Google百度一下。

**Comment by duanyicanyuan** [comment]
WMPageController *pageVC = [[WMPageController alloc] initWithViewControllerClasses:viewControllers andTheirTitles:titles];
// 初始化时给keys和values在这边赋值
    pageVC.keys = [NSArray arrayWithObjects:@"selectIndex", @"selectIndex", @"selectIndex", @"selectIndex", nil];
    pageVC.values = [NSArray arrayWithObjects: @"0", @"1", @"2", @"3", nil];
    pageVC.pageAnimatable = YES;
    pageVC.menuItemWidth = 85;
    pageVC.postNotification = YES;
    pageVC.bounces = YES;

// 自控制器，这样设置
@interface OrderDetailVC : UITableViewController

@property (nonatomic, copy)NSString *selectIndex;
@end


为什么会在WMPageController.m中
// 添加子控制器
- (void)addViewControllerAtIndex:(int)index {
    Class vcClass = self.viewControllerClasses[index];
    UIViewController *viewController = [[vcClass alloc] init];
    if (self.values.count == self.viewControllerClasses.count && self.keys.count == self.viewControllerClasses.count) {
//   会在下面这段代码崩溃
        [viewController setValue:self.values[index] forKey:self.keys[index]];
    }
    [self addChildViewController:viewController];
    viewController.view.frame = [self.childViewFrames[index] CGRectValue];
    [viewController didMoveToParentViewController:self];
    [self.scrollView addSubview:viewController.view];
    [self.displayVC setObject:viewController forKey:@(index)];
    [self backToPositionIfNeeded:viewController atIndex:index];
}

**Comment by wangmchn** [comment]
检查一下控制器个数是否和keys、values的数量相等？然后给一下报错信息？

**Comment by duanyicanyuan** [comment]
控制器个数和keys、values的个数相等的，都是4个，具体信息我都发你wangmchn@163.com邮箱了

**Comment by duanyicanyuan** [comment]
错误提示，也都发你邮箱了

**Comment by wangmchn** [comment]
你的子控制器叫 `OrderTableVc`，设置属性的控制器叫 `OrderDetailVc` ?

**Comment by duanyicanyuan** [comment]
是的，他继承了UITableViewController

**Comment by wangmchn** [comment]
子控制器和设置属性的控制器应该是同一个，不然就找不到对应属性了。

**Comment by duanyicanyuan** [comment]
抱歉，我类太多搞错了，这是我自己的问题。不过这个很谢谢你耐心的讲解。

**Comment by duanyicanyuan** [comment]
谢谢你，非常感谢！！！！
