### ISSUE TITLE
menuView的高度可以调整吗

### ISSUE THREAD

**Issue by JerryDJX** [wangmchn/WMPageController#432]
我是按着文档中的 init 创建的

> 
-(instancetype)init{
    if (self = [super init]) {
        self.titleSizeNormal = 16;
        self.titleSizeSelected = 16;
        self.menuViewStyle = WMMenuViewStyleLine;
        self.menuItemWidth = kIPMainViewW / 3;
        self.progressColor = kIPNavbgColor;
        self.progressWidth = 60;
        self.titleColorSelected = kIPNavbgColor;
    }
    return self;
}
>
现在我想设置menuView的高度，我查看了一些文章，以前有个属性是
self.menuHeight = 44; //导航栏高度

现在这个属性没了，我在 iOS11.2.1上高度少了将近20
我直接在 init 种加入
self.menuView.frame = CGRectMake(0,0, kIPMainViewW, 400);
压根没用
这个怎么改啊

**Comment by JerryDJX** [comment]
我在2.5.0版本的 WMPageController.m类中找到一个wm_calculateSize方法，然后直接在里面改了高度 这种思路可以吗

`- (void)wm_calculateSize {
    if ([self.dataSource respondsToSelector:@selector(pageController:preferredFrameForMenuView:)]) {
        _menuViewFrame = [self.dataSource pageController:self preferredFrameForMenuView:self.menuView];
    } else {
        CGFloat originY = (self.showOnNavigationBar && self.navigationController.navigationBar) ? 0 : CGRectGetMaxY(self.navigationController.navigationBar.frame);
        _menuViewFrame = CGRectMake(0, originY, self.view.frame.size.width, 50.0f);
    }
    if ([self.dataSource respondsToSelector:@selector(pageController:preferredFrameForContentView:)]) {
        _contentViewFrame = [self.dataSource pageController:self preferredFrameForContentView:self.scrollView];
    } else {
        CGFloat originY = (self.showOnNavigationBar && self.navigationController.navigationBar) ? CGRectGetMaxY(self.navigationController.navigationBar.frame) : CGRectGetMaxY(_menuViewFrame);
        CGFloat tabBarHeight = self.tabBarController.tabBar && !self.tabBarController.tabBar.hidden ? self.tabBarController.tabBar.frame.size.height : 0;
        CGFloat sizeHeight = self.view.frame.size.height - tabBarHeight - originY;
        _contentViewFrame = CGRectMake(0, originY, self.view.frame.size.width, sizeHeight);
    }
    _childViewFrames = [NSMutableArray array];
    for (int i = 0; i < self.childControllersCount; i++) {
        CGRect frame = CGRectMake(i * _contentViewFrame.size.width, 0, _contentViewFrame.size.width, _contentViewFrame.size.height);
        [_childViewFrames addObject:[NSValue valueWithCGRect:frame]];
    }`

把以前的30.0f 改成了50.0f

**Comment by JerryDJX** [comment]
我在2.5.0版本的 WMPageController.m类中找到一个wm_calculateSize方法，然后直接在里面改了高度 这种思路可以吗

> - (void)wm_calculateSize {
    if ([self.dataSource respondsToSelector:@selector(pageController:preferredFrameForMenuView:)]) {
        _menuViewFrame = [self.dataSource pageController:self preferredFrameForMenuView:self.menuView];
    } else {
        CGFloat originY = (self.showOnNavigationBar && self.navigationController.navigationBar) ? 0 : CGRectGetMaxY(self.navigationController.navigationBar.frame);
        _menuViewFrame = CGRectMake(0, originY, self.view.frame.size.width, 50.0f);
    }
    if ([self.dataSource respondsToSelector:@selector(pageController:preferredFrameForContentView:)]) {
        _contentViewFrame = [self.dataSource pageController:self preferredFrameForContentView:self.scrollView];
    } else {
        CGFloat originY = (self.showOnNavigationBar && self.navigationController.navigationBar) ? CGRectGetMaxY(self.navigationController.navigationBar.frame) : CGRectGetMaxY(_menuViewFrame);
        CGFloat tabBarHeight = self.tabBarController.tabBar && !self.tabBarController.tabBar.hidden ? self.tabBarController.tabBar.frame.size.height : 0;
        CGFloat sizeHeight = self.view.frame.size.height - tabBarHeight - originY;
        _contentViewFrame = CGRectMake(0, originY, self.view.frame.size.width, sizeHeight);
    }
    _childViewFrames = [NSMutableArray array];
    for (int i = 0; i < self.childControllersCount; i++) {
        CGRect frame = CGRectMake(i * _contentViewFrame.size.width, 0, _contentViewFrame.size.width, _contentViewFrame.size.height);
        [_childViewFrames addObject:[NSValue valueWithCGRect:frame]];
    }
把以前的30.0f 改成了50.0f

**Comment by wangmchn** [comment]
@JerryDJX 
https://github.com/wangmchn/WMPageController#customize-contents-frame
可以通过
```
- (CGRect)pageController:(WMPageController *)pageController preferredFrameForMenuView:(WMMenuView *)menuView;
```
这个数据源方法来自定义导航条的frame, 包括高度

**Comment by JerryDJX** [comment]
嗯嗯 好的  弄好了 谢谢哈

**Comment by JerryDJX** [comment]
可以通过这个方法进行设置
//设置 WMMenuView的 frame
-(CGRect)pageController:(WMPageController *)pageController preferredFrameForMenuView:(WMMenuView *)menuView{
   CGRect menuViewFrame = CGRectMake(0, 64, kIPMainViewW, 50.0);
   return menuViewFrame;
}




| |
Jerry·D
IT
|
|
1760066****
邮箱：canmeng10964@163.com
北京
120991****
勤勤恳恳做人 踏踏实实做事
|

签名由 网易邮箱大师 定制

在2018年01月04日 19:17，Wang Ming 写道：

Closed #432.
