### ISSUE TITLE
设置背景颜色后，顶部会出现一条黑线

### ISSUE THREAD

**Issue by LJYes** [wangmchn/WMPageController#444]
在StickyExample工程里的WMDetailViewController.m文件里，填写如下代码，顶部会出现一条黑色的线，怎么也去不掉，这个BUG改了两天了，今晚发版，急求帮助！
![image](https://user-images.githubusercontent.com/18663185/34552832-f30d7be0-f15e-11e7-8aeb-78f9d0a8c9e1.png)

@implementation WMDetailViewController

- (instancetype)init {
    if (self = [super init]) {
        self.titleSizeNormal = 15;
        self.titleSizeSelected = 15;
        self.menuViewStyle = WMMenuViewStyleFlood;
        self.menuViewLayoutMode = WMMenuViewLayoutModeScatter;
        self.menuItemWidth = [UIScreen mainScreen].bounds.size.width / self.musicCategories.count;
        self.titleColorSelected = [UIColor colorWithRed:0.5 green:0.5 blue:0.5 alpha:1.0];
        self.titleColorNormal = [UIColor whiteColor];
        self.progressColor = [UIColor colorWithRed:0.31 green:0.51 blue:1.0 alpha:1.0];
        self.progressViewCornerRadius = 5;
        self.postNotification = YES;
        
        
    }
    return self;
}

- (void)viewDidLoad {
    [super viewDidLoad];
    self.menuView.progressView.backgroundColor = [UIColor colorWithRed:0.75 green:0.89 blue:1.0 alpha:1.0];
}

**Comment by wangmchn** [comment]
你好，回复完了抱歉，没注意邮件

查了下是因为progress的高度是个浮点数导致的，uikit确实偶尔会出现这个问题

建议你先设置下self.progressHeight = 一个整数，我稍后再修复这个BUG

发自我的 iPhone

**Comment by LJYes** [comment]
谢谢你的及时回复，我会根据你的建议尝试修改
