### ISSUE TITLE
作者您好，如果titleArray过多，那岂不是加载很多的控制器，左右滑来滑去，上下滑来滑去，内存不就暴增吗

### ISSUE THREAD

**Issue by Hccong** [wangmchn/WMPageController#469]

**Comment by wangmchn** [comment]
WMPageController 有缓存策略，可以设置缓存控制器的数量，如果超出缓存限制会释放控制器的（内部使用NSCache作为缓存容器）
```
typedef NS_ENUM(NSInteger, WMPageControllerCachePolicy) {
    WMPageControllerCachePolicyDisabled   = -1,  // Disable Cache
    WMPageControllerCachePolicyNoLimit    = 0,   // No limit
    WMPageControllerCachePolicyLowMemory  = 1,   // Low Memory but may block when scroll
    WMPageControllerCachePolicyBalanced   = 3,   // Balanced ↑ and ↓
    WMPageControllerCachePolicyHigh       = 5    // High
};
```

**Comment by Hccong** [comment]
![image](https://user-images.githubusercontent.com/17471791/35425251-84dc704e-0294-11e8-83f2-e4c2e8891140.png)
我在childArray存放的控制器，如果按您说的释放的话，那岂不是我这个childArray里面的某个控制器就释放了？岂不是数据混乱了？怎么做？

**Comment by wangmchn** [comment]
@Hccong 你不需要childArray，在这里创建返回一个实例即可，内部会有管理策略的
如果用array强引用了那就没法释放了

**Comment by RtzX** [comment]
如果titlearray.count > 1000 或者更多 会有性能影响吗?看了好多这种组件.. 就是担心这个问题.. 
其中,每一个控制器里面都存在大量的数据..
