### ISSUE TITLE
滑动不触发didSelect代理方法

### ISSUE THREAD

**Issue by chengxianghe** [wangmchn/WMPageController#47]
有个页面是需要登录才能展示的, 但是滚动的时候代理并不会被触发,有什么好的解决办法么?

我目前是在viewWillAppear 里面判断,如果未登录就手动设置menu选中上个页面.

我想的是可否增加一个选项:
将要展示某个页面时,根据代理返回的bool值 决定是否展示.

**Comment by wangmchn** [comment]
能不能这样，未登录就整个不把这个控制器加入到WMPageController当中。
等到登陆了刷新WMPageController，再加入指定控制器

**Comment by chengxianghe** [comment]
@wangmchn 这样可能不行。
首先，这个就是两个页面：一个是“热门群组”，一个是“我的群组”，而我的群组是必须要登录才能展示的。
如果说未登录就不展示“我的群组”，那就是说在这个页面无法触发登录事件，那么用户看不了“我的群组”（只能等待别的地方触发登录事件登录成功）。这样做产品首先会不同意的吧···

其实简单的来说，未登录在“我的群组”页面展示“去登录”这样的提示也是可以的，可是这个产品不同意···所以我才提出这个问题的。

只是建议一下，如果可能的话，最好不管是滑动还是手动点击，都应该触发didSelect这样的方法，我觉得这样可能处理很多事件方便点。另外willSelect如果能加进去应该使用起来也会更灵活。

**Comment by wangmchn** [comment]
不是特别明白你的意思，就是未登录时，我的群组也要存在，但是这个时候不能滑动和点击？？

**Comment by chengxianghe** [comment]
未登录时， 标题栏上有“我的群组” 点击我的群组判断用户是否登录，如果登录网络请求数据展示我的群组，如果未登录，弹窗提示用户去登录，登录完成后再请求数据展示

**Comment by wangmchn** [comment]
viewWillAppear不能满足需求么？先判断是否登陆，如果登录网络请求数据展示我的群组，如果未登录，弹窗提示用户去登录，登录完成后再请求数据展示？也不需要手动设置选中上一个页面啊，直接弹窗提示用户去登录不行么？还是说产品有特殊的想法？

**Comment by wangmchn** [comment]
大概明白你的意思了
意思就是如果未登录的话，要拦截展示我的群组控制器，然后先提示去登陆对不？(未登录时一滚动就弹窗提示用户去登录，然后页面一直保持在 热门群组 ？)
话说这样的需求我觉得不要滑动会比较好吧= =
但是你又说到：`如果说未登录就不展示“我的群组”，那就是说在这个页面无法触发登录事件，那么用户看不了“我的群组”` 
也就是说你的登陆事件只有在我的群组控制器才能触发？这样即使触发了didSelect也是一样的吧。
didSelect和子控制器的viewWillAppear应该是一样的才对

**Comment by chengxianghe** [comment]
多谢你的解答,不过现在我已经说服产品了,展示空页面给用户一个"去登录"的按钮,这样终于不用改太多了......
不过我还是觉得能提供一个willSelect的方法会更完美一些.如果有时间,我会尝试添加一下~

**Comment by wangmchn** [comment]
不过每当要选中一个tab页的时候都是会发送一个通知的
期待你的pr~
