### ISSUE TITLE
if you wanna set wmmenuview as titleview,you should add this

### ISSUE THREAD

**Issue by oam87** [wangmchn/WMPageController#49]
i wanna set wmmenuview as titleview,but i notice that if you push to another viewcontroller,after pull back,the wmmenuview will increase more subviews.

i check the thread stack finded that the reason is when push viewcontroller,the parent controller will call "willMoveToSuperview" again,so the wmmenuview will add new items,but obversely you dont want that happen.

so a simple way to fix the problem is to add a bool variable and add a if control,like below:

- (void)willMoveToSuperview:(UIView *)newSuperview {
    if(!self.isload){
        self.isload=true;
        [self addScrollView];
        [self addItems];
        [self makeStyle];
    }
}

works fine on me.hope will help somebody

**Comment by wangmchn** [comment]
Mmmmm..I have add a if control before, did it not work for you ?
```objective-c
- (void)willMoveToSuperview:(UIView *)newSuperview {
    if (self.scrollView) { return; }
    
    [self addScrollView];
    [self addItems];
    [self makeStyle];
}
```
