### ISSUE TITLE
能否实现预加载左右n页的功能呢？

### ISSUE THREAD

**Issue by chx632996066** [wangmchn/WMPageController#54]
子控制器界面内容较多时，第一次滑动过去的时候会停顿一下，当子控制器加载完毕后就左右滑动得很流畅了，所以我想问一下，能否实现预加载左右n页的功能，然后左右滑动的时候就流畅滑动无停顿

**Comment by wangmchn** [comment]
不错的提议，会接下来添加该功能

**Comment by dadadong** [comment]
不好意思 ，借楼提一个相关的问题， 在子控制器页面内容过多的时候 ，第一次快速横向滑动，一方面就像楼主所言 会卡顿， 另一方面，上面的栏位 会出现多个选中的现象 ，就是多个标签处于 放大的状态， 我目前采取的措施是：在标签居中 的时候， 取消选择 除当前 的其它item 。我觉得有更好的方案，请赐教

**Comment by wangmchn** [comment]
@dadadong  请问下多个选中是什么情况，能详细说明一下吗？是只有页面内容多的时候会引起还是？

**Comment by dadadong** [comment]
不好意思 ，回复的晚了， 是这样的 ，我用的 WMMenuViewStyleDefault ，item选中 处于放大状态。
正常状况 ：item选中状态下，item的CGAffineTransformMakeScale 会处于放大状态， 反之 item 恢复到 正常大小；
然后我看到你的代码 是在 WMPageController 中的 scrollViewDidScroll 中调用 [self.menuView slideMenuAtProgress:rate] 更新 item 的 transform ,但是在 子控制器过于复杂的时候 ，快速横向滑动 由于出现卡顿 造成 scrollViewDidScroll这个函数会少掉很多次 ，以至于 一些 item 未恢复到 默认大小，就出现了 WMMenuView 中 多个 item 处于 Scale 大于1的状态。

**Comment by wangmchn** [comment]
添加了一个预加载机制了，可以试试了

**Comment by chx632996066** [comment]
大赞！非常感谢！
