### ISSUE TITLE
 - WMMenuView Delegate 这里是不是笔误

### ISSUE THREAD

**Issue by dadadong** [wangmchn/WMPageController#56]
- (void)menuView:(WMMenuView *)menu didSelesctedIndex:(NSInteger)index currentIndex:(NSInteger)currentIndex {
    NSInteger gap = (NSInteger)labs(index - currentIndex);
    _selectIndex = (int)index;
    _animate = NO;
    CGPoint targetP = CGPointMake(_viewWidth*index, 0);
    
    [self.scrollView setContentOffset:targetP animated:gap > 1 ? NO : self.pageAnimatable];
    if (gap > 1 || !self.pageAnimatable) {
        // 由于不触发 -scrollViewDidScroll: 手动处理控制器
        UIViewController *currentViewController = self.displayVC[@(currentIndex)];
        // 最好判断一下，因为在做某个项目时，currentViewController = nil
        if (currentViewController) {
            [self removeViewController:currentViewController atIndex:currentIndex];
        }
        [self layoutChildViewControllers];
        self.currentViewController = self.displayVC[@(self.selectIndex)];
        [self postFullyDisplayedNotificationWithCurrentIndex:(int)index];

**#pragma mark - 这里 是不是应该是 index 而不是  currentIndex**
        [self didEnterController:self.currentViewController atIndex: **currentIndex**];

    }

**Comment by wangmchn** [comment]
是笔误，抱歉！
