### ISSUE TITLE
顶部的view有办法添加下拉刷新吗

### ISSUE THREAD

**Issue by miniLV** [wangmchn/WMPageController#567]
WMStickyPageController 的 self.View 有办法 添加MJRefresh控件吗

**Comment by miniLV** [comment]
修改私有属性 ，将contentView放在.h文件，在WMStickyPageController中，用self.contentView 代替 self.view(UIView) 使用，可以添加 MJRefresh 控件

**Comment by lsysun1** [comment]
> 修改私有属性 ，将contentView放在.h文件，在WMStickyPageController中，用self.contentView 代替 self.view(UIView) 使用，可以添加 MJRefresh 控件

我已经修改了，但是添加MJRefresh后下拉还是没有反应。

    MJRefreshStateHeader *stateHeader = [MJRefreshStateHeader headerWithRefreshingTarget:self refreshingAction:@selector(loadNewData)];
    [stateHeader setTitle:@"" forState:MJRefreshStateIdle];
    self.contentView.mj_header = stateHeader;

我是直接继承的WMStickyPageController，将
@property(nonatomic, strong) WMMagicScrollView *contentView;
直接放在WMStickyPageViewController.h里面了。

你是怎么处理的哦。
