### ISSUE TITLE
可以给标题的label增加Badge功能吗？目前是没有的

### ISSUE THREAD

**Issue by VVJason** [wangmchn/WMPageController#57]
类似这样的，目前好像是没有的
![snip20160216_10](https://cloud.githubusercontent.com/assets/14148888/13072014/07f03986-d4d2-11e5-89bc-93a4b11c13db.png)

**Comment by wangmchn** [comment]
会后续添加该功能 ：）

**Comment by VVJason** [comment]
自己加了，回头pr给你吧
