### ISSUE TITLE
改变数据后，调用reloadData，几率性出现白屏

### ISSUE THREAD

**Issue by yorkwang** [wangmchn/WMPageController#58]
就是reload后，view显示不了。盲点view里面button，跳转到另一个界面，再返回，才能显示。说明view加载了，就是显示不了

**Comment by dadadong** [comment]
这个我也遇到了 ，断点看到 白屏的viewCtl的 viewwilllappear 等生命周期函数没掉，

**Comment by wangmchn** [comment]
这个挺奇怪的 
用的数据源还是initWithxxx那个方法？是否有将PageController作为视图添加到了某个控制器的视图上？
我排查一下

**Comment by yorkwang** [comment]
没有用initWithxxx， 用的datasource 的方法。我的使用场景是：从WMPageController跳转到另一个view controller B，然后在view controller B做修改。关闭B，同时调用WMPageController 的reloaddata，回到WMPageController，就会几率性白屏。如果关闭B后，在WMPageController 的 viewwillappear中调用reloaddata，就不会白屏。

**Comment by wangmchn** [comment]
今天修复了一下，有空试试看是否好了= =

**Comment by xilin** [comment]
我这正好遇到reload的情况，测试用了新版OK了。

**Comment by wangmchn** [comment]
@xilin 非常感谢! 👍
