### ISSUE TITLE
更新小红点崩溃

### ISSUE THREAD

**Issue by jackliuheh** [wangmchn/WMPageController#580]
无小红点到有小红点，或者有小红点到更新没有小红点，如果是初始化是没有问题的
 [self.menuView updateBadgeViewAtIndex:1];
崩溃到 setframe 获取到数值无穷大，

**Comment by jackliuheh** [comment]
- (UIView *)menuView:(WMMenuView *)menu badgeViewAtIndex:(NSInteger)index{
    
    switch (index) {
        case 0:
        {
            return nil;
            
            break;
        }
            
            
        case 1:
        {
            if (!_showRedPoint) {

                return nil;
                break;

            }
            UIView *red = [[UIView alloc]initWithFrame:CGRectMake(_itemX, 16.5, 6, 6)];
            red.backgroundColor = [UIColor redColor];
            red.layer.masksToBounds = YES;
            red.layer.cornerRadius = 3.0f;
            return red;
            
            break;
        }
            
            
        default:
            return nil;
            break;
    }

}

**Comment by jackliuheh** [comment]
![348716b1-1a6e-4287-bb06-153a706f201a](https://user-images.githubusercontent.com/29977146/50206621-e56b9c00-03a6-11e9-8d49-3f6341051467.png)
![5e4c67a3-8ece-4608-923a-122f6c4ee5c8](https://user-images.githubusercontent.com/29977146/50206632-f0263100-03a6-11e9-89ec-6f86575b4c64.png)

**Comment by jackliuheh** [comment]
已弃用这个方法

**Comment by chenZai90** [comment]
你好，我用这个方法实现了小红点提醒。但是当我查看了消息之后应该怎么把这个小红点去除呢 ？我应该用哪一个方法呢？
