### ISSUE TITLE
Hello，想要 UICollectionView 和 WMPageViewController 存在于一个页面中，我遇到了一些麻烦 ...

### ISSUE THREAD

**Issue by bruceWangDev** [wangmchn/WMPageController#597]
<img width="1440" alt="国际机票城市选择页面设计" src="https://user-images.githubusercontent.com/12932651/55395172-a0453180-5573-11e9-8282-704d3444d5e5.png">

emmm，我的设想是在一个 VC 上添加一个 UIScrollView，UIScrollView 上面先添加 UICollectionView ，然后在 UICollectionView 下面添加 WMPageViewController。

但是我看了您的文档，我发现 WMPageViewController 的创建方式只能是继承。那么问题来了，我在 WMPageViewController.view 上添加 UIScrollView，并且在 UIScrollView 上添加 UICollectionView，接下来我要如何把 WMPageViewController.view 的内容添加到 UIScrollView 上呢？
或者说，我如何让 WMPageViewController.view 包含一个 UICollectionView + pageViewController，让它先可以上下滑动，也可以左右滑动 .. 
<img width="255" alt="WX20190402-182307@2x" src="https://user-images.githubusercontent.com/12932651/55395580-66285f80-5574-11e9-9107-c7f0a773c0d8.png">
我完成了大部分，但是整个页面还是无法上下滑动，想要一个 idea .. 
感谢！

**Comment by Charlin0701** [comment]
你可以使用WMStickyPageController，将你上部分的整体信息写成自定义的 headerView 试试
