### ISSUE TITLE
如果是view Controllers之一是 UITableview Controller

### ISSUE THREAD

**Issue by dengzhp** [wangmchn/WMPageController#64]
能保留左滑删除手势么？

**Comment by wangmchn** [comment]
能

**Comment by dengzhp** [comment]
我试了 otherGestureRecognizerSimultaneously = YES 也不行哦

**Comment by dengzhp** [comment]
确实可以，不过会冲突，比较难触发。

**Comment by wangmchn** [comment]
做了些调整，试试看现在是否ok

**Comment by dengzhp** [comment]
试了，现在优先是cell的左滑操作 ， scollview的滑动就变得很难触发了。
建议加上这个选项的otherGestureRecognizerSimultaneously判断，
这样用户想要保留tableview的左滑，就开启otherGestureRecognizerSimultaneously，不然就默认scollView的滑动。  如何？

**Comment by wangmchn** [comment]
那是要同时能够触发cell左滑和scrollView滑动吗？ 现在是能够左划删除的cell无法触发scrollView滑动，无法左划删除的cell能够触发scrollView滑动，我觉得还挺合理的？

**Comment by dengzhp** [comment]
恩，还算合理。
不过我这边情况是因为之前比较难触发cell左滑，我加上了长按手势，所以cell左滑就不必要了，但也保留，这种情况我希望 滑动还是优先 scrollView。但这个commit后，就不行了。所以我希望可以判断选项otherGestureRecognizerSimultaneously。

**Comment by wangmchn** [comment]
要不然你Fork一份手动改下源码？ 因为我觉得现在会比较满足大部分情况哈
