### ISSUE TITLE
滑动切换子视图的时候selectIndex不准确,无法根据这个刷新数据

### ISSUE THREAD

**Issue by chengyinglpl** [wangmchn/WMPageController#65]

**Comment by wangmchn** [comment]
试试看这个代理：`- (void)pageController:(WMPageController *)pageController willEnterViewController:(__kindof UIViewController *)viewController withInfo:(NSDictionary *)info` 或者监听下notification
info里面包含序号信息，selectIndex好像是有点问题，我看看修复下
