### ISSUE TITLE
问题太多还是放弃在项目中使用了

### ISSUE THREAD

**Issue by VVJason** [wangmchn/WMPageController#66]
容器控制器的view竟然不是从顶部开始的，从导航栏开始的，，，一般的需求可能可以用，很多问题没法满足项目的需求，还是老实的自己写吧
![25206af4356adeb98be3821cc3117387](https://cloud.githubusercontent.com/assets/14148888/13546527/7299500c-e2eb-11e5-80b1-938d361f4ef9.png)

**Comment by wangmchn** [comment]
嗯 是这样的
