### ISSUE TITLE
一个常见的使用场景 问题

### ISSUE THREAD

**Issue by dadadong** [wangmchn/WMPageController#67]
- (void)addMenuView {
    CGRect frame = CGRectMake(_viewX, _viewY, _viewWidth, self.menuHeight);
    WMMenuView *menuView = [[WMMenuView alloc] initWithFrame:frame];
    menuView.backgroundColor = self.menuBGColor;
    menuView.delegate = self;
    menuView.dataSource = self;
    menuView.style = self.menuViewStyle;
    menuView.progressHeight = self.progressHeight;
    if (self.titleFontName) {
        menuView.fontName = self.titleFontName;
    }
    if (self.progressColor) {
        menuView.lineColor = self.progressColor;
    }
    if (self.showOnNavigationBar && self.navigationController.navigationBar) {
        self.navigationItem.titleView = menuView;
    } else {
        [self.view addSubview:menuView];
    }
    self.menuView = menuView;
    // 如果设置了初始选择的序号，那么选中该item
    if (self.selectIndex != 0) {

**       ** // 这里有个使用场景 ，如果我是在从WMVC -push出来的一个vc里面 做了栏位的编辑 ，然后调用了WMVC的        -reloadDate 方法，
        // 这里的 序号设置会失效， 原因是- (void)willMoveToSuperview:(UIView *)newSuperview ；方法在 页面出现的时候  才会调用， 此时menuView的子items 还未创建****

        [self.menuView selectItemAtIndex:self.selectIndex];
    }
}

**Comment by wangmchn** [comment]
最新的还有这个问题么？我刚试了试可以正常选中？

**Comment by dadadong** [comment]
还有这个问题的，
我是调用完 reloadDate后 在pop回来的，
 reloadDate内部会重置menuView , 新的menuVIew在 willMoveToSuperview 才会addItems ，而willMoveToSuperview在pop后才会调用 ，
 调用 reloadDate 里的 restMenuVIew里  [self.menuView selectItemAtIndex:self.selectIndex]; 时，items还未创建
建议 在 [self.menuView selectItemAtIndex:self.selectIndex]; 这个方法的实现内部 手动调用一次willMoveToSuperview 方法， 防止menuView内部未实例化

**Comment by dadadong** [comment]
![2016-03-08 11 36 29](https://cloud.githubusercontent.com/assets/13832911/13591283/0f2e0b32-e522-11e5-9ccc-9dd2230ca031.png)
另外这个问题 还是存在

**Comment by wangmchn** [comment]
:hankey:  
我看看- -

**Comment by dadadong** [comment]
快速滑动 造成多选中的问题 ，我在   - (void)refreshContenOffset；里加入了下面的代码，
  [self.scrollView.subviews enumerateObjectsUsingBlock:^(__kindof UIView * _Nonnull obj, NSUInteger idx, BOOL * _Nonnull stop) {
            if ([obj isKindOfClass:[WMMenuItem class]]) {
                WMMenuItem *tempItem = (WMMenuItem *)obj;
                if (tempItem != self.selItem) {
                    [tempItem deselectedItemWithoutAnimation];
                }
            }
        }];
