### ISSUE TITLE
如何从Storyboard中加载ViewController，重写init----（Swift）

### ISSUE THREAD

**Issue by smileat** [wangmchn/WMPageController#68]
我看了ob的版本，如果要从sb或者xib中加载视图，需要重写视图的init，那么在Swift中，我的视图是在sb中的，那么应该要怎么重写视图的init？，我尝试了很久，依然没成功，希望您能帮我解答，万分感谢。

**Comment by wangmchn** [comment]
@smileat  
Swift 版本里面有个Example文件夹，你可以参看一下Use Storyboard那个demo
回复晚了抱歉
