### ISSUE TITLE
每次滑动已经加载的controller重新新建

### ISSUE THREAD

**Issue by CODE4APPLE** [wangmchn/WMPageController#7]
可以考虑一下缓存之类的,让已经加载的controller重用之类.
看好多新闻类的app都好像缓存了一样.
要是能做到这个,那就是真正好用的轮子了

**Comment by wangmchn** [comment]
嗯是的，正在做这方面的工作~

**Comment by wangmchn** [comment]
已经添加了一个缓存机制，可以使用看看了，有什么值得改进的还望提出：）
