### ISSUE TITLE
隐藏导航栏，会发现menuView 被 状态栏遮住。这个体验不是很好。

### ISSUE THREAD

**Issue by JeeLiu** [wangmchn/WMPageController#70]
隐藏导航栏，会发现menuView 被 状态栏遮住。这个体验不是很好。如果能不遮住就很好看了，尝试很多方法，并没有解决。如果添加一个view height＝20 的话，似乎太繁琐了。

**Comment by mrxiaobin** [comment]
iOS7以后，导航栏本来就是从0开始算起的吧，所以应该是正常现象了，这个感觉应该是要自己代码里调整的

**Comment by mrxiaobin** [comment]
@JeeLiu iOS7以后，导航栏本来就是从0开始算起的吧，所以应该是正常现象了，这个感觉应该是要自己代码里调整的
