### ISSUE TITLE
如何使用WMPageController的KVC给里面的控制器传值

### ISSUE THREAD

**Issue by BlackRainism** [wangmchn/WMPageController#73]
因为我外层是一个tableview，点击其中的一个cell，我要传值给推出的WMPageController里面的ViewControllers，如何使用KVC给ViewControllers传值，能教教我吗，小白求教

**Comment by wangmchn** [comment]
现在有两种方式可以传值：
方式一是利用kvc，WMPageController 有两个属性，一个叫 values，一个叫 keys.
可通过设置这两个属性来传递数据，比如，你第一个子控制器有属性 name，第二个有属性 age，那么你可以通过一下方式传递name和age的值：
在初始化的时候，设置
pageController.values = @[@"Mark",@22]
pageController.keys = @[@"name",@"age"]
并注意一下几点：
1.keys的值必须和控制器属性名字相同
2.keys和values个数需与控制器个数相同，顺序一一对应，若中间有控制器不需要传值，请设置空的属性来接受

方式二是通过datasource来创建子控制器，这个具体可以参见Pass Value那个demo，里面给了一个基础的例子，这个没在ReadMe中写明，不好意思。
推荐使用datasource，更加灵活~

**Comment by BlackRainism** [comment]
谢谢您百忙之中回答我，已经很好了.是我比较笨.嘿嘿


发自 网易邮箱大师
在2016年03月28日 23:23，Wang Ming 写道:

现在有两种方式可以传值：
方式一是利用kvc，WMPageController 有两个属性，一个叫 values，一个叫 keys.
可通过设置这两个属性来传递数据，比如，你第一个子控制器有属性 name，第二个有属性 age，那么你可以通过一下方式传递name和age的值：
在初始化的时候，设置
pageController.values = @[@"Mark",@22]
pageController.keys = @[@"name",@"age"]
并注意一下几点：
1.keys的值必须和控制器属性名字相同
2.keys和values个数需与控制器个数相同，顺序一一对应，若中间有控制器不需要传值，请设置空的属性来接受

方式二是通过datasource来创建子控制器，这个具体可以参见Pass Value那个demo，里面给了一个基础的例子，这个没在ReadMe中写明，不好意思。
推荐使用datasource，更加灵活~
