### ISSUE TITLE
去掉itemwidth小于屏幕宽度，为item间添加间距的功能

### ISSUE THREAD

**Issue by bamaocc** [wangmchn/WMPageController#74]
wmmenuview.m  261行
  if (contentWidth < self.frame.size.width) {
        // 计算间距
//        CGFloat distance = self.frame.size.width - contentWidth;
//        CGFloat gap = distance / (self.titlesCount + 1);
//        for (int i = 0; i < self.frames.count; i++) {
//            CGRect frame = [self.frames[i] CGRectValue];
//            frame.origin.x += gap * (i+1);
//            self.frames[i] = [NSValue valueWithCGRect:frame];
//        }
//        contentWidth = self.frame.size.width;
		self.scrollView.frame = CGRectMake((self.frame.size.width - contentWidth) / 2, 0, contentWidth, self.frame.size.height);
    }
这样修改会不会有引起什么错误？

**Comment by wangmchn** [comment]
应该是不会的
