### ISSUE TITLE
showOnNavigationBar只有两个item时 间距怎么调小？

### ISSUE THREAD

**Issue by LiweiDong** [wangmchn/WMPageController#75]
showOnNavigationBar只有两个item时 间距怎么调小？
 
![1](https://cloud.githubusercontent.com/assets/1669848/14201547/40cf4cb2-f825-11e5-9bbb-5c91153fd128.png)

**Comment by wangmchn** [comment]
可以通过调 **itemsMargins** 这个属性
![untitled](https://cloud.githubusercontent.com/assets/9441848/14202063/76e152b6-f828-11e5-8584-c7dfb958b5df.png)

**Comment by LiweiDong** [comment]
self.itemsMargins = @[@(30),@(1),@(30)];
self.itemsWidths = @[@(50),@(50)];

感谢，已解决
