### ISSUE TITLE
问个小白问题..

### ISSUE THREAD

**Issue by XQBoy** [wangmchn/WMPageController#8]
如果我想要在程序启动后就显示这种界面，而不是通过导航控制器push过去，要怎么做呢，小白求教

**Comment by wangmchn** [comment]
在AppDelegate里的- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions方法中使用如下代码：
 WMPageController *pageController = [[WMPageController alloc] initWithViewControllerClasses:xxx titles:xxx];
self.window.rootViewController = pageController;
如果想要有导航栏，那么创建UINavigationController，并把pageController添加为rootViewController即可，具体如下：
UINavigationController *nav =  [[UINavigationController alloc] initRootViewController:pageController];
self.window.rootViewController = nav;

**Comment by XQBoy** [comment]
这个我知道，那这样的话AppDelegate里面就要写很长代码了，封装性不好。试着继承自WMPageController,然后再里面添加子控制器等，但是总报错在这一行， [self addChildViewController:viewController];

**Comment by wangmchn** [comment]
不太明白你添加子控制的目的，其实WMPageController和系统的UITabbarController有相似之处，都是用来管理其他的控制器的，对于内部的要显示的子控制器，已经用 `- initWithViewControllerClasses: titles:`这个方法封装好了，所以能再详细说下你的目的吗？

**Comment by wangmchn** [comment]
如果觉得代码过长，可以尝试通过创建一个 `Model` 类专门用来提供 `viewControllerClasses` 和 `titles`, 以此来封装一些代码。

**Comment by XQBoy** [comment]
比如说，我要在程序打开之后就显示WMPageController的默认形式，里面有个tableViewController跟viewController,纯代码形式。然而我在AppDelegate的didFinishLaunchingWithOptions方法中只需要self.window.rootViewController=WMPageController,具体WMPageController我不在didFinishLaunchingWithOptions方法中体现。

**Comment by wangmchn** [comment]
因为这只是一个封装好的小轮子，之所以要这么多代码是为了降低耦合性。
想要得到你那种效果建议你重写 `WMPageController` 的 `init` 方法,在 `int` 中对 `self.titles` 和 `self.viewControllerClasses` 进行赋值。
然后创建的时候直接用`init`创建即可。

**Comment by XQBoy** [comment]
重写init方法实现了！赞!

**Comment by wangmchn** [comment]
：）

**Comment by XQBoy** [comment]
请问下现在这个加了缓存么，控制器是否可以重用？

**Comment by wangmchn** [comment]
最新版本对于加载过的`viewController`是有缓存的，但并不是重用（因为每个控制器都是独立的），加载过一次的`viewController`再次进入不会调用`viewDidLoad`方法，但会调用`viewWillAppear`

**Comment by wangmchn** [comment]
有一点需要注意，当收到内存警告时，或者viewController过多，之前的控制器有可能会被释放而重新创建。

**Comment by XQBoy** [comment]
好的，多谢
