### ISSUE TITLE
我想用swift语法 集成OC版的WMPageController

### ISSUE THREAD

**Issue by Brances** [wangmchn/WMPageController#80]
希望作者能出一套关于在swift中如何使用OC版的WMPageController,万分感谢. 我的QQ 292692700 我想请教您问题.

**Comment by wangmchn** [comment]
可以用 Swift 版本的

**Comment by Brances** [comment]
swift版木有使用教程. @wangmchn

**Comment by wangmchn** [comment]
swift接口和oc完全一样的

发自我的 iPhone

**Comment by xnth97** [comment]
需要kvo的属性添加@objc关键字 别的照着写就行了
