### ISSUE TITLE
一处笔误

### ISSUE THREAD

**Issue by dadadong** [wangmchn/WMPageController#82]
#pragma mark - WMMenuView Delegate
- (void)menuView:(WMMenuView *)menu didSelesctedIndex:(NSInteger)index currentIndex:(NSInteger)currentIndex {

    if (!_hasInited) { return; }
    _selectIndex = (int)index;
    _startDragging = NO;
    CGPoint targetP = CGPointMake(_viewWidth*index, 0);
    [self.scrollView setContentOffset:targetP animated:self.pageAnimatable];

** // 应该 是 （！self.pageAnimatable）**
    if (self.pageAnimatable) {    

        // 由于不触发 -scrollViewDidScroll: 手动处理控制器
        [self removeSuperfluousViewControllersIfNeeded];
        UIViewController *currentViewController = self.displayVC[@(currentIndex)];
        if (currentViewController) {
            [self removeViewController:currentViewController atIndex:currentIndex];
        }
        [self layoutChildViewControllers];
        self.currentViewController = self.displayVC[@(self.selectIndex)];
        [self postFullyDisplayedNotificationWithCurrentIndex:(int)index];
        [self didEnterController:self.currentViewController atIndex:index];
    }
}

**Comment by wangmchn** [comment]
唔，非常感谢~
