### ISSUE TITLE
一个小问题

### ISSUE THREAD

**Issue by dadadong** [wangmchn/WMPageController#83]
使用 dataSource代理， 很有可能在- viewDidLoad时，dataSourceCount = 0 ，这样的话 menuVIew则不会创建；

- (void)resetMenuView {
// 这里是否 判断一下 menuVIew是否存在 会更好些
        [self.menuView reload];

    if (self.selectIndex != 0) {
        [self.menuView selectItemAtIndex:self.selectIndex];
    }
}

**Comment by wangmchn** [comment]
嗯 确实是这样~thx

**Comment by dadadong** [comment]
// 包括宽高，子控制器视图 frame
- (void)calculateSize {
    CGFloat navigationHeight = CGRectGetMaxY(self.navigationController.navigationBar.frame);

#pragma mark -  navigationBarHiden时，navigationHeight = -20   ,下面判断 我加了个条件 不知道符合不符合你的原意，

    if (self.edgesForExtendedLayout == UIRectEdgeNone || navigationHeight <= 0) {
        navigationHeight = 0;
    }

**Comment by wangmchn** [comment]
嗯 感觉上还是不限制比较好 考虑到有可能会有这种需求

**Comment by dadadong** [comment]
好的 ，这是小地方，可以个人根据需求修改，
我还有个地方不太明白，预加载的时候，为什么不 直接实例化然后放进 cache中呢？
- addViewControllerAtIndex:i ； 这个方法实例化 会使childVC的生命周期函数(viewWillAppear ,viewDidAppear） 提前调用，

**Comment by wangmchn** [comment]
这边主要是参照了网易新闻的做法 网易新闻也是这样的

**Comment by wangmchn** [comment]
然后的话，考虑到预加载主要是为了防止滑动的卡顿，提前渲染图形能够减少一些滑动的阻塞吧，个人感觉这样提前add也是比较合理的

**Comment by dadadong** [comment]
好吧， 我还是觉得 最好能保证childVC的生命周期正常好些~~！
另外 这里有点小问题，

**Comment by dadadong** [comment]
- (void)setLeftView:(UIView *)leftView {
//  leftView之前不为空，但是在此设为 nil的时候 ，无限递归了。。
    if (self.leftView) {
        [self.leftView removeFromSuperview];
        self.leftView = nil;    //该是  _leftView = nil;
    }
    [self addSubview:leftView];
    _leftView = leftView;
    
    [self resetFrames];
}

**Comment by wangmchn** [comment]
非常感谢🙏 我回去就修改下

发自我的 iPhone
