### ISSUE TITLE
我想问如果Item有好多会卡吗?

### ISSUE THREAD

**Issue by Kratos28** [wangmchn/WMPageController#84]
我想问如果Item有好多会卡吗? 如果我有25ITem,前面没有用到的ViewController会被释放吗? 这个有重用的吗?

**Comment by wangmchn** [comment]
会释放的

**Comment by Kratos28** [comment]
![Uploading QQ20160427-0.png…]()
有自动适应文字宽度的功能的吗？

**Comment by Kratos28** [comment]
![qq20160427-0](https://cloud.githubusercontent.com/assets/8486246/14843686/f140f032-0c84-11e6-8775-d65bdae0647c.png)

**Comment by wangmchn** [comment]
暂时没有 需设置itemWidth / itemswidths属性
