### ISSUE TITLE
最新的代码顶部会有64像素的空白

### ISSUE THREAD

**Issue by Chren** [wangmchn/WMPageController#87]
检查代码发现是因为self.view的frame顶部已经从64开始了，计算menuView的frame时又从64开始，
导致menuView实际绝对坐标从128开始了。。

**Comment by wangmchn** [comment]
是的，因为假期改了下代码 改出了点问题 我下午修复下

可以先尝试设置WMPageController的edgesForExtendedLayout = none 

发自我的 iPhone

**Comment by wangmchn** [comment]
刚做了修改，尝试下最新代码看看问题还是否存在？:smile:

**Comment by lhy6962** [comment]
我这边是TabbarController和NavigationController嵌套 顶部会有空白 而且内容显示不出来 只有menu

**Comment by wangmchn** [comment]
@lhy6962 
设置WMPageController的edgesForExtendedLayout = none 这样也没用吗？
能详细说下你是怎么设置的吗？

**Comment by Chren** [comment]
最新的代码试过 可以了

**Comment by lhy6962** [comment]
WMPageController.m  710行
if ((_hasInited && _superviewHeight == oldSuperviewHeight) || !self.view.window) return;
这句的self.view.window获取到的是nil 导致后面的代码都没执行
我暂时先把window的那个判断取消了
