### ISSUE TITLE
如果是同一个 ViewController,怎么显示不同的数据

### ISSUE THREAD

**Issue by kaven85** [wangmchn/WMPageController#89]
在 VC 里通过 type 参数去区分不同的数据获取。但我在你的 demo 里，看到的是设置pageController的 key 和 value，但这是对所有的 VC 都起效的。如何做到一个 VC 的重用？

**Comment by wangmchn** [comment]
举个例子，假如你只有一个控制器，叫做 WMViewController，且内有一个属性 type（通过 type 参数去区分不同的数据获取）。
那么根据你初始化的方式，有两种方法来设置 type：
1.假如通过 datasource 来提供实例，那么在数据源方法中, 可以做类似下面的设置：
```
- (UIViewController *)pageController:(WMPageController *)pageController viewControllerAtIndex:(NSInteger)index {
     WMViewController *vc = [[WMViewController alloc] init];
     vc.type = index;
     return vc;
}
```
2.假如通过构造方法创建：
```
- (instancetype)initWithViewControllerClasses:(NSArray<Class> *)classes andTheirTitles:(NSArray<NSString *> *)titles;
```
那么设置 
```
pageController.keys = @[@"type", @"type", @"type",....., @"type"];  // 个数与控制器数量相同
pageController.values = @[@0, @1, @2, ...... , @n]; // 个数与控制器数量相同
```

在 WMPageController 中， 没有真正意义上的重用控制器，这里的“重用”指的是对一个控制器 class 的重用，即同一 class 不同的实例。
不知道上面的方法是否是你想要的？

**Comment by kaven85** [comment]
好，能解决我的问题
