### ISSUE TITLE
scrollViewDidScroll 里的操作

### ISSUE THREAD

**Issue by chuangchen** [wangmchn/WMPageController#9]
感觉一滚动 ，就在不停调用layoutChildViewControllers，做了很多没意思的操作啊，这个该怎么优化呢？
- (void)scrollViewDidScroll:(UIScrollView *)scrollView{
    [self layoutChildViewControllers];
    if (animate) {
        CGFloat width = scrollView.frame.size.width;
        CGFloat contentOffsetX = scrollView.contentOffset.x;
        CGFloat rate = contentOffsetX / width;
        [self.menuView slideMenuAtProgress:rate];
    }
}

- (void)layoutChildViewControllers{
    int currentPage = (int)self.scrollView.contentOffset.x / viewWidth;
    int start,end;
    if (currentPage == 0) {
        start = currentPage;
        end = currentPage + 1;
    }else if (currentPage + 1 == self.viewControllerClasses.count){
        start = currentPage - 1;
        end = currentPage;
    }else{
        start = currentPage - 1;
        end = currentPage + 1;
    }
    NSLog(@"%s",__func__); //startPage
    for (int i = start; i <= end; i++) {
        NSLog(@"hello");
        CGRect frame = [self.childViewFrames[i] CGRectValue];
        UIViewController *vc = [self.displayVC objectForKey:@(i)];
        if ([self isInScreen:frame]) {
            if (vc == nil) {
                // 先从 cache 中取
                vc = [self.memCache objectForKey:@(i)];
                if (vc) {
                    // cache 中存在，添加到 scrollView 上，并放入display
                    [self addCachedViewController:vc atIndex:i];
                }else{
                    // cache 中也不存在，创建并添加到display
                    [self addViewControllerAtIndex:i];
                }
            }
        }else{
            if (vc) {
                // vc不在视野中且存在，移除他
                [self removeViewController:vc atIndex:i];
            }
        }
    }
}

**Comment by wangmchn** [comment]
确实有一些不必要的操作，优化的话，我想可以根据滚动的位置来调用 `-layoutChildViewControllers`。
因为滚动中间是不会发生子控制器切换的，例如在`iPhone5s`中，宽度 `0~320` 的滚动中，其实只有刚开始和最后结束才会有`add`和`remove`操作，可能在`10~310`范围的滚动（只是举个例子，也可能是`5~315`）并不需要做任何操作，所以可以通过限定范围来减少`layoutChildViewControllers `的调用。
我在`layoutChildViewControllers `中也做了一些简单地优化，精益求精的话可以再添加上述限制操作。
更进一步的优化并没有什么比较好的想法，有待大家进一步提出

**Comment by chuangchen** [comment]
我觉得： 点击标签的时候，方法单独拿出来比较好，不要用scrollViewDidScroll，而且根据标签很容易判断要滚动到的位置（如果是带动画的滚动，会调用scrollViewDidEndScrollingAnimation）。
而手势滑动时候的判断，用方法scrollViewDidEndDecelerating比较好，因为scrollViewDidEndDecelerating是在手势滑动停止的时候调用。

今天研究了下你的代码，意见仅供参考哈。

**Comment by wangmchn** [comment]
嗯有道理！我晚上有空的时候尝试下~thx
