### ISSUE TITLE
我在右边添加的一个btn 把内容遮挡了

### ISSUE THREAD

**Issue by zhouzhiqiang1** [wangmchn/WMPageController#93]
顶部导航栏menuView右边 怎么空一点出来？我在右边添加的一个btn 把内容遮挡了

**Comment by wangmchn** [comment]
menuView有个叫rightView的属性，用法跟navigationBar的rightBarItem相似，可以试下这个属性

**Comment by zhouzhiqiang1** [comment]
谢了     
还有一个
 ViewController One 继承 WMPageController  
然后就是上面的 点击进入一个UIViewController Tow 页面  在页面中写了delegate 
然后我在One 中实现代理  在One中刷新页面[self reloadData];
 然后界面就有问题了（WMScrollView *scrollView  遮挡了 WMMenuView *menuView）
请问是不是在刷新前还要设置什么东西呢？

**Comment by wangmchn** [comment]
能否提供一个 demo？现在不太看得出问题在哪

**Comment by zhouzhiqiang1** [comment]
就是push  页面跳转的地方 改成present   返回在刷新一下，页面就有问题   
或者你把邮箱发我我吧Dome发你

**Comment by wangmchn** [comment]
我的邮箱地址是 wangmchn@163.com
非常感谢

**Comment by wangmchn** [comment]
@zhouzhiqiang1 找到问题所在了，这是个bug我修复一下

**Comment by wangmchn** [comment]
做了修复，你看看问题是否还存在？
