### ISSUE TITLE
menuView都是加到导航栏上面，那有什么方法添加不同页面不同的navagationBar

### ISSUE THREAD

**Issue by 542604974** [wangmchn/WMPageController#95]
我有几个页面要用到WMPageController，menuView都是加到导航栏上面，那有什么方法添加每个页面不同的navagationBar

**Comment by wangmchn** [comment]
不好意思 没太明白你的意思？
你是指你有很多个需要显示在navigationBar上的WMPageController？
``添加每个页面不同的navagationBar`` 这句话没有明白。

**Comment by 542604974** [comment]
这样说吧，我首页就用到WMPageController，但我不想点击tableBar就给WMPageController添加子controller，然后跳转到WMPageController里面去，请问有什么办法呢？

**Comment by 542604974** [comment]
我想用另外的controller来继承WMPageController，这样WMPageController就独立开来了

**Comment by wangmchn** [comment]
可以的，推荐用另外的controller来继承WMPageController

**Comment by 542604974** [comment]
谢谢，OK了
