### ISSUE TITLE
reloadData之后变空白

### ISSUE THREAD

**Issue by Chren** [wangmchn/WMPageController#97]
datasource更改 之后重新reload 界面变空白
但是numbersOfChildControllersInPageController
viewControllerAtIndex这些都有调用到的

**Comment by Chren** [comment]
好像是死循环了

**Comment by wangmchn** [comment]
@Chren 能否提供下例子呀？这样不太能找到问题出在哪里

**Comment by Chren** [comment]
@wangmchn 在viewWillAppear里reloadData会导致空白

**Comment by Chren** [comment]
在异步线程里调用reload也会变空白。
我们的需求是这样的：
dataSource可能会变，变的时候整个页面要重新加载，但是datasource变的时候这个页面不一定在屏幕上的 可能在其他子页面里，kvo监听到dataSource时去reloaddata 就空白了，有没有好的办法解决？
我目前暂时的解决方案是放在viewDidAppear里reloadData，但是会有其他影响。

**Comment by wangmchn** [comment]
在异步线程是肯定不可以调用reload方法的，因为涉及到UI所以必须回到主线程的

viewWillAppear空白的问题我要再看一下，你说的datasource改变是指的datasource不再是WMPageController本身而改变成其他对象是吗？

**Comment by Chren** [comment]
我dispatch到主线程了的
datasource指的是数据 比如原来只有2个栏目 后来变成3个了

**Comment by wangmchn** [comment]
现在的问题是，我没有办法重现到这个bug，如果能够重现可能会比较好解决
