### ISSUE TITLE
希望能自定义下划线到文字之间的距离

### ISSUE THREAD

**Issue by IAMJ** [wangmchn/WMPageController#99]
也就是图中红框那个距离，现在下划线是固定在 menu 底部
![001](https://cloud.githubusercontent.com/assets/2928760/15500374/fcc17952-21da-11e6-9fa2-fe0e12d17206.jpg)

**Comment by wangmchn** [comment]
会增加该功能的

发自我的 iPhone

**Comment by wangmchn** [comment]
现在添加了progressViewBottomSpace属性，可以自定义到menuview底部的距离。
可以使用最新的代码来尝试这个属性，有问题再反馈 😃

**Comment by IAMJ** [comment]
给力，立马升级测试
